Changed text for several Activity titles
Azure/Azure-Sentinel pull request #1030
Opened 2020-09-01 18:21 UTC by YaronFruchtmann

Fixes #

## Proposed Changes

  - Fixed Titles to be different and more generic than Content
  -
  -

2020-09-03 23:50 UTC, shainw requested changes

2020-09-03 23:50 UTC, shainw commented on Insights/InputEntity_Account/AccountsActions.yaml
> +   Title: "The user has deleted account an account"
Should be - "The user has deleted an account"

2020-09-03 23:50 UTC, shainw commented on Insights/InputEntity_Account/AccountsActions.yaml
> +   Description: "This activity displays accounts created by the user"
May want to change to - "This activity displays account creation events performed by the user"

2020-09-03 23:50 UTC, shainw commented on Insights/InputEntity_Account/AccountsActions.yaml
> +   Description: "This activity displays password reset event performed by the user"
Add and 's' to event - "This activity displays password reset event**s** performed by the user"

2020-09-04 06:07 UTC, RoundNutz4 approved these changes

2020-09-04 06:13 UTC, YaronFruchtmann commented on Insights/InputEntity_Account/AzActivity_AzureOps.yaml
> +  | project-rename Target_AzureResource_ResourceId = _ResourceId, Source_IP_Address = CallerIpAddress
So we need to see why it failed the UT. In any case, it is better this way

2020-09-04 15:36 UTC, shainw requested changes

2020-09-04 15:36 UTC, shainw commented on Insights/InputEntity_Account/GroupAdditions.yaml
> +   Content: "The user has added an account to to the Remote Desktop Users group {{Count}} time(s)"
extra **"to"**

2020-09-08 07:41 UTC, merged