Auth0 Authentication parsers
Azure/Azure-Sentinel pull request #10402
Opened 2024-04-27 14:01 UTC by siteshjha11

Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2024-04-30 14:24 UTC, vakohl requested changes

2024-04-30 14:24 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/vimAuth0Authentication.yaml
> +          and ((array_length(srcipaddr_has_any_prefix) == 0) or (has_any_ipv4_prefix(ip_s,srchostname_has_any)))
srchostname_has_any used instead of srcipaddr_has_any_prefix

2024-04-30 14:24 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/vimAuth0Authentication.yaml
> +        //username, Eventtype and eventresult done down in the parser
can we give exact filter names in this description?

2024-04-30 14:24 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/vimAuth0Authentication.yaml
> +     | where((array_length(username_has_any) == 0) or (TargetUsername has_any (username_has_any)))
this filter could be used before.

2024-04-30 14:24 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/imAuthentication.yaml
> +      , vimAuthenticationAuth0                          (starttime=starttime, endtime=endtime,  targetusername_has_any=username_has_any, disabled=(imAuthenticationBuiltInDisabled or('ExcludevimAuthen
please pull latest changes from master

2024-04-30 14:24 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/imAuthentication.yaml
> +      , vimAuthenticationAuth0                          (starttime=starttime, endtime=endtime,  targetusername_has_any=username_has_any, disabled=(imAuthenticationBuiltInDisabled or('ExcludevimAuthen
missing updated filters

2024-04-30 14:24 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/ASimAuthenticationAuth0.yaml
> +     "oidc_backchannel_logout_succeeded","Success","Logoff","Other","Informational","Interactive"
https://auth0.com/docs/deploy-monitor/logs/log-event-type-codes
can we use text in the 'Event' column as EventOriginalResultDetails incases where authentication is failed?

2024-04-30 14:24 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/vimAuth0Authentication.yaml
> +  let parser = (
there is error in query. Couldn't run in LA.

2024-04-30 14:24 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/ASimAuthenticationAuth0.yaml
> +ParserQuery: |
there are error in parser query. couldn't run in LA. Did you test it?

2024-05-03 10:41 UTC, v-atulyadav commented
Hi @siteshjha11,
Please work on above comments and also check for branch conflicts. Thanks

2024-05-03 11:59 UTC, closed without merging