ASimNetworkSessionBarracudaWAF.yaml-33
Azure/Azure-Sentinel pull request #10593
Opened 2024-06-05 10:24 UTC by Alekhya0824

Required items, please complete
   
   Change(s):
   - Created a new file for BaracudeCEF and added BaracudaCEF parser in it. In BaracudaWAF file removed BaracudaCEF parser and in ASimNetworkSession added BaracudeCEF Parser name  and same changes have done for vim as well.

   Reason for Change(s):
   - To Split the BaracudaWAF and BaracudaCEF parser separately

   Version Updated:
   - yes

   Testing Completed:
   - yes

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

2024-06-06 06:50 UTC, v-atulyadav commented
Hi @Alekhya0824,
KQL validation failures, please check for those. Thanks
<img width="460" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/104008048/a0bf6452-b8f4-4c7a-81ed-f2dedb41e8a8">

2024-06-11 12:10 UTC, v-atulyadav commented
Hi @Alekhya0824,
Validations failing please check. Thanks

2024-07-16 06:04 UTC, vakohl requested changes

2024-07-16 06:04 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionBarracudaCEF.yaml
> +  let barracudaSchema = datatable(
we dont need this schema for CEF parser

2024-07-17 05:38 UTC, Alekhya0824 commented on .gitignore
> -.DS_Store
after updating schema...it's considering old schema file so to consider new schema update added this line

2024-07-17 05:49 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionBarracudaCEF.yaml
> +  let barracudaSchema = datatable(
done

2024-07-17 05:49 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionBarracudaWAF.yaml
>  Parser:
done

2024-07-17 05:49 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionBarracudaCEF.yaml
> +Parser:
done

2024-07-17 05:49 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionBarracudaWAF.yaml
>  Parser:
done

2024-07-17 05:49 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionBarracudaCEF.yaml
> +Parser:
done

2024-07-17 05:49 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionBarracudaWAF.yaml
>  - Title: Logs type Description in Barracuda WAF
done

2024-07-17 05:49 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionBarracudaWAF.yaml
> +  LastUpdated: Jun 5 2024
done

2024-07-17 05:50 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionBarracudaCEF.yaml
> +  Link: https:/aka.ms/AboutASIM
done

2024-07-17 05:50 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionBarracudaCEF.yaml
> +  LastUpdated: JunE 5 2024
done

2024-07-17 05:50 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionBarracudaWAF.yaml
> +  LastUpdated: JunE 5 2024
done

2024-07-17 05:50 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionBarracudaCEF.yaml
> +  Link: https:/aka.ms/AboutASIM
done

2024-07-17 05:50 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionBarracudaCEF.yaml
> +  LastUpdated: June 5 2024
done

2024-07-18 05:05 UTC, v-atulyadav commented
Hi @Alekhya0824,
I can see a few open comments from the reviewer, and PR is also having failed validations. Please act on them. 
<img width="618" alt="image" src="https://github.com/user-attachments/assets/8f6fbe8d-42c0-4873-af1e-303af271ad98">

And also, one suggestion: once you're done with the open comment change, please click on the `Resolve Conversation` button.
<img width="577" alt="image" src="https://github.com/user-attachments/assets/ab9c6aa3-ddb2-4fd0-a732-b893f5d1c9c4">

2024-07-23 06:21 UTC, v-atulyadav commented
Hi @Alekhya0824,
Please act on above comments and also look for validations that failed. Thanks

2024-07-26 09:36 UTC, Alekhya0824 commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionBarracudaWAF.yaml
>  Parser:
As data is not there in workspace so closing this comment

2024-07-29 06:02 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionBarracudaWAF.yaml
>  Parser:
please un-comment
![image](https://github.com/user-attachments/assets/0f066171-fcd3-4522-9806-97f27f64d5cd)

2024-07-30 18:21 UTC, vakohl approved these changes

2024-07-31 04:28 UTC, v-atulyadav approved these changes

2024-07-31 04:28 UTC, merged