ASimFileEventMicrosoftSysmon.yaml-27
Azure/Azure-Sentinel pull request #10605
Opened 2024-06-06 10:21 UTC by Alekhya0824

Required items, please complete
   
   Change(s):
   - Created a new file for WindowsEvent and added WindowsEvent parser in it. In Event file removed WindowsEvent parser and in ASimFileEvent added WindowsEvent Parser name  and same changes have done for vim as well.

   Reason for Change(s):
   - To Split the WindowsEven and Event parser separately

   Version Updated:
   - yes

   Testing Completed:
   - yes

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

2024-06-07 06:02 UTC, v-atulyadav commented
Hi @Alekhya0824,
Please check below failed KQL validation. Thanks
<img width="677" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/104008048/5e3a2e6e-ddb6-4744-8b83-b60196868c25">

2024-06-11 12:11 UTC, v-atulyadav commented
Hi @Alekhya0824,
Validations failing please check. Thanks

2024-07-17 09:44 UTC, vakohl requested changes

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmon.yaml
> +  LastUpdated: June 6 2024
date correction

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmonWindowsEvent.yaml
> +  LastUpdated: June 6 2024
date correction

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmon.yaml
> +  LastUpdated: June 6 2024
date correction

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmonWindowsEvent.yaml
> +  LastUpdated: June 6 2024
date correction

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmon.yaml
>  Parser:
(1) Warning: Missing recommended field [EventUid]

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmonWindowsEvent.yaml
> +Parser:
(1) Warning: Missing recommended field [EventUid]

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmon.yaml
>  Parser:
(1) Warning: Missing recommended field [EventUid]

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmonWindowsEvent.yaml
> +Parser:
(1) Warning: Missing recommended field [EventUid]

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/test/Microsoft_Sysmon_ASimFileEvent_DataTest.csv
> +"(0) Error: 1 invalid value(s) (up to 10 listed) in 10 records (100.0%) for field [HashType] of type [Enumerated]: [""SHA256""] (Schema:FileEvent)"
can we check this error?

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/test/Microsoft_Sysmon_VimFileEvent_DataTest.csv
> +"(0) Error: 1 invalid value(s) (up to 10 listed) in 10 records (100.0%) for field [HashType] of type [Enumerated]: [""SHA256""] (Schema:FileEvent)"
please check

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/test/Microsoft_Sysmon_Windows_Even_VimFileEvent_DataTest.csv
> +"(0) Error: 1 invalid value(s) (up to 10 listed) in 10 records (100.0%) for field [HashType] of type [Enumerated]: [""SHA256""] (Schema:FileEvent)"
please check

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmon.yaml
> +  This ASIM parser supports normalizing Sysmon event 11, 23, and 26, stored in either the Event or WindowsEvent tables, logs ingested in 'Event' table to the ASIM file event schema.
description doesn't seem right

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmonWindowsEvent.yaml
> +  This ASIM parser supports normalizing Sysmon event 11, 23, and 26, stored in either the Event or WindowsEvent tables, logs ingested in 'WindowsEvent' table to the ASIM file event schema.
description doesn't seem right

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmon.yaml
> +  This ASIM parser supports normalizing Sysmon event 11, 23, and 26, stored in either the Event or WindowsEvent tables, logs ingested in 'Event' table to the ASIM file event schema.
description doesn't seem right

2024-07-17 09:44 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmonWindowsEvent.yaml
> +  This ASIM parser supports normalizing Sysmon event 11, 23, and 26, stored in either the Event or WindowsEvent tables, logs ingested in 'WindowsEvent' table to the ASIM file event schema.
description doesn't seem right

2024-07-19 06:54 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmon.yaml
> +  LastUpdated: June 6 2024
Done

2024-07-19 06:54 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmonWindowsEvent.yaml
> +  LastUpdated: June 6 2024
Done

2024-07-19 06:54 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmonWindowsEvent.yaml
> +  LastUpdated: June 6 2024
Done

2024-07-19 06:54 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmon.yaml
>  Parser:
Done

2024-07-19 06:54 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmonWindowsEvent.yaml
> +Parser:
Done

2024-07-19 06:54 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmon.yaml
>  Parser:
Done

2024-07-19 06:54 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmonWindowsEvent.yaml
> +Parser:
Done

2024-07-19 06:55 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmon.yaml
> +  This ASIM parser supports normalizing Sysmon event 11, 23, and 26, stored in either the Event or WindowsEvent tables, logs ingested in 'Event' table to the ASIM file event schema.
Done

2024-07-19 06:55 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmonWindowsEvent.yaml
> +  This ASIM parser supports normalizing Sysmon event 11, 23, and 26, stored in either the Event or WindowsEvent tables, logs ingested in 'WindowsEvent' table to the ASIM file event schema.
Done

2024-07-19 06:55 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmon.yaml
> +  This ASIM parser supports normalizing Sysmon event 11, 23, and 26, stored in either the Event or WindowsEvent tables, logs ingested in 'Event' table to the ASIM file event schema.
Done

2024-07-22 08:58 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmonWindowsEvent.yaml
> +  This ASIM parser supports normalizing Sysmon event 11, 23, and 26, stored in either the Event or WindowsEvent tables, logs ingested in 'WindowsEvent' table to the ASIM file event schema.
done

2024-07-24 09:00 UTC, v-atulyadav commented
Hi @Alekhya0824,
Please work on open comment. Thanks

2024-07-26 09:28 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/test/Microsoft_Sysmon_VimFileEvent_DataTest.csv
> +"(0) Error: 1 invalid value(s) (up to 10 listed) in 10 records (100.0%) for field [HashType] of type [Enumerated]: [""SHA256""] (Schema:FileEvent)"
added supported values in ARM tester

2024-07-26 09:28 UTC, Alekhya0824 commented on Parsers/ASimFileEvent/test/Microsoft_Sysmon_Windows_Even_VimFileEvent_DataTest.csv
> +"(0) Error: 1 invalid value(s) (up to 10 listed) in 10 records (100.0%) for field [HashType] of type [Enumerated]: [""SHA256""] (Schema:FileEvent)"
added supported values in ARM tester

2024-07-29 12:32 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmonWindowsEvent.yaml
> +          //EventUid = _ItemId,
please remove this

2024-07-29 13:39 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/ASimFileEventMicrosoftSysmonWindowsEvent.yaml
> +           //EventUid = _ItemId,
I've removed it.

2024-07-29 13:39 UTC, vakohl commented on Parsers/ASimFileEvent/Parsers/vimFileEventMicrosoftSysmonWindowsEvent.yaml
> +          //EventUid = _ItemId,
I've removed it.

2024-07-29 13:39 UTC, vakohl approved these changes

2024-07-30 04:53 UTC, v-atulyadav approved these changes

2024-07-30 04:54 UTC, merged