Audit Native Parser
Azure/Azure-Sentinel pull request #11561
Opened 2024-12-13 13:11 UTC by Alekhya0824

Required items, please complete

Change(s):

created native AuditEvent parser for both vim and asim and added these names in AsimAuditEvent.yaml and imAuditEvent.yaml
Reason for Change(s):

native parser is not there for authentication so created
Version Updated:

yes
Testing Completed:

yes
Checked that the validations are passing and have addressed any issues that are present:

yes

2024-12-16 05:45 UTC, v-prasadboke commented
Hello @Alekhya0824, Please try to add missing columns for specific tables mentioned in KQL validation failures

2025-01-07 09:52 UTC, vakohl requested changes

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/ASimAuditEventNative.yaml
> +  Version: '0.1.1'
0.1.0

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/ASimAuditEventNative.yaml
> +          _ResourceId, _SubscriptionId,RuleName,SrcIpAddr
please remove comment
why we are projecting away RuleName and SrcIpAddr?

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +  Version: '0.1.1'
0.1.0

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +          _ResourceId, _SubscriptionId,RuleName,SrcIpAddr
why were projecting away RuleName and SrcIpAddr?

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +          Rule=RuleName
please add following:
| project-rename
          EventUid = _ItemId

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +
(1) Warning: Missing recommended field [EventUid]
(1) Warning: Missing recommended field [SrcIpAddr]
(1) Warning: Missing recommended field [Src]

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +
please fix above warnings

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +
please remove this line from tester.csv https://github.com/Azure/Azure-Sentinel/blob/master/ASIM/dev/ASimTester/ASimTester.csv
![image](https://github.com/user-attachments/assets/b8e5ae08-e3c7-42a0-a84b-e755a47d728d)

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +  LastUpdated: Dec 13, 2024
please check these warnings
(1) Warning: Missing recommended field [EventUid]
(1) Warning: Missing recommended field [SrcIpAddr]
(1) Warning: Missing recommended field [Src]

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/ASimAuditEventNative.yaml
> +          _ResourceId, _SubscriptionId,RuleName,SrcIpAddr
please check these warnings:
(1) Warning: Missing recommended field [EventUid]
(1) Warning: Missing recommended field [SrcIpAddr]
(1) Warning: Missing recommended field [Src]

2025-01-07 09:52 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/ASimAuditEventNative.yaml
> +  };
please add following:
| project-rename
EventUid = _ItemId

2025-01-07 09:52 UTC, vakohl commented on Sample Data/ASIM/Microsoft_Azure_AuditEvent_IngestedLogs.csv
> +Security Logs",Set,"{""Authorization"":null,""Claims"":null,""Error"":null}",12.165.175.103,user2@qwert123456789kjhgfdsaqwertyui.com,Azure,Azure,14.143.170.130,user2@qwert123456789kjhgfdsaqwertyui.co
please remove new line before Security Logs, its causing exception

2025-01-07 09:52 UTC, vakohl commented on Sample Data/ASIM/Microsoft_Azure_AuditEvent_IngestedLogs.csv
> +Security Logs",Create,"{""Authorization"":null,""Claims"":null,""Error"":null}",12.165.175.103,user5@qwert123456789kjhgfdsaqwertyui.com,Azure,Azure,14.143.170.130,user5@qwert123456789kjhgfdsaqwertyui
please remove new line

2025-01-07 09:57 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/ASimAuditEventNative.yaml
> +          _ResourceId, _SubscriptionId,RuleName,SrcIpAddr
EventStartTime = TimeGenerated,
          EventEndTime = TimeGenerated,

2025-01-07 09:58 UTC, vakohl commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +    | extend EventVendor='Microsoft',
EventStartTime = TimeGenerated,
          EventEndTime = TimeGenerated,

2025-01-07 13:00 UTC, Alekhya0824 commented on .script/tests/asimParsersTest/ExclusionListForASimTests.csv
> +_Im_AuditEvent_Native
done

2025-01-07 13:22 UTC, Alekhya0824 commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +          Rule=RuleName
done

2025-01-07 13:29 UTC, Alekhya0824 commented on Parsers/ASimAuditEvent/Parsers/ASimAuditEventNative.yaml
> +          _ResourceId, _SubscriptionId,RuleName,SrcIpAddr
done

2025-01-07 13:29 UTC, Alekhya0824 commented on Parsers/ASimAuditEvent/Parsers/ASimAuditEventNative.yaml
> +  };
done

2025-01-07 13:29 UTC, Alekhya0824 commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +  Version: '0.1.1'
done

2025-01-07 13:29 UTC, Alekhya0824 commented on Parsers/ASimAuditEvent/Parsers/ASimAuditEventNative.yaml
> +  Version: '0.1.1'
done

2025-01-09 09:40 UTC, Alekhya0824 commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +  LastUpdated: Dec 13, 2024
done

2025-01-09 09:40 UTC, Alekhya0824 commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +          _ResourceId, _SubscriptionId,RuleName,SrcIpAddr
done

2025-01-09 09:41 UTC, Alekhya0824 commented on Parsers/ASimAuditEvent/Parsers/ASimAuditEventNative.yaml
> +          _ResourceId, _SubscriptionId,RuleName,SrcIpAddr
done

2025-01-09 10:28 UTC, Alekhya0824 commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +
done

2025-01-16 09:29 UTC, Alekhya0824 commented on Sample Data/ASIM/Microsoft_Azure_AuditEvent_IngestedLogs.csv
> +﻿Operation,ActorSessionId,SrcIpAddr,EventOriginalType_string,EventOriginalType_int,EventOriginalUid,TimeGenerated [UTC],Type,_ItemId,_ResourceId,EventCount,EventStartTime [UTC],EventEndTime [UTC],Eve
done

2025-01-16 09:35 UTC, Alekhya0824 commented on Sample Data/ASIM/Microsoft_Azure_AuditEvent_IngestedLogs.csv
> +Security Logs",Create,"{""Authorization"":null,""Claims"":null,""Error"":null}",12.165.175.103,user5@qwert123456789kjhgfdsaqwertyui.com,Azure,Azure,14.143.170.130,user5@qwert123456789kjhgfdsaqwertyui
done

2025-01-16 10:04 UTC, Alekhya0824 commented on Parsers/ASimAuditEvent/Parsers/vimAuditEventNative.yaml
> +
done

2025-01-17 08:21 UTC, vakohl commented on .script/tests/asimParsersTest/ExclusionListForASimTests.csv
> +ParserName
please undo this change

2025-01-17 11:33 UTC, Alekhya0824 commented on .script/tests/asimParsersTest/ExclusionListForASimTests.csv
> +ParserName
done

2025-01-17 12:02 UTC, vakohl approved these changes

2025-01-17 12:08 UTC, v-atulyadav approved these changes

2025-01-17 12:08 UTC, merged