Connector syslog watch guard firebox
Azure/Azure-Sentinel pull request #1165
Opened 2020-10-10 09:47 UTC by ecosystempo

Fixes #

## Proposed Changes

  -
  -
  -

2020-10-10 09:48 UTC, ecosystempo commented
Update WatchGuard Data Connector

2020-10-28 23:38 UTC, nazang requested changes

2020-10-28 23:38 UTC, nazang commented on DataConnectors/Connector_syslog_WatchGuardFirebox.json
> +            "name": "Syslog(Firebox)",
Syslog (Firebox)  

Make sure there is a space before bracket.

2020-10-28 23:38 UTC, nazang commented on DataConnectors/Connector_syslog_WatchGuardFirebox.json
> +    "availability": {
Set preview flag for now:

"availability": { 
            "status": 1,
            "isPreview": true
            },

2020-10-28 23:38 UTC, nazang commented on DataConnectors/Connector_syslog_WatchGuardFirebox.json
> +    "title": "Firebox",
Title should be Provider Name and Appliance Name:

WatchGuard Firebox

2020-10-28 23:38 UTC, nazang commented on DataConnectors/Connector_syslog_WatchGuardFirebox.json
> +    "publisher": "Watchguard",
provide should match the company name in cases:

WatchGuard or WatchGuard Technologies

2020-10-28 23:38 UTC, nazang commented on DataConnectors/Connector_syslog_WatchGuardFirebox.json
> +    "graphQueries": [
[critical missing parts] Parser should be defined and include the defined alias and link into the subscription.

2020-10-28 23:38 UTC, nazang commented on DataConnectors/Connector_syslog_WatchGuardFirebox.json
> +            "legend": "Watchguard",
legend should be "WatchGuard Firebox"

2020-10-28 23:38 UTC, nazang commented on DataConnectors/Connector_syslog_WatchGuardFirebox.json
> +            "baseQuery": "Firebox"
"baseQuery": "DATATYPE_NAME", Validate DATATYPE_NAME represent both provider, appliance name and type of data [optionally] as a short name in the data type name.

DATATYPE_NAME should be WatchGuardFirebox

2020-10-28 23:38 UTC, nazang commented on DataConnectors/Connector_syslog_WatchGuardFirebox.json
> +            "description": ">This data connector depends on a parser based on a Kusto Function to work as expected. [Follow these steps](Link to Kusto Function on Azure Sentinel GitHub) to create the
Again, this should have the function alias defined and has a valid link to the function.

2020-11-25 06:04 UTC, closed without merging