ACN_CD_CiscoUCS_Connector01
Azure/Azure-Sentinel pull request #1281
Opened 2020-11-09 21:37 UTC by chicduong

#  Proposed Changes

  - Cisco UCS - Data connector page JSON
  - Cisco UCS - Sample Data JSON
  -

2020-11-11 02:04 UTC, v-jayakal requested changes

2020-11-11 02:54 UTC, chicduong commented on DataConnectors/Cisco UCS/Connector_Syslog_CiscoUCS.json
> +    "title": "Cisco UCS (Preview)",
changes have been made and resubmitted

2020-11-11 02:54 UTC, chicduong commented on DataConnectors/Cisco UCS/Connector_Syslog_CiscoUCS.json
> +         "legend": "Cisco UCS",
changes have been made and resubmitted

2020-11-11 02:55 UTC, chicduong commented on DataConnectors/Cisco UCS/Connector_Syslog_CiscoUCS.json
> +    "additionalRequirementBanner":"These queries and workbooks are dependent on a parser based on a Kusto Function to work as expected. Follow the steps to use this Kusto functions alias **CiscoUCS**
Parser URL changed to https://aka.ms/sentinelgithubparsersciscoucs as a place holder. @preetikr to create the official URL

2020-11-11 02:55 UTC, chicduong commented on DataConnectors/Cisco UCS/Connector_Syslog_CiscoUCS.json
> +                    "description": ">This data connector depends on a parser based on a Kusto Function to work as expected. [Follow the steps](https://aka.ms/sentinelgithubparserssymantecvip) to use
Parser URL changed to https://aka.ms/sentinelgithubparsersciscoucs as a place holder. @preetikr to create the official URL

2020-11-13 22:38 UTC, v-jayakal commented on DataConnectors/Cisco UCS/Connector_Syslog_CiscoUCS.json
> +    "additionalRequirementBanner":"These queries and workbooks are dependent on a parser based on a Kusto Function to work as expected. Follow the steps to use this Kusto functions alias **CiscoUCS**
Please update PR with redirection link : https://aka.ms/sentinel-ciscoucs-function.

2020-11-13 22:38 UTC, v-jayakal commented on DataConnectors/Cisco UCS/Connector_Syslog_CiscoUCS.json
> +                    "description": ">This data connector depends on a parser based on a Kusto Function to work as expected. [Follow the steps](https://aka.ms/sentinelgithubparserssymantecvip) to use
Please update PR with redirection link : https://aka.ms/sentinel-ciscoucs-function.

2020-11-13 22:44 UTC, chicduong commented on DataConnectors/Cisco UCS/Connector_Syslog_CiscoUCS.json
> +    "additionalRequirementBanner":"These queries and workbooks are dependent on a parser based on a Kusto Function to work as expected. Follow the steps to use this Kusto functions alias **CiscoUCS**
links have been updated

2020-11-13 22:45 UTC, chicduong commented on DataConnectors/Cisco UCS/Connector_Syslog_CiscoUCS.json
> +                    "description": ">This data connector depends on a parser based on a Kusto Function to work as expected. [Follow the steps](https://aka.ms/sentinelgithubparserssymantecvip) to use
links have been updated

2020-11-13 22:58 UTC, v-jayakal approved these changes

2020-11-13 23:02 UTC, nazang approved these changes

2020-11-13 23:03 UTC, merged