ACN_CD_VMwareESXi_Parser01
Azure/Azure-Sentinel pull request #1310
Opened 2020-11-13 21:18 UTC by chicduong

## Proposed Changes

  - VMWareESXi Parser Function

2020-11-16 20:41 UTC, shainw requested changes
After changing the OpId regex, I would suggest validation of the UserName regex since I don't see it in the sample.

2020-11-16 21:33 UTC, chicduong commented on Parsers/VMwareESXi/VMwareESXi.txt
> +         OpId = extract(@"opID=([\w\d\(\)\-]+)\s",1, Substring),
updates have been made, added \s?\]? at the end to account for spaces and close brackets

2020-11-16 21:34 UTC, chicduong commented on Parsers/VMwareESXi/VMwareESXi.txt
> +         UserName = extract(@"\suser=([\w\d\(\)\-]+)\]",1, Substring)
user appears on some records (not all) after OpId

2020-11-17 22:35 UTC, shainw approved these changes

2020-11-17 22:35 UTC, merged