Thycotic update logos
Azure/Azure-Sentinel pull request #1358
Opened 2020-11-24 08:44 UTC by AndyNikolaev

Fixes #

## Proposed Changes

  -
  -
  -

2020-11-24 08:48 UTC, AndyNikolaev commented
@nazang 
made the appropriate changes to repo

2020-11-24 22:05 UTC, nazang requested changes

2020-11-24 22:05 UTC, nazang commented on Dashboards/Images/Logos/ThycoticLogo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 75 75">
Please remove xmlns:xlink="http://www.w3.org/1999/xlink" from logo file. 

All the other changes look good. @AndyNikolaev, Thank you for update!

Logo check list:
https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/ReadMe.md

The company logo adhering to the following requirements in the 'Logo' folder
Logo needs to be in SVG format and under 5 Kb
Ensure raw file of logo does not have any of the following:
cls and style formats
embedded png formats
xmlns:xlink
data-name

2020-11-25 06:41 UTC, AndyNikolaev commented
@nazang 
Fixed

2020-11-25 21:51 UTC, nazang approved these changes

2020-11-25 21:51 UTC, merged