New Alsid for AD connector, workbooks and analytics templates
Azure/Azure-Sentinel pull request #1368
Opened 2020-11-25 14:40 UTC by Azomasiel

# Proposed Changes

  - Alsid for AD Syslog connector
  - Alsid for AD Indicators of exposure workbook
  - Alsid for AD Indicators of exposure analytic rules

2020-12-02 02:23 UTC, shainw requested changes
Validations will fail on all the Detection YAML's because the table schema cannot be identified.  In order to work around this, you will need to provide a Custom Table schema here - https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables.  They are simple JSON format.  The name of the table goes at that top in the name field, in your case it would be "afad_parser".  Then the schema follows in the Properties key value pair section.

2020-12-02 02:23 UTC, shainw commented on Parsers/Alsid/afad_parser.kql
> +// Usage Instruction :
Parser should follow the standard format, example from this - https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/PulseConnectSecure/PulseConnectSecure.txt.  Need to get a Wiki update to include required template for parsers, but you can use the PulseConnectSecure version as a template.

2020-12-06 16:58 UTC, shainw requested changes

2020-12-06 16:58 UTC, shainw commented on Detections/AlsidForAD/ADAttacksPathways.yaml
> +  | where MessageType == 0 and (Codename == "C-PRIV-ACCOUNTS-SPN" or Codename == "C-SDPROP-CONSISTENCY" or Codename == "C-DANG-PRIMGROUPID" or Codename == "C-GPO-HARDENING" or Codename == "C-DC-ACCES
Missed this on the first pass.  Much more readable if you create a list for this and use the 'in' operator.  Change to -

let codeNameList = ("C-PRIV-ACCOUNTS-SPN", "C-SDPROP-CONSISTENCY", "C-DANG-PRIMGROUPID", "C-GPO-HARDENING", "C-DC-ACCESS-CONSISTENCY", "C-DANGEROUS-TRUST-RELATIONSHIP", "C-UNCONST-DELEG", "C-ABNORMAL-ENTRIES-IN-SCHEMA");
afad_parser
| where MessageType == 0 and codeNameList in~ (codeNameList)

2020-12-06 16:58 UTC, shainw commented on Detections/AlsidForAD/PasswordIssues.yaml
> +  | where MessageType == 0 and (Codename == "C-CLEARTEXT-PASSWORD" or Codename == "C-PASSWORD-DONT-EXPIRE" or Codename == "C-USER-REVER-PWDS" or Codename == "C-PASSWORD-POLICY" or Codename == "C-USER
Change to List, same as I had shown in "Alsid Active Directory attacks pathways" detection.

2020-12-06 16:58 UTC, shainw commented on Detections/AlsidForAD/PrivilegedAccountIssues.yaml
> +  | where MessageType == 0 and (Codename == "C-PRIV-ACCOUNTS-SPN" or Codename == "C-NATIVE-ADM-GROUP-MEMBERS" or Codename == "C-KRBTGT-PASSWORD" or Codename == "C-PROTECTED-USERS-GROUP-UNUSED" or Cod
Change to List, same as I had shown in "Alsid Active Directory attacks pathways" detection.

2020-12-06 16:58 UTC, shainw commented on Detections/AlsidForAD/UserAccountIssues.yaml
> +  | where MessageType == 0 and (Codename == "C-ACCOUNTS-DANG-SID-HISTORY" or Codename == "C-PRE-WIN2000-ACCESS-MEMBERS" or Codename == "C-PASSWORD-DONT-EXPIRE" or Codename == "C-SLEEPING-ACCOUNTS" or
Change to List, same as I had shown in "Alsid Active Directory attacks pathways" detection.

2020-12-07 03:04 UTC, v-jayakal requested changes

2020-12-07 03:06 UTC, v-jayakal commented on DataConnectors/AlsidForAD.json
> +            "query" : "\/\/ Usage Instruction :\r\n\/\/ Paste below query in log analytics, click on Save button and select as Function from drop down by specifying function name and alias (e.g. afad
Can you please provide sample data in json format?

2020-12-09 03:46 UTC, v-jayakal commented
Sample data file name should be 'AlsidForADLog_CL.json' as per Sentinel Guidelines. Can you please change the name of the file from 'AlsidForAd.json'  to 'AlsidForADLog_CL.json'?

2020-12-09 03:46 UTC, v-jayakal requested changes

2020-12-09 03:46 UTC, v-jayakal commented on Parsers/Alsid/afad_parser.kql
> +"C-LAPS-UNSECURE-CONFIG", "Local administrative account management"
missing , (comma) at the end of this line.

2020-12-09 03:46 UTC, v-jayakal commented on Parsers/Alsid/afad_parser.kql
> +
Remove space on this line (line number 66), otherwise, CodenameTable will not be recognized.

2020-12-09 20:29 UTC, shainw commented
There is a JSON validation failure, but I am not sure it is accurate - "Incorrect Json file. File path: Sample Data/Syslog/AlsidForADLog_CL.json. Error message: Unexpected token ﻿ in JSON at position 0".  I checked the file manually and seems fine.  @sagamzu who is the author of the JSON validations, thoughts here?

2020-12-11 05:51 UTC, nazang commented
> There is a JSON validation failure, but I am not sure it is accurate - "Incorrect Json file. File path: Sample Data/Syslog/AlsidForADLog_CL.json. Error message: Unexpected token ﻿ in JSON at position 0". I checked the file manually and seems fine. @sagamzu who is the author of the JSON validations, thoughts here?

2020-12-11 05:58 UTC, nazang commented
> There is a JSON validation failure, but I am not sure it is accurate - "Incorrect Json file. File path: Sample Data/Syslog/AlsidForADLog_CL.json. Error message: Unexpected token ﻿ in JSON at position 0". I checked the file manually and seems fine. @sagamzu who is the author of the JSON validations, thoughts here?

Same failure for the next PR "Dark trace connector" as well, copy out the json and validate manually, seems fine. @sagamzu, could you help to take a look?

2020-12-11 21:25 UTC, nazang requested changes

2020-12-11 21:25 UTC, nazang commented on Workbooks/Images/Logos/Alsid.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 477.51 515.81"><defs><style>.cls-1{fill:#1b2b44;}.cls-2{fill:#0d06b9;}</style></defs><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-na
The logo id attribute has to be a unique id. Could you update:

id="Layer_2"  -->  id="\<generated guid>"
id="Layer_1-2" -->  id="\<generated guid>"

2020-12-12 01:22 UTC, v-jayakal commented
@Azomasiel, there is a special character in AlsidForADLog_CL.json file, Please check the PR that removes that character, approve and merge into AlsidOfficial:AFAD-connector branch. OR you can do the change in your branch in AlsidForADLog_CL.json file.
PR: https://github.com/AlsidOfficial/Azure-Sentinel/pull/2/files
Logo is also invalid, it has id (which should have guids for unique identification) and also has style, which is not allowed. Please refer logo guidelines here: https://github.com/Azure/Azure-Sentinel/blob/e1665d4c4442b430d6847adc65f4b9c25f7b071f/DataConnectors/ReadMe.md.
Made changes to the logo attached to be along the guidelines and attaching it here for your verification and if you are fine with this version, please update the logo (workbook as well as data connector) with this OR any other valid logo.
[Alsid.zip](https://github.com/Azure/Azure-Sentinel/files/5682271/Alsid.zip)

2020-12-14 09:33 UTC, v-jayakal approved these changes

2020-12-14 18:40 UTC, nazang approved these changes

2020-12-14 22:45 UTC, shainw approved these changes

2020-12-14 22:45 UTC, merged