Apache HTTP Server Data Connector
Azure/Azure-Sentinel pull request #1373
Opened 2020-11-26 16:34 UTC by socprime

## Proposed Changes

  - added Apache HTTP Server Data Connector

2020-12-07 23:55 UTC, v-jayakal requested changes

2020-12-08 13:16 UTC, socprime commented on DataConnectors/ApacheHTTPServer/Connector_ApacheHTTPServer_agent.json
> +    "id": "Apache HTTP Server",
done

2020-12-09 00:58 UTC, v-jayakal requested changes

2020-12-09 00:58 UTC, v-jayakal commented on DataConnectors/ApacheHTTPServer/Connector_ApacheHTTPServer_agent.json
> +            "legend": "Apache Events",
ApacheHTTPServer_CL is the value for legend as DATATYPE_NAME is expected.

2020-12-09 00:58 UTC, v-jayakal approved these changes

2020-12-09 01:32 UTC, nazang approved these changes

2020-12-09 01:32 UTC, merged