ACN_CD_SymantecEndpointProtection_Parser01
Azure/Azure-Sentinel pull request #1388
Opened 2020-12-02 00:22 UTC by chicduong

## Proposed Changes

  - Symantec Endpoint Protection Parser
  + Sample Data

2020-12-06 16:37 UTC, shainw requested changes
Some minor fixes, also in the sample JSON, there is no LogTypes for AgentSecurityLogs and AgentPacketLogs.  Might be good to include those, although, not required.

2020-12-06 16:37 UTC, shainw commented on Parsers/SymantecEndpointProtection/SymantecEndpointProtection.txt
> +Syslog
Missing 'let LogHeader = Syslog'

2020-12-06 16:37 UTC, shainw commented on Parsers/SymantecEndpointProtection/SymantecEndpointProtection.txt
> +| where LogType !in ("Agent System Logs","Agent Activity Logs","Agent Behavior Logs", "Agent Traffic Logs","Agent Traffic Logs","Agent Security Logs", "Agent Packet Logs");
"Agent Traffic Logs" is listed twice

2020-12-06 18:59 UTC, chicduong commented on Parsers/SymantecEndpointProtection/SymantecEndpointProtection.txt
> +| where LogType !in ("Agent System Logs","Agent Activity Logs","Agent Behavior Logs", "Agent Traffic Logs","Agent Traffic Logs","Agent Security Logs", "Agent Packet Logs");
corrections made

2020-12-06 18:59 UTC, chicduong commented on Parsers/SymantecEndpointProtection/SymantecEndpointProtection.txt
> +Syslog
corrections made

2020-12-08 02:11 UTC, v-jayakal approved these changes

2020-12-09 20:13 UTC, shainw approved these changes

2020-12-09 20:13 UTC, merged