including new entity mapping information
Azure/Azure-Sentinel pull request #1392
Opened 2020-12-02 16:20 UTC by shainw

Fixes #

## Proposed Changes

  -
  -
  -

2020-12-02 18:43 UTC, ashwin-patil requested changes
Other than Typo - rest looks good.

2020-12-02 18:43 UTC, ashwin-patil commented on Detections/AuditLogs/MaliciousOAuthApp_O365AttackToolkit.yaml
> +  | extend timestamp = TimeGenerated, AccountCustomEntity = GrantInitiatedBy, IPCusomtEntity = GrantIpAddress
Typo - IPCusomtEntity

2020-12-02 18:43 UTC, ashwin-patil commented on Detections/AuditLogs/MaliciousOAuthApp_PwnAuth.yaml
> +  | extend timestamp = TimeGenerated, AccountCustomEntity = GrantInitiatedBy, IPCusomtEntity = GrantIpAddress
Typo - IPCusomtEntity

2020-12-02 18:43 UTC, ashwin-patil commented on Detections/AuditLogs/NewAppOrServicePrincipalCredential.yaml
> +  | extend timestamp = TimeGenerated, AccountCustomEntity = InitiatingUserOrApp, IPCusomtEntity = InitiatingIpAddress
Typo - IPCusomtEntity

2020-12-02 18:43 UTC, ashwin-patil commented on Detections/AuditLogs/SuspiciousOAuthApp_OfflineAccess.yaml
> +  | extend timestamp = TimeGenerated, AccountCustomEntity = GrantInitiatedBy, IPCusomtEntity = GrantIpAddress
Typo - IPCusomtEntity

2020-12-03 16:56 UTC, laithhisham requested changes
Looks great
just the typos that Ashwin mentioned

2020-12-03 17:55 UTC, shainw commented on Detections/AuditLogs/SuspiciousOAuthApp_OfflineAccess.yaml
> +  | extend timestamp = TimeGenerated, AccountCustomEntity = GrantInitiatedBy, IPCusomtEntity = GrantIpAddress
thanks!

2020-12-03 17:55 UTC, shainw commented on Detections/AuditLogs/NewAppOrServicePrincipalCredential.yaml
> +  | extend timestamp = TimeGenerated, AccountCustomEntity = InitiatingUserOrApp, IPCusomtEntity = InitiatingIpAddress
thanks!

2020-12-03 17:55 UTC, shainw commented on Detections/AuditLogs/MaliciousOAuthApp_PwnAuth.yaml
> +  | extend timestamp = TimeGenerated, AccountCustomEntity = GrantInitiatedBy, IPCusomtEntity = GrantIpAddress
thanks!

2020-12-03 17:55 UTC, shainw commented on Detections/AuditLogs/MaliciousOAuthApp_O365AttackToolkit.yaml
> +  | extend timestamp = TimeGenerated, AccountCustomEntity = GrantInitiatedBy, IPCusomtEntity = GrantIpAddress
thanks!

2020-12-03 17:56 UTC, laithhisham approved these changes

2020-12-03 18:02 UTC, merged