ACN_CD_QualysKB_Connector01
Azure/Azure-Sentinel pull request #1412
Opened 2020-12-05 06:54 UTC by chicduong

## Proposed Changes

  - Qualys KnowledgeBase Function App 
  - Qualys KB Connector Page

2020-12-10 00:06 UTC, erant10 approved these changes

2020-12-10 06:25 UTC, v-jayakal requested changes

2020-12-10 06:49 UTC, chicduong commented on DataConnectors/Qualys KB/QualysKB_API_FunctionApp.json
> +        ],
correction made

2020-12-10 06:49 UTC, chicduong commented on DataConnectors/Qualys KB/QualysKB_API_FunctionApp.json
> +            "query": "QualysKB\n | | summarize count() by Category"
correction made

2020-12-10 07:18 UTC, v-jayakal approved these changes

2020-12-11 01:54 UTC, nazang approved these changes

2020-12-11 01:55 UTC, merged