onboard Forcepoint Cloud Security Gateway
Azure/Azure-Sentinel pull request #1436
Opened 2020-12-10 10:58 UTC by Dlo-Bagari

Fixes #

## Proposed Changes

  -
  -
  -

2020-12-18 11:26 UTC, v-maudan requested changes

2020-12-18 11:26 UTC, v-maudan commented on DataConnectors/Forcepoint Cloud Security Gateway.json
> +    "sampleQueries": [
Remove one extra space from all sample queries after TimeGenerated.

2020-12-18 11:26 UTC, v-maudan commented on DataConnectors/Forcepoint Cloud Security Gateway.json
> +                        "value": "sudo wget https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/CEF/cef_troubleshoot.py&&sudo python cef_troubleshoot.py  {0}"
-O is missing in the command. Please refer template https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Connector_CEF_template.json

2020-12-18 11:26 UTC, v-maudan commented on DataConnectors/Forcepoint Cloud Security Gateway.json
> +            "description": "This integration requires the Linux Syslog agent to collect your Forcepoint Cloud Security Gateway Web/Email logs as Common Event Format (CEF) and forward them to Azure Se
CEF connector should communicate via some port (514 TCP default).Please refer template https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Connector_CEF_template.json

2020-12-18 11:26 UTC, v-maudan commented on Workbooks/Forcepoint Cloud Secuirty Gateway workbook.json
> +{
workbooksMetadata.json file should have an entry for this workbook. for update please refer this link. https://github.com/Azure/Azure-Sentinel/tree/master/Workbooks

2020-12-18 13:08 UTC, v-maudan commented on Workbooks/Forcepoint Cloud Secuirty Gateway workbook.json
> +        "query": "CommonSecurityLog\n| where TimeGenerated  <= ago(0m)\n| where DeviceVendor == \"Forcepoint CSG\"\n| where DeviceProduct == \"Web\"\n| where LogSeverity == 6\n| where DeviceCustomStr
There should be at least 4 charts / graphs in the workbook.(Currently there are 3 charts/graphs present)

2020-12-21 06:00 UTC, v-maudan commented on DataConnectors/Forcepoint Cloud Security Gateway.json
> +{
Data connector json file should be in the format ProviderNameApplianceName.json . Please remove the space from DataConnector file name.

2020-12-23 08:48 UTC, v-maudan commented on Workbooks/Forcepoint Cloud Secuirty Gateway workbook.json
> +{
No space in file name please.
Rename the workbook file name to ForcepointCloudSecuirtyGatewayworkbook.json

2021-01-08 18:03 UTC, v-jayakal commented
@Dlo-Bagari, Can you please update the PR on comment resolutions? Thanks.

2021-01-11 13:52 UTC, v-maudan commented on Workbooks/Forcepoint Cloud Secuirty Gateway workbook.json
> +{
Need to update the Workbook metadata file WorkbooksMetadata.json to include the new workbook. Please add workbook metadata definition.

2021-01-12 16:10 UTC, v-maudan commented on Workbooks/Forcepoint Cloud Secuirty Gateway workbook.json
> +{
@Dlo-Bagari , Can you please update on this.

2021-01-12 21:56 UTC, v-jayakal requested changes

2021-01-13 13:42 UTC, v-maudan requested changes

2021-01-13 13:42 UTC, v-maudan commented on Workbooks/WorkbooksMetadata.json
> + "dataConnectorsDependencies": [],
Please Update "dataConnectorsDependencies" as  data connector id value in the data connector(s) on which this workbook depends on. like [ "ForcepointCloudSecurityGateway" ]

2021-01-15 04:39 UTC, v-maudan commented
@Dlo-Bagari, Can you resolve the conflicts? Thanks.

2021-01-15 10:31 UTC, v-maudan commented on Workbooks/WorkbooksMetadata.json
> +=======
Please resolve conflicts properly,[Remove duplicate code of line no 1131,1132,1133 and update '**,**' at line no 1130]

2021-01-15 20:12 UTC, v-jayakal commented
@Dlo-Bagari, as part of the comment resolution, in recent commit, few Notebook files are added in the PR and they are resulting in validation issues. Can you please resolve the issues? you have the following options for resolving:
1. Drop notebook related changes, sync your branch with master to have latest and without conflicts.
2. Create a new branch from master and apply only changes related to connector.
Please let us know if you need any info and resolve the conflicts and validations, Thanks.

2021-01-18 04:38 UTC, v-jayakal commented
> @Dlo-Bagari, as part of the comment resolution, in recent commit, few Notebook files are added in the PR and they are resulting in validation issues. Can you please resolve the issues? you have the following options for resolving:
> 
> 1. Drop notebook related changes, sync your branch with master to have latest and without conflicts.
> 2. Create a new branch from master and apply only changes related to connector.
>    Please let us know if you need any info and resolve the conflicts and validations, Thanks.

@Dlo-Bagari - Can you please update the PR? Thanks.

2021-01-19 12:25 UTC, Dlo-Bagari commented
> > @Dlo-Bagari, as part of the comment resolution, in recent commit, few Notebook files are added in the PR and they are resulting in validation issues. Can you please resolve the issues? you have the following options for resolving:
> > 
> > 1. Drop notebook related changes, sync your branch with master to have latest and without conflicts.
> > 2. Create a new branch from master and apply only changes related to connector.
> >    Please let us know if you need any info and resolve the conflicts and validations, Thanks.
> 
> @Dlo-Bagari - Can you please update the PR? Thanks.

@v-jayakal, for Forcepoint Cloud Security Gateway onboarding there was nothing to be added to notebooks.
I have created a new branch with the name: origin/Forcepoint-cloud-security-gateway which contains the latest code.
please let me know if that would solve the conflicts.

2021-01-19 13:32 UTC, v-maudan commented
@Dlo-Bagari , I am unable to see data connector related changes in new branch which you mentioned- origin/Forcepoint-cloud-security-gateway [PFB screenshot], Could you please create new pull request.
![image](https://user-images.githubusercontent.com/75478517/105040692-29e72b80-5a88-11eb-923b-af3862b25dbf.png)

2021-01-19 13:40 UTC, Dlo-Bagari commented
> @Dlo-Bagari , I am unable to see data connector related changes in new branch which you mentioned- origin/Forcepoint-cloud-security-gateway [PFB screenshot], Could you please create new pull request.
> ![image](https://user-images.githubusercontent.com/75478517/105040692-29e72b80-5a88-11eb-923b-af3862b25dbf.png)

I have created a new PR: onboarding Forcepoint cloud security gateway #1604
do I need to close the previous PR which is:  onboard Forcepoint Cloud Security Gateway #1436

2021-01-19 14:17 UTC, v-maudan commented
@Dlo-Bagari , Could you please revert notebook related changes.

2021-01-19 14:52 UTC, Dlo-Bagari commented
> @Dlo-Bagari , Could you please revert notebook related changes.

@v-maudan, for Forcepoint Cloud Security Gateway there were no changes made in notebooks, I am not sure what do I need to revert exactly here. can you give me more explanation about what needs to be done?

2021-01-20 14:24 UTC, v-jayakal commented
@Dlo-Bagari, the 2 PRs raised for Forcepoint has Notebook files included even though there are no changes to those files. Adding them in PR will corrupt the repo. To explain you the issue, a new PR draft has been created with only the changes of Forcepoint, Please check the PR https://github.com/Azure/Azure-Sentinel/pull/1608, when compared, this new PR does not have notebook files. Can you please create a new PR similar to this PR with only changes related to Forcepoint and without Notebook files. 
Let us know the PR once you have it, we can review and approve it, Thanks.
![Forcepoint-Noteboos](https://user-images.githubusercontent.com/73506651/105187863-44d5a080-5b59-11eb-8fed-f8f79239a4c2.PNG)

2021-01-20 14:34 UTC, closed without merging