Couple of simple detections
Azure/Azure-Sentinel pull request #1440
Opened 2020-12-11 00:34 UTC by dicolanl

Fixes #

## Proposed Changes
  - New TI Detection (IP) against App Services HTTP Logs
  - New App Services AV Detections based on new feature (https://azure.github.io/AppService/2020/12/09/AzMon-AppServiceAntiVirusScanLogs.html)

2020-12-11 03:59 UTC, shainw requested changes

2020-12-11 03:59 UTC, shainw commented on Detections/ThreatIntelligenceIndicator/IPEntity_AppServiceHTTPLogs.yaml
> +  on $left.TI_ipEntity == $right.SingleIP
There is no SingleIP from the right side (AppServiceHTTPLogs) so the join fails, this looks like it should be CIp.

2020-12-11 03:59 UTC, shainw commented on Detections/AzureAppServices/AVScan_Infected_Files_Found.yaml
> +  | extend HostCustomEntity = _ResourceId
Please add - extend timestamp = TimeGenerated

2020-12-11 03:59 UTC, shainw commented on Detections/AzureAppServices/AVScan_Failure.yaml
> +  | extend HostCustomEntity = _ResourceId
Please add - extend timestamp = TimeGenerated

2020-12-11 21:10 UTC, dicolanl commented
@shainw  i updated the 3 files per feedback.  Thanks!

2020-12-19 16:53 UTC, shainw approved these changes
There is no issue with this, the validation needs to be fixed, but I am going to wait to complete it until we have a chance to look at the validation.

2021-03-08 18:01 UTC, dicolanl reviewed
fixed

2021-03-08 18:03 UTC, dicolanl commented
/azp run

2021-03-29 20:29 UTC, dicolanl commented
/azp run

2021-04-08 02:20 UTC, shainw approved these changes

2021-04-08 02:20 UTC, merged