New rules and queries for Cisco Umbrella, Cisco ISE and Proofpoint POD
Azure/Azure-Sentinel pull request #1571
Opened 2021-01-12 08:33 UTC by vu-socprime

Added new detection rules and hunting queries for Cisco Umbrella, Cisco ISE and Proofpoint POD

2021-01-15 08:38 UTC, vu-socprime commented
During KqlValidation there is an error "The name 'ProofpointPOD' does not refer to any known table, tabular variable or function". But all queries are based on functions (ProofpointPOD is the name of function) located in "Parsers" directory. Could you please tell if it is possible to pass KqlValidation in this situation?

2021-01-20 07:06 UTC, shainw commented
> During KqlValidation there is an error "The name 'ProofpointPOD' does not refer to any known table, tabular variable or function". But all queries are based on functions (ProofpointPOD is the name of function) located in "Parsers" directory. Could you please tell if it is possible to pass KqlValidation in this situation?

@vu-socprime - You will need to create a CustomTable mapping for these as these connectors are not built into the build system at this point.  Instructions are here - https://github.com/Azure/Azure-Sentinel#pull-request-kql-validation-check - specifically this -

`If you are using custom logs table (a table which is not defined on all workspaces by default) you should verify your table schema is defined in json file in the folder Azure-Sentinel\.script\tests\KqlvalidationsTests\CustomTables`

2021-01-25 16:51 UTC, vu-socprime commented
> > During KqlValidation there is an error "The name 'ProofpointPOD' does not refer to any known table, tabular variable or function". But all queries are based on functions (ProofpointPOD is the name of function) located in "Parsers" directory. Could you please tell if it is possible to pass KqlValidation in this situation?
> 
> @vu-socprime - You will need to create a CustomTable mapping for these as these connectors are not built into the build system at this point. Instructions are here - https://github.com/Azure/Azure-Sentinel#pull-request-kql-validation-check - specifically this -
> 
> `If you are using custom logs table (a table which is not defined on all workspaces by default) you should verify your table schema is defined in json file in the folder Azure-Sentinel\.script\tests\KqlvalidationsTests\CustomTables`

@shainw, json files for custom tables are already in Azure-Sentinel\.script\tests\KqlvalidationsTests\CustomTables. The issue is that we use functions (Azure-Sentinel/Parsers/) instead of tables because we need normalized fields to make queries. What should we do in this situation?

2021-01-27 06:35 UTC, shainw commented
@vu-socprime - You can include it in the CustomTable, but it would be a JSON with the schema of the Parser versus the Table.  At least I believe this should work.  Give it a try and see if it allows passing of the validation.

2021-01-27 10:36 UTC, vu-socprime commented
@shainw - Ok, I will try it. Thank you.

2021-01-31 19:30 UTC, shainw commented
> @shainw - Ok, I will try it. Thank you.

@vu-socprime - I think you did the wrong one.  I see you submitted for Cisco_Umbrella but the KQL validation error is on the ProofPointPOD missing a customtable entry.

2021-02-01 14:49 UTC, vu-socprime commented
> > @shainw - Ok, I will try it. Thank you.
> 
> @vu-socprime - I think you did the wrong one. I see you submitted for Cisco_Umbrella but the KQL validation error is on the ProofPointPOD missing a customtable entry.

@shainw - There were errors regarding Cisco_Umbrella, ProofPointPOD and CiscoISEEvent. I've also added schemas for  ProofPointPOD and CiscoISEEvent in last commit.

2021-02-17 04:56 UTC, shainw requested changes
Looks like referencing the parser in the CustomTable worked.  Additionally, a couple of required changes for Detections with the Entity Mapping.  Also, to support a future improvement we want to include Entity Mapping on Hunting queries also now.  This is not required, but when it does become required we would need you to come back and do it then, so may want to do it now.

2021-02-17 04:56 UTC, shainw commented on Detections/ProofpointPOD/ProofpointPODHighRiskNotDiscarded.yaml
> +  | project SrcUserUpn, DstUserUpn
Missing the Entity Mapping section on this one.

2021-02-17 04:56 UTC, shainw commented on Detections/ProofpointPOD/ProofpointPODWeakCiphers.yaml
> +  | where TlsCipher in (tls_ciphers)
Missing the Entity Mapping section

2021-02-18 00:03 UTC, shainw approved these changes

2021-02-18 00:04 UTC, merged