Added isPreview flag
Azure/Azure-Sentinel pull request #1572
Opened 2021-01-12 12:11 UTC by v-maudan

Fixes #

## Proposed Changes

  -Added isPreview flag

2021-01-15 22:28 UTC, nazang commented on DataConnectors/Templates/Connector_REST_API_AzureFunctionApp_template/DataConnector_API_AzureFunctionApp_template.json
> +	"isPreview": true
Please fix the alignment.

2021-03-11 00:51 UTC, preetikr approved these changes

2021-03-11 00:54 UTC, preetikr requested changes
Need to check whether status should be 1 or 2 - @v-jayakal - please confirm and accordingly close the PR. Thanks.

2021-03-11 04:57 UTC, closed without merging

2021-03-11 04:57 UTC, v-jayakal commented
Updated in other PR