QualysVM Gov Changes
Azure/Azure-Sentinel pull request #1747
Opened 2021-02-10 10:22 UTC by v-ampami

Fixes #
QualysVM Gov Changes
## Proposed Changes

  -
  -
  -

2021-02-26 10:26 UTC, v-jayakal requested changes

2021-02-26 10:26 UTC, v-jayakal commented on DataConnectors/Qualys VM/QualysVM_API_FunctionApp.json
> +            "description": "Use this method for automated deployment of the Qualys VM connector using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below. \n\n\t[![Deploy To Azure](https
This has to be added in Manual step, please remove here and add in manual. In manual parameter count should also be changed to 8 from 7.

2021-03-02 06:30 UTC, v-jayakal requested changes

2021-03-02 06:30 UTC, v-jayakal commented on DataConnectors/Qualys VM/QualysVM_API_FunctionApp.json
> +            "description": "Use this method for automated deployment of the Qualys VM connector using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below. \n\n\t[![Deploy To Azure](https
Please add the 'and' removed here. No change in this line.

2021-03-03 01:01 UTC, nazang approved these changes

2021-03-03 05:11 UTC, merged