Expansions based on MDE Unsigned file and screenshot taken
Azure/Azure-Sentinel pull request #1766
Opened 2021-02-14 11:56 UTC by YaronFruchtmann

Fixes #

## Proposed Changes

  -
  -
  -

2021-02-19 06:55 UTC, shainw requested changes

2021-02-19 06:55 UTC, shainw commented on Exploration Queries/InputEntity_Host/ProcessBlockedNonMS.yaml
> +  | summarize Count=count() by Process_ProcessId=InitiatingProcessId, Process_CommandLine=InitiatingProcessCommandLine, Process_CreationTimeUtc=InitiatingProcessCreationTime, Process_Host_Unstructure
DeviceEvents does not have a column named InitiatingProcessCreationTime

2021-02-21 07:44 UTC, YaronFruchtmann commented on Exploration Queries/InputEntity_Host/ProcessBlockedNonMS.yaml
> +  | summarize Count=count() by Process_ProcessId=InitiatingProcessId, Process_CommandLine=InitiatingProcessCommandLine, Process_CreationTimeUtc=InitiatingProcessCreationTime, Process_Host_Unstructure
Wow! Glad you caught that. Removing this for now and taking a task to understand why this is missing

2021-02-21 18:51 UTC, YaronFruchtmann commented on Exploration Queries/InputEntity_Host/ProcessBlockedNonMS.yaml
> +  | summarize Count=count() by Process_ProcessId=InitiatingProcessId, Process_CommandLine=InitiatingProcessCommandLine, Process_CreationTimeUtc=InitiatingProcessCreationTime, Process_Host_Unstructure
This coulmn is missing on the connector side. This will be fixed soon, and I will reintroduce the field mapping

2021-02-24 05:48 UTC, shainw approved these changes

2021-02-24 05:49 UTC, merged