Oracle DB Audit Data Connector
Azure/Azure-Sentinel pull request #1800
Opened 2021-02-19 17:05 UTC by vu-socprime

## Proposed Changes
  - Add Oracle DB Audit Data Connector
  - Add Oracle DB Audit Workbook

2021-02-26 03:59 UTC, v-jayakal commented
@vu-socprime , Please modify the "fromTemplateId" of workbook to refer Oracle DB instead of generic "sentinel-UserWorkbook", you can check other workbooks for reference.

2021-02-26 04:31 UTC, v-jayakal commented
@vu-socprime, There is an additional parentheses in the text for Parser, Can you please remove?
Text:  This data connector depends on a parser based on Kusto Function **OracleDatabaseAuditEvent** to work as expected.  [Follow steps to get this Kusto Function]((https://aka.ms/sentinel-OracleDatabaseAudit-parser)"
See the parentheses before https: here.

2021-02-26 04:31 UTC, v-jayakal requested changes

2021-02-26 04:31 UTC, v-jayakal commented on DataConnectors/OracleDatabaseAudit/Connector_OracleDatabaseAudit.json
> +            "legend": "Oracle Database Audit Events",
Legend value should be OracleDatabaseAudit

2021-02-26 13:54 UTC, vu-socprime commented
> @vu-socprime , Please modify the "fromTemplateId" of workbook to refer Oracle DB instead of generic "sentinel-UserWorkbook", you can check other workbooks for reference.

done

2021-02-26 13:55 UTC, vu-socprime commented
> @vu-socprime, There is an additional parentheses in the text for Parser, Can you please remove?
> Text: This data connector depends on a parser based on Kusto Function **OracleDatabaseAuditEvent** to work as expected. [Follow steps to get this Kusto Function]((https://aka.ms/sentinel-OracleDatabaseAudit-parser)"
> See the parentheses before https: here.

done

2021-03-02 03:03 UTC, v-jayakal requested changes

2021-03-02 03:03 UTC, v-jayakal commented on DataConnectors/OracleDatabaseAudit/Connector_OracleDatabaseAudit.json
> +            "legend": "Syslog(OracleDatabaseAudit)",
Please remove Syslog, "legend": "OracleDatabaseAudit" is the value expected.

2021-03-02 03:03 UTC, v-jayakal commented on DataConnectors/OracleDatabaseAudit/Connector_OracleDatabaseAudit.json
> +            "name": "Syslog(OracleDatabaseAudit)",
Please keep the space next to Syslog, There should not be any space within "OracleDatabaseAudit.

2021-03-02 23:20 UTC, v-jayakal requested changes
@vu-socprime ,Please resolve merge confilcts of Workbook metadata file, Thanks.

2021-03-05 01:02 UTC, v-jayakal commented
@vu-socprime ,Please resolve merge conflicts of Workbook metadata file, Thanks.

2021-03-05 08:38 UTC, vu-socprime commented
> @vu-socprime ,Please resolve merge conflicts of Workbook metadata file, Thanks.

@v-jayakal , resolved

2021-03-05 19:04 UTC, v-jayakal approved these changes

2021-03-05 19:04 UTC, merged