Create KVPairExtraction
Azure/Azure-Sentinel pull request #1867
Opened 2021-03-04 11:33 UTC by CyberSekure

Extracts key value pairs such as the below and then stores them as separate fields. Tweak the regex in the extend for your log source if required. Tested on Cisco ISE logs
DestinationIPAddress=10.0.0.1, UserName=Test, AcsSessionID=SomeSession

Fixes #

## Proposed Changes

  -
  -
  -

2021-03-04 13:33 UTC, CyberSekure commented
Just noticed that some fields were being extracted with a hyphen and KQL doesn't seem to like these. I've added a replace command to remove hyphens

2021-03-18 03:13 UTC, shainw requested changes

2021-03-18 03:13 UTC, shainw commented on Parsers/KVPairExtraction
> +| extend kvpairs=parse_json(extract_all("([^\\d\\s]+)=(\\S+),\\s", dynamic([1,2]), SyslogMessage))
Please follow the parser format identified here - https://github.com/Azure/Azure-Sentinel/wiki/Contribute-to-Sentinel-GitHub-Community-of-Queries#example-parser

2021-03-25 04:40 UTC, shainw approved these changes

2021-03-25 04:40 UTC, merged