Cisco firepower e streamer cef
Azure/Azure-Sentinel pull request #1923
Opened 2021-03-12 19:10 UTC by skhademcis

Fixes #

## Proposed Changes

  -  Updated Description and Application name in the MD

2021-03-16 01:12 UTC, v-jayakal commented
@skhademcis, Can you provide changes to the existing files in the Sentinel Repo to track the changes and the best way to identify and modify the changes needed. 
Please use https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/CiscoFirepower/CiscoFirepowerEStreamerCollector.json to modify the connector changes. 
Thanks.

2021-03-16 01:15 UTC, v-jayakal commented
@skhademcis, Please resolve conflicts and make changes to the existing files in the repo for modifications.

2021-03-31 23:56 UTC, v-jayakal commented
Hey @skhademcis , Please make changes to the existing files instead of adding them resulting in conflicts. Can you please modify the files? Let us know if you need more information. Thanks.

2021-04-27 06:58 UTC, v-admahe requested changes

2021-04-27 06:58 UTC, v-admahe commented on DataConnectors/CiscoFirepower/CiscoFirepowerEStreamerCollector.json
> +        "status": 1
isPreview tag is missing. Please add the isPreview tag.

Thanks,
Aditi Maheshwari

2021-04-27 06:58 UTC, v-admahe commented on DataConnectors/CiscoFirepower/CiscoFirepowerEStreamerCollector.json
> +                                "value": "sudo wget https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/CEF/cef_installer.py&&sudo python cef_installer.py {0} {1}"
-O cef_installer.py is missing. Please refer the sample template https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Connector_CEF_template.json

Thanks,
Aditi Maheshwari

2021-04-27 06:58 UTC, v-admahe commented on DataConnectors/CiscoFirepower/CiscoFirepowerEStreamerCollector.json
> +                        "value": "sudo wget https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/CEF/cef_troubleshoot.py&&sudo python cef_troubleshoot.py  {0}"
-O cef_troubleshoot.py is missing. Please refer the sample template https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Connector_CEF_template.json

Thanks,
Aditi Maheshwari

2021-04-27 06:58 UTC, v-admahe commented on Logos/cisco-logo-72px.svg
> +<svg width="72px" height="72px" viewBox="0 0 72 72">
Please add xmlns="http://www.w3.org/2000/svg" in svg tag.

Thanks,
Aditi Maheshwari

2021-05-01 04:37 UTC, v-jayakal approved these changes

2021-05-01 04:37 UTC, merged