Check Point - Playbook and Custom Connector
Azure/Azure-Sentinel pull request #2052
Opened 2021-04-01 00:25 UTC by chkp-jguo

Fixes #

## Proposed Changes

  - Add Check Point logo to logo directory
  - Add Check Point / Playbook folder to Solutions directory
  - Add Check Point / Playbook folder which contains Check Point custom connector and playbook

2021-04-01 02:58 UTC, sarah-yo commented on Solutions/Check Point/Playbooks/README.md
> +[Logic App Overview](https://azure.microsoft.com/en-us/services/logic-apps/)
Remove localisation "en-us" from URL

2021-04-01 02:59 UTC, sarah-yo requested changes
Hello, please can you do the following:

-  remove any localisation from your URLs (I have marked one example but please check your whole readme)
- Add a "Deploy to Azure Gov button and ARM template
- Update your "Deploy to Azure button image with the most recent version as can be seen on other readmes in this repo

Thanks!

2021-04-02 20:52 UTC, chkp-jguo commented on Solutions/Check Point/Playbooks/README.md
> +[Logic App Overview](https://azure.microsoft.com/en-us/services/logic-apps/)
Removed localization - per https://github.com/Azure/Azure-Sentinel/pull/2052/commits/2b05dc45e52c19bc1a42eeaea62226fafa221843

2021-04-02 20:57 UTC, chkp-jguo commented
> Hello, please can you do the following:
> 
> * remove any localisation from your URLs (I have marked one example but please check your whole readme)
> * Add a "Deploy to Azure Gov button and ARM template
> * Update your "Deploy to Azure button image with the most recent version as can be seen on other readmes in this repo
> 
> Thanks!

1. Removed localization in readme
2. Added deploy to azure gov and arm template
3. Updated deploy to azure button image

2021-04-26 20:31 UTC, closed without merging

2021-04-26 20:32 UTC, chkp-jguo commented
will submit a new one.