Update WatchGuardFirebox.txt
Azure/Azure-Sentinel pull request #2054
Opened 2021-04-01 02:47 UTC by ecosystempo

Try to update

WatchGuard syslog Parser

2021-04-06 11:14 UTC, v-admahe requested changes

2021-04-06 11:14 UTC, v-admahe commented on Parsers/WatchGuardFirebox.txt
> +Message = extract("msg=\"(.*?)\"",1,SyslogMessage),
Should it not be 'EventMessage'? Please refer https://docs.microsoft.com/en-us/azure/sentinel/normalization-schema for field names.

Thanks,
Aditi Maheshwari

2021-04-06 11:14 UTC, v-admahe commented on Parsers/WatchGuardFirebox.txt
> +SourceIP = fromat_result(extract_all(@"(:\s(?P<srcIp1>(\d{1,3}\.){3}\d{1,3}):\d{1,5}\s->\s)|(\s(?P<srcIp2>(\d{1,3}\.){3}\d{1,3})\s(\d{1,3}\.){3}\d{1,3}\s)", dynamic(['srcIp1', 'srcIp2']), SyslogMessa
Should it not be 'SrcIpAddr'? Please refer https://docs.microsoft.com/en-us/azure/sentinel/normalization-schema for field names.

Thanks,
Aditi Maheshwari

2021-04-06 11:14 UTC, v-admahe commented on Parsers/WatchGuardFirebox.txt
> +DestinationIP = fromat_result(extract_all(@"(:\d{1,5}\s->\s(?P<destIp1>(\d{1,3}\.){3}\d{1,3}):\d{1,5}\s)|(\s(\d{1,3}\.){3}\d{1,3}\s(?P<destIp2>(\d{1,3}\.){3}\d{1,3})\s)", dynamic(['destIp1', 'destIp2
Should it not be 'DstIpAddr'? Please refer https://docs.microsoft.com/en-us/azure/sentinel/normalization-schema for field names.

Thanks,
Aditi Maheshwari

2021-04-06 11:14 UTC, v-admahe commented on Parsers/WatchGuardFirebox.txt
> +SourcePort = fromat_result(extract_all(@"(:\s(\d{1,3}\.){3}\d{1,3}:(?P<srcPort1>\d{1,5})\s->\s)|(\s(\d{1,3}\.){3}\d{1,3}\s(\d{1,3}\.){3}\d{1,3}\s(?P<srcPort2>\d{1,5})\s)", dynamic(['srcPort1', 'srcPo
Should it not be 'SrcPortNumber'? Please refer https://docs.microsoft.com/en-us/azure/sentinel/normalization-schema for field names.

Thanks,
Aditi Maheshwari

2021-04-06 11:14 UTC, v-admahe commented on Parsers/WatchGuardFirebox.txt
> +DestinationPort = fromat_result(extract_all(@"(:\d{1,5}\s->\s(\d{1,3}\.){3}\d{1,3}:(?P<destPort1>\d{1,5})\s)|(\s(\d{1,3}\.){3}\d{1,3}\s(\d{1,3}\.){3}\d{1,3}\s\d{1,5}\s(?P<destPort2>\d{1,5})\s)", dyna
Should it not be 'DstPortNumber'? Please refer https://docs.microsoft.com/en-us/azure/sentinel/normalization-schema for field names.

Thanks,
Aditi Maheshwari

2021-04-07 02:26 UTC, ecosystempo commented
Modify done for the change request 

![image](https://user-images.githubusercontent.com/37067255/113801560-a934f300-978b-11eb-955e-b57bf408698a.png)

2021-04-09 05:46 UTC, v-jayakal approved these changes

2021-04-09 05:51 UTC, merged