Update Connector_syslog_WatchGuardFirebox.json
Azure/Azure-Sentinel pull request #2055
Opened 2021-04-01 03:07 UTC by ecosystempo

Update Connector_syslog_WatchGuardFirebox.json

  -
  -
  -

2021-04-08 10:53 UTC, v-admahe requested changes

2021-04-08 11:02 UTC, v-admahe commented
@ecosystempo Legend name should be datatype name. Please update the legend name to WatchGuard Firebox.

Thanks,
Aditi Maheshwari

2021-04-09 02:29 UTC, ecosystempo commented
Modify "id" and "legend" 
![image](https://user-images.githubusercontent.com/37067255/114120073-68b9ae80-991e-11eb-9a4e-d33750b7866b.png)

2021-04-09 05:45 UTC, v-jayakal approved these changes

2021-04-09 05:52 UTC, merged