Add Palo Alto High Risk Port hunting query
Azure/Azure-Sentinel pull request #2180
Opened 2021-04-21 15:53 UTC by mmaitre314

Add a hunting query listing communications on dangerous ports which were not blocked by Palo Alto firewalls and need to be reviewed to ensure sufficient network isolation.

2021-04-27 06:44 UTC, v-jayakal submitted a review, later dismissed

2021-04-27 06:45 UTC, v-jayakal commented
@shainw , metadata looks good, approved.

2021-05-03 17:13 UTC, shainw requested changes
I would suggest swapping the left and right sides of the join here.  The HighRiskPorts is a much smaller data set and when comparing with very large CommonSecurityLog the performance is not great in its current format.  Based on testing in large data sets, swapping the sides of the join cuts the query time by 50% and the total CPU time used by 33% for a 24 hour period, even more when expanding to 3 and 7 days.

2021-05-06 17:54 UTC, shainw approved these changes

2021-05-06 17:54 UTC, merged