Add ESET PROTECT connector
Azure/Azure-Sentinel pull request #2242
Opened 2021-05-04 11:54 UTC by dmaasland

Hello,

This PR adds a Syslog connector for the new ESET PROTECT platform, but is also backwards compatible with the old ESET Security Management Center (as available here: https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/esetSmc.json). 

The difference is that this connector requires no configuration file editing and could replace the old one completely. If at all possible I would like to draw some extra attention to the field mappings as we are not sure all fields are correctly mapped.

2021-05-10 10:34 UTC, v-admahe requested changes

2021-05-10 10:34 UTC, v-admahe commented on Parsers/ESETPROTECT/ESETPROTECT.txt
> +        UserDomain = iff(Message['username'] contains '\\', split(Message['username'], '\\')[0], ''),
It should be either DstUserDomain or SrcUserDomain.

Thanks,
Aditi Maheshwari

2021-05-17 12:40 UTC, dmaasland commented
Updated all but one, please check my comment there and let me know how to proceed :)

2021-05-17 23:09 UTC, elforb commented on Workbooks/WorkbooksMetadata.json
> +  {
This metadata addition should be removed, metadata changes are not necessary for solutions.

2021-05-17 23:10 UTC, elforb commented on DataConnectors/ESETPROTECT/Connector_Syslog_ESETPROTECT.json
> +    "descriptionMarkdown": "Syslog is an event logging protocol that is common to Linux. Applications will send messages that may be stored on the local machine or delivered to a Syslog collector. Wh
descriptionMarkdown should meaningful explanation of what data the data connector enables bringing in, in what format and pointer to appliance documentation as applies.

2021-05-17 23:11 UTC, elforb commented on DataConnectors/ESETPROTECT/Connector_Syslog_ESETPROTECT.json
> +    "publisher": "ESET Netherlands",
This Provider name is not used throughout. Should be changed to `ESET` to reflect that which is used all around.

2021-05-17 23:11 UTC, elforb commented on DataConnectors/ESETPROTECT/Connector_Syslog_ESETPROTECT.json
> +            "description" : "Query Eset threat events from On-demand scanner",
Should "Eset" be fully capitalized here?

2021-05-17 23:12 UTC, elforb commented on DataConnectors/ESETPROTECT/Connector_Syslog_ESETPROTECT.json
> +}
Please add a Metadata object within this file. See https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/Templates/Connector_REST_API_template.json for further detail.

2021-05-17 23:15 UTC, elforb commented on Workbooks/ESETPROTECT.json
> +          "json": "## ESET PROTECT"
Should include note about parser, which is included in solution. See https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Box/Workbooks/Box.json#L7 for example.

2021-05-17 23:19 UTC, elforb commented
Please also move these added files to a new folder under the solutions folder, `/Solutions/ESETProtect`.

For example of desired folder structure see: https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Box

2021-05-20 18:12 UTC, elforb requested changes

2021-05-20 18:12 UTC, elforb commented on DataConnectors/ESETPROTECT/Connector_Syslog_ESETPROTECT.json
> +{
Please also move these added files to a new folder under the solutions folder, /Solutions/ESETProtect.

For example of desired solution folder structure see: https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Box

2021-05-24 09:16 UTC, dmaasland commented
Hello,

I think this should fix all of your comments. Please check

2021-05-25 11:28 UTC, v-maudan requested changes
@dmaasland , To pass pull request kql validation, can you please add CustomTable JSON schema with Parser name(ESETPROTECT.json) [here](https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables). Please refer this link for reference : [Sample Parser custom table schema (Cloudflare.json)](https://github.com/Azure/Azure-Sentinel/pull/2019/files#diff-7c3e14c3f2fad6ef6dd861033735a4f0e1360ed19adf1e86d92401071dcbc879) Thanks!.

2021-05-25 11:28 UTC, v-maudan commented on Solutions/ESETPROTECT/Analytic Rules/ESETThreatDetected.yaml
> +        columnName: FileHashCustomEntity
@dmaasland, Please add field **Version** in Analytic rule file as mentioned below
"version: 1.0.0"
refer this link for reference. [Sample PR link](https://github.com/Azure/Azure-Sentinel/pull/2271)

2021-05-25 11:28 UTC, v-maudan commented on Solutions/ESETPROTECT/Analytic Rules/ESETWebsiteBlocked.yaml
> +        columnName: URLCustomEntity
@dmaasland, Please add field **Version** in Analytic rule file as mentioned below
"version: 1.0.0"
refer this link for reference. [Sample PR link](https://github.com/Azure/Azure-Sentinel/pull/2271)

2021-05-25 11:28 UTC, v-maudan commented on Solutions/ESETPROTECT/Workbooks/ESETPROTECT.json
> +          "query": "ESETPROTECT\r\n| where TimeGenerated {TimeRange}\r\n| where EventType == 'Threat_Event'\r\n| summarize events_count = count() by tostring(UserName)",
As per latest changes in parser please update SrcUserName  instead of UserName.

2021-05-25 11:28 UTC, v-maudan commented on Solutions/ESETPROTECT/Workbooks/ESETPROTECT.json
> +          "query": "ESETPROTECT\r\n| where TimeGenerated {TimeRange}\r\n| where EventType == \"Threat_Event\"\r\n| project TimeGenerated, HostName, UserName, ThreatCategory, ThreatName, ProcessFilePa
As per latest changes in parser please update SrcUserName instead of UserName.

2021-05-25 12:09 UTC, dmaasland commented
Done!

2021-05-25 13:23 UTC, v-maudan commented on Solutions/ESETPROTECT/Analytic Rules/ESETThreatDetected.yaml
> +query: |
Relevant Technique field is missing, can you please update the same and [refer this link ](https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide)for details.

2021-05-25 13:23 UTC, v-maudan commented on Solutions/ESETPROTECT/Analytic Rules/ESETWebsiteBlocked.yaml
> +query: |
Relevant Technique field is missing, can you please update the same and [refer this link ](https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide)for details.

2021-05-25 13:25 UTC, v-maudan commented
> Done!

@dmaasland Thanks for update. Please add Relevant Technique field in Analytics rule files. Thanks!.

2021-05-25 14:17 UTC, dmaasland commented
Also done!

2021-05-26 04:38 UTC, v-maudan requested changes

2021-05-26 04:38 UTC, v-maudan commented on Solutions/ESETPROTECT/Analytic Rules/ESETThreatDetected.yaml
> +      - Syslog
If the detection query operates on Parser ,dataTypes should be the Parser name and not the table name. [Please refer this ](https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide#datatypes)for more details :

2021-05-26 04:38 UTC, v-maudan commented on Solutions/ESETPROTECT/Analytic Rules/ESETWebsiteBlocked.yaml
> +      - Syslog
If the detection query operates on Parser ,dataTypes should be the Parser name and not the table name. [Please refer this ](https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide#datatypes)for more details :

2021-05-26 08:19 UTC, dmaasland commented
done and done

2021-05-26 10:42 UTC, v-maudan approved these changes

2021-05-26 19:34 UTC, v-jayakal approved these changes

2021-05-26 19:35 UTC, merged