Proofpoint TAP Playbooks
Azure/Azure-Sentinel pull request #2427
Opened 2021-06-08 08:00 UTC by vu-socprime

## Proposed Changes
  - Add Proofpoint TAP Custom Logic App Connector and Playbooks

2021-06-13 23:47 UTC, sarah-yo requested changes
- Please check spelling, grammar and correct capitalization in all readme files.
- Please expand the instructions for "b. Configurations in Sentinel" in each readme

2021-06-14 17:52 UTC, lior-tamir commented
I have sent feedback over email to the contributors

2021-06-15 08:56 UTC, v-admahe requested changes

2021-06-15 08:56 UTC, v-admahe commented on Playbooks/ProofpointTAP/Playbooks/ProofpointTAP-AddForensicsInfoToIncident/azuredeploy.json
> +    "contentVersion": "1.0.0.0",
Metadata parameters is missing.

Thanks,
Aditi Maheshwari

2021-06-15 08:56 UTC, v-admahe commented on Playbooks/ProofpointTAP/Playbooks/ProofpointTAP-AddInfoToIncident/azuredeploy.json
> +    "contentVersion": "1.0.0.0",
Metadata parameters is missing.

Thanks,
Aditi Maheshwari

2021-06-15 08:56 UTC, v-admahe commented on Playbooks/ProofpointTAP/ProofpointTAPConnector/azuredeploy.json
> +    "contentVersion": "1.0.0.0",
Metadata parameters is missing.

Thanks,
Aditi Maheshwari

2021-06-15 08:56 UTC, v-admahe commented on Playbooks/ProofpointTAP/azuredeploy.json
> +    "contentVersion": "1.0.0.0",
Metadata parameters is missing.

Thanks,
Aditi Maheshwari

2021-06-21 21:10 UTC, v-jayakal commented
@vu-socprime , @sarah-yo , @lior-tamir & @sreedharande - As we already have a solution for Proofpoint TAP, these playbooks will be packaged as part of the solution. As part of that, these files will be moved to solution folder once this is approved. Thanks.

2021-06-23 14:43 UTC, vu-socprime commented
> I have sent feedback over email to the contributors

@lior-tamir Thanks! Playbooks have been updated according to the email.

2021-06-24 03:18 UTC, sarah-yo commented on Playbooks/ProofpointTAP/Playbooks/ProofpointTAP-CheckAccountInVAP/readme.md
> +1. In Azure sentinel analytical rules should be configured to trigger an incident with risky user account. In the *Entity maping* section of the analytics rule creation workflow, user's email should
remove "en-us" from URL

2021-06-24 03:18 UTC, sarah-yo commented on Playbooks/ProofpointTAP/Playbooks/ProofpointTAP-AddForensicsInfoToIncident/readme.md
> +1. In Azure sentinel analytical rules should be configured to trigger an incident. An incident should have *campaignId* custom entity (obtained from *campaignId_s* field in ProofpointTAP logs). Check
remove "en-us" from URL

2021-06-24 03:19 UTC, sarah-yo requested changes
Please remove "en-us" from URLs as marked in the readmes

2021-07-01 13:58 UTC, vu-socprime commented on Playbooks/ProofpointTAP/Playbooks/ProofpointTAP-CheckAccountInVAP/readme.md
> +1. In Azure sentinel analytical rules should be configured to trigger an incident with risky user account. In the *Entity maping* section of the analytics rule creation workflow, user's email should
updated

2021-07-01 13:58 UTC, vu-socprime commented on Playbooks/ProofpointTAP/Playbooks/ProofpointTAP-AddForensicsInfoToIncident/readme.md
> +1. In Azure sentinel analytical rules should be configured to trigger an incident. An incident should have *campaignId* custom entity (obtained from *campaignId_s* field in ProofpointTAP logs). Check
updated

2021-07-08 09:42 UTC, vu-socprime commented
> * Please check spelling, grammar and correct capitalization in all readme files.
> * Please expand the instructions for "b. Configurations in Sentinel" in each readme

@sarah-yo Done

2021-07-08 23:08 UTC, v-jayakal commented
@vu-socprime , can you please move these files into solutions folder of Cisco Umbrella? Path for the Cisco Umbrella solution is https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CiscoUmbrella. Please add a folder called Playbooks and move these files. You can refer other solutions with playbooks (ex: Cisco ISE) for reference.

2021-07-15 05:12 UTC, v-jayakal commented
@sarah-yo , @lior-tamir - Can you please approve the PR? thanks.

2021-07-20 21:26 UTC, v-jayakal commented
@vu-socprime , Can you please move these files into Proofpoint TAP solution folder? Thanks.

2021-07-29 19:43 UTC, v-jayakal approved these changes

2021-07-29 19:44 UTC, merged