InsightVMCloud: data_connector,parsers,datasamples
Azure/Azure-Sentinel pull request #2507
Opened 2021-06-17 12:10 UTC by averbn

## Proposed Changes

  - new connector

2021-06-22 13:08 UTC, v-maudan requested changes

2021-06-23 07:29 UTC, averbn commented on .script/tests/KqlvalidationsTests/CustomTables/NexposeInsightVMCloud_assets_CL
> +{
fixed

2021-06-23 07:29 UTC, averbn commented on .script/tests/KqlvalidationsTests/CustomTables/NexposeInsightVMCloud_vulnerabilities_CL
> +{
fixed

2021-06-23 07:30 UTC, averbn commented on Solutions/Rapid7InsightVM/Parsers/InsightVMAssets
> +// Usage Instruction :
fixed

2021-06-23 07:30 UTC, averbn commented on Solutions/Rapid7InsightVM/Parsers/InsightVMVulnerabilities
> +// Usage Instruction :
fixed

2021-06-23 07:30 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +	"descriptionMarkdown":"The [Rapid7 Insight VM](https://www.rapid7.com/products/insightvm/) Report data connector provides the capability to ingest Scan reports and vulnerability data into Azure Sent
fixed

2021-06-23 07:30 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"**1. Deploy a Function App**\n\n> **NOTE:** You will need to [prepare VS code](https://docs.microsoft.com/azure/azure-functions/functions-create-first-function-python#prerequisites
fixed

2021-06-23 07:30 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/azuredeploy_Connector_InsightVMCloudAPI_AzureFunction.json
> +                        "WEBSITE_RUN_FROM_PACKAGE": "https://github.com/averbn/azure_sentinel_data_connectors/raw/main/insight-vm-cloud-azure-sentinel-data-connector/InsightVMCloudAPISentinelConn.zip
fixed

2021-06-23 07:30 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"Use the following step-by-step instructions to deploy the Rapid7 Insight Vulnerability Management Repor data connector manually with Azure Functions (Deployment via Visual Studio C
fixed

2021-06-23 07:30 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"**2. Configure the Function App**\n\n1. In the Function App, select the Function App Name and select **Configuration**.\n2. In the **Application settings** tab, select ** New appli
fixed

2021-06-23 07:30 UTC, averbn commented on Solutions/Rapid7InsightVM/Parsers/InsightVMAssets
> +                    "DvcMacAddr", mac_s
fixed

2021-06-23 10:08 UTC, v-maudan commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"**2. Configure the Function App**\n\n1. In the Function App, select the Function App Name and select **Configuration**.\n2. In the **Application settings** tab, select ** New appli
@averbn , Can you please update instruction for logAnalyticsUri (optional). Thanks!

2021-06-23 10:12 UTC, v-maudan commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"**1. Deploy a Function App**\n\n> **NOTE:** You will need to [prepare VS code](https://docs.microsoft.com/azure/azure-functions/functions-create-first-function-python#prerequisites
@averbn , It seems short url link for Azure Function App not yet updated.

2021-06-23 10:14 UTC, v-maudan commented
@averbn , Can you please fix all PR review comments. Thanks!

2021-06-25 06:51 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"**2. Configure the Function App**\n\n1. In the Function App, select the Function App Name and select **Configuration**.\n2. In the **Application settings** tab, select ** New appli
done

2021-06-25 07:52 UTC, v-maudan commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +	"additionalRequirementBanner":"These queries and workbooks are dependent on a parser based on Kusto to work as expected. ​Follow the steps to use this Kusto functions aliases [InsightVMAssets](https
@averbn ,Please update additionalRequirementBanner value. Thanks!

2021-06-25 07:54 UTC, v-maudan commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":">**NOTE:** This data connector depends on a parser based on a Kusto Function to work as expected. Follow the steps to create the Kusto functions aliases: [InsightVMAssets](https://
@averbn, can you please update parser description? Thanks!

2021-06-25 08:07 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"**1. Deploy a Function App**\n\n> **NOTE:** You will need to [prepare VS code](https://docs.microsoft.com/azure/azure-functions/functions-create-first-function-python#prerequisites
Already fixed, pls check the "InsightVM: connector json fix"  commit.

2021-06-25 09:00 UTC, v-maudan commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"Use this method for automated deployment of the Rapid7 Insight Vulnerability Management Report data connector using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below
@averbn , Replace value https://aka.ms/sentinelinsightvmcloudazuredeploy with  https://aka.ms/sentinel-InsightVMCloudAPI-azuredeploy short url link for azure deploy .

2021-06-25 09:05 UTC, v-maudan commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"**1. Deploy a Function App**\n\n> **NOTE:** You will need to [prepare VS code](https://docs.microsoft.com/azure/azure-functions/functions-create-first-function-python#prerequisites
Update short url as per given format : https://aka.ms/sentinel-InsightVMCloudAPI-functionapp.

2021-06-25 09:21 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"**1. Deploy a Function App**\n\n> **NOTE:** You will need to [prepare VS code](https://docs.microsoft.com/azure/azure-functions/functions-create-first-function-python#prerequisites
done

2021-06-28 05:23 UTC, v-maudan commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":">**NOTE:** This data connector depends on a parser based on a Kusto Function to work as expected. Follow the steps to create the Kusto functions aliases: [InsightVMAssets](https://
@averbn , Can you please update on this .

2021-06-28 05:23 UTC, v-maudan commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"Use this method for automated deployment of the Rapid7 Insight Vulnerability Management Report data connector using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below
@averbn , Can you please update on this .

2021-06-29 07:31 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":"Use this method for automated deployment of the Rapid7 Insight Vulnerability Management Report data connector using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below
done

2021-06-29 08:55 UTC, v-maudan commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":">**NOTE:** This data connector depends on a parser based on a Kusto Function to work as expected. Follow the steps to create the Kusto functions aliases: [InsightVMAssets](https://
@averbn , I am not able to see parser instruction description updated, can you please update as mentioned.

2021-06-29 11:07 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloud_API_FunctionApp.json
> +		  "description":">**NOTE:** This data connector depends on a parser based on a Kusto Function to work as expected. Follow the steps to create the Kusto functions aliases: [InsightVMAssets](https://
done

2021-06-29 11:28 UTC, v-maudan approved these changes

2021-07-01 05:27 UTC, v-jayakal approved these changes

2021-07-01 05:28 UTC, merged