CiscoACI Data Connector
Azure/Azure-Sentinel pull request #2511
Opened 2021-06-17 13:25 UTC by vu-socprime

## Proposed Changes

  - add CiscoACI Data Connector

2021-06-22 05:18 UTC, v-admahe requested changes

2021-06-22 05:22 UTC, v-admahe commented
@oshezaf Can you please review the Parser? 

Thanks
Aditi Maheshwari

2021-06-22 08:12 UTC, vu-socprime commented on Solutions/CiscoACI/Data Connectors/CiscoACI_Syslog.json
> +            "query": "CiscoACIEvent\n | where notempty(SrcIpAddr)\n | summarize count() by SrcIpAddr\n | top 10 by count_"
fixed

2021-06-28 06:27 UTC, v-jayakal approved these changes

2021-06-28 06:27 UTC, merged