update Group IB TIA playbooks for solutions package + logo + sample data
Azure/Azure-Sentinel pull request #2540
Opened 2021-06-22 09:58 UTC by ivanovchinnikov

Fixes #

## Proposed Changes

  - Logo file added
  - Sample data added
  - Playbooks updated to the latest version

2021-06-22 21:54 UTC, v-jayakal commented
@sarah-yo - Can you please review the PR? Thanks.

2021-06-23 03:07 UTC, sarah-yo commented
Assigning @preetikr as it's solutions

2021-06-24 03:22 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_APT_ThreatActor.json
> +                    "connectionId": "/subscriptions/6a021fde-5198-441e-9190-9d634e1f4a84/resourceGroups/Group-IB-WS/providers/Microsoft.Web/connections/azureloganalyticsdatacollector-2",
hardcoded subscription ID

2021-06-24 03:22 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_APT_ThreatActor.json
> +                    "connectionId": "/subscriptions/6a021fde-5198-441e-9190-9d634e1f4a84/resourceGroups/Group-IB-WS/providers/Microsoft.Web/connections/azuresentinel-Close-SentinelIncident-from-SNOW"
hardcoded subscription ID

2021-06-24 03:22 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_Attacks_ddos.json
> +                        "subscriptions": "6a021fde-5198-441e-9190-9d634e1f4a84",
hardcoded subscription ID

2021-06-24 03:22 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_Attacks_ddos.json
> +                                            "id": "/subscriptions/6a021fde-5198-441e-9190-9d634e1f4a84/resourceGroups/Group-IB-WS/providers/Microsoft.Logic/workflows/GIBIndicatorProcessor"
hardcoded subscription ID

2021-06-24 03:23 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_Attacks_ddos.json
> +                    "connectionId": "/subscriptions/6a021fde-5198-441e-9190-9d634e1f4a84/resourceGroups/Group-IB-WS/providers/Microsoft.Web/connections/azureloganalyticsdatacollector-2",
hardcoded subscription ID

2021-06-24 03:23 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_Attacks_ddos.json
> +                    "connectionId": "/subscriptions/6a021fde-5198-441e-9190-9d634e1f4a84/resourceGroups/Group-IB-WS/providers/Microsoft.Web/connections/azuresentinel-Close-SentinelIncident-from-SNOW"
hardcoded subscription ID

2021-06-24 03:23 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_Attacks_deface.json
> +                        "subscriptions": "6a021fde-5198-441e-9190-9d634e1f4a84",
hardcoded subscription ID

2021-06-24 03:23 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_Attacks_deface.json
> +                                            "id": "/subscriptions/6a021fde-5198-441e-9190-9d634e1f4a84/resourceGroups/Group-IB-WS/providers/Microsoft.Logic/workflows/GIBIndicatorProcessor"
hardcoded subscription ID

2021-06-24 03:23 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_Attacks_deface.json
> +                "defaultValue": "i.ovchinnikov+2@group-ib.com",
hardcoded username

2021-06-24 03:23 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_Attacks_deface.json
> +                    "connectionId": "/subscriptions/6a021fde-5198-441e-9190-9d634e1f4a84/resourceGroups/Group-IB-WS/providers/Microsoft.Web/connections/azureloganalyticsdatacollector-2",
hardcoded subscription ID

2021-06-24 03:23 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_Attacks_deface.json
> +                    "connectionId": "/subscriptions/6a021fde-5198-441e-9190-9d634e1f4a84/resourceGroups/Group-IB-WS/providers/Microsoft.Web/connections/azuresentinel-Close-SentinelIncident-from-SNOW"
hardcoded subscription ID

2021-06-24 03:24 UTC, sarah-yo commented on Solutions/Group-IB/Playbooks/GIBTIA_Attacks_phishing.json
> +                        "subscriptions": "6a021fde-5198-441e-9190-9d634e1f4a84",
hardcoded subscription ID

2021-06-24 03:27 UTC, sarah-yo requested changes
Many hardcoded subscription ID and usernames, there were too many to mark up. Please remove.

Please remove the "en-us" part of the URL in your readme

Please put the playbook title back in for each deployment button in the readme

2021-07-01 04:12 UTC, sarah-yo requested changes
Please put the deploy buttons next to the relevant playbook in the Group-IB Sentinel Playbooks Collections Detailed Description part of the readme

2021-07-04 21:14 UTC, merged