Origin/dev/process events
Azure/Azure-Sentinel pull request #2552
Opened 2021-06-23 07:42 UTC by oshezaf

Fixes #

## Proposed Changes

  -
  -
  -

2021-06-23 13:43 UTC, oshezaf commented
Resolved "notebooks" merge issue and passed tests

2021-06-24 09:01 UTC, YaronFruchtmann commented on Hunting Queries/ASimProcess/imProcess_Suspicious_enumeration_using_adfind.yaml
> +  | where CommandLine matches regex "(.*)>(.*)"
maybe "where CommandLine contains '>' "

2021-07-01 00:27 UTC, shainw requested changes
Other suggestions inline - The only thing that "has" to be changed is removing the submodule updates for Notebooks.  You can get this out of your way by right clicking Notebooks (submodule) in VS during the commit and choosing update:
![submoduleUpdate](https://user-images.githubusercontent.com/45466083/124047078-32914580-d9c8-11eb-9ec0-d907e5df3c3e.png)

2021-07-01 00:56 UTC, shainw requested changes

2021-07-01 00:56 UTC, shainw commented on Parsers/ASimProcess/ARM/ProcessEventGeneric/README.md
> +This template deploys the Source Agnostic ASIM ProcessEvent schema parser. The parser is a part of the Azure Sentinel Information Model.
This is the same as the Empty parser information, shouldn't we make it clear this is for Generic?

2021-07-01 07:40 UTC, oshezaf commented
All issues fixed

2021-07-01 07:41 UTC, merged