Digital Guardian DLP Data Connector
Azure/Azure-Sentinel pull request #2584
Opened 2021-06-29 14:18 UTC by vu-socprime

## Proposed Changes

  - add Digital Guardian DLP Data Connector

2021-07-02 21:17 UTC, v-jayakal commented
@oshezaf , can you please review the parser? Thanks.

2021-07-05 11:14 UTC, v-admahe requested changes

2021-07-06 10:34 UTC, vu-socprime commented on Solutions/DigitalGuardianDLP/Parsers/DigitalGuardianDLPEvent.txt
> +    | summarize bag = make_bag(p)
fixed

2021-07-06 10:34 UTC, vu-socprime commented on Solutions/DigitalGuardianDLP/Data Connectors/Connector_DigitalGuardian_Syslog.json
> +            "legend": "Syslog (DigitalGuardianDLPEvent)",
updated

2021-07-12 11:16 UTC, v-admahe commented
@vu-socprime : We are getting error in parser , it didnot find the timestamp field.

![image](https://user-images.githubusercontent.com/73637076/125278258-1c707700-e330-11eb-8997-d18c081f7895.png)

We have check that this field is available in syslog message but at the time we make a pack of two syslog message field this field timestamp field is not included.

Thanks,
Aditi Maheshwari

2021-07-12 11:16 UTC, v-admahe commented
@shainw could you please review the parser.

Thanks,
Aditi

2021-07-14 11:14 UTC, vu-socprime commented
> @vu-socprime : We are getting error in parser , it didnot find the timestamp field.
> 
> ![image](https://user-images.githubusercontent.com/73637076/125278258-1c707700-e330-11eb-8997-d18c081f7895.png)
> 
> We have check that this field is available in syslog message but at the time we make a pack of two syslog message field this field timestamp field is not included.
> 
> Thanks,
> Aditi Maheshwari

@v-admahe This error occurs when there are no data in the table. Try to use other time period in the query that contains DigitalGuardian events in Syslog table.

2021-07-20 12:18 UTC, v-rucdu approved these changes

2021-07-22 04:36 UTC, v-jayakal approved these changes

2021-07-22 04:36 UTC, merged