Cisco Duo Data Connector
Azure/Azure-Sentinel pull request #2586
Opened 2021-06-29 14:47 UTC by vu-socprime

## Proposed Changes

  - add Cisco Duo Data Connector

2021-07-06 10:24 UTC, v-admahe requested changes

2021-07-06 10:49 UTC, vu-socprime commented on Sample Data/Custom/CiscoDuo_CL.json
> +        "timestamp_d": "1624550594",
updated

2021-07-06 10:49 UTC, v-maudan requested changes

2021-07-06 11:05 UTC, vu-socprime commented on Solutions/CiscoDuoSecurity/Data Connectors/CiscoDuo_API_FunctionApp.json
> +            "description": "Use this method for automated deployment of the data connector using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below. \n\n\t[![Deploy To Azure](https://ak
fixed

2021-07-14 06:51 UTC, v-rucdu approved these changes

2021-07-15 04:56 UTC, v-jayakal approved these changes

2021-07-15 04:56 UTC, merged