Cisco umbrella playbooks
Azure/Azure-Sentinel pull request #2602
Opened 2021-06-30 16:09 UTC by vu-socprime

## Proposed Changes

  - add CiscoUmbrellaEnforcementAPI custom logic app connector
  - add CiscoUmbrellaInvestigateAPI custom logic app connector
  - add CiscoUmbrellaManagementAPI custom logic app connector
  - add CiscoUmbrellaNetworkDeviceManagementAPI custom logic app connector
  - add CiscoUmbrella-BlockDomain playbook
  - add CiscoUmbrella-GetDomainInfo playbook
  - add CiscoUmbrella-AssignPolicyToIdentity playbook

2021-07-01 04:13 UTC, sarah-yo commented on Playbooks/CiscoUmbrella/Playbooks/CiscoUmbrella-AssignPolicyToIdentity/readme.md
> +1. In Azure sentinel analytical rules should be configured to trigger an incident. An incident should have *originId* custom entity. OriginId is Umbrella wide unique identifier for this traffic sourc
Remove "en-us" from URL

2021-07-01 04:13 UTC, sarah-yo commented on Playbooks/CiscoUmbrella/Playbooks/CiscoUmbrella-BlockDomain/readme.md
> +1. In Azure sentinel analytical rules should be configured to trigger an incident with malicious URL. In the *Entity maping* section of the analytics rule creation workflow, malicious URL should be m
Remove "en-us" from URL

2021-07-01 04:13 UTC, sarah-yo commented on Playbooks/CiscoUmbrella/Playbooks/CiscoUmbrella-GetDomainInfo/readme.md
> +1. In Azure sentinel analytical rules should be configured to trigger an incident. In the *Entity maping* section of the analytics rule creation workflow, malicious URL should be mapped to **Url** id
Remove "en-us" from URL

2021-07-01 04:15 UTC, sarah-yo requested changes
Please remove any "en-us" localisation in URLs.

Please tidy up the grammar, spelling and punctuation in the readmes.

2021-07-08 09:35 UTC, vu-socprime commented on Playbooks/CiscoUmbrella/Playbooks/CiscoUmbrella-AssignPolicyToIdentity/readme.md
> +1. In Azure sentinel analytical rules should be configured to trigger an incident. An incident should have *originId* custom entity. OriginId is Umbrella wide unique identifier for this traffic sourc
done

2021-07-08 09:35 UTC, vu-socprime commented on Playbooks/CiscoUmbrella/Playbooks/CiscoUmbrella-BlockDomain/readme.md
> +1. In Azure sentinel analytical rules should be configured to trigger an incident with malicious URL. In the *Entity maping* section of the analytics rule creation workflow, malicious URL should be m
done

2021-07-08 09:35 UTC, vu-socprime commented on Playbooks/CiscoUmbrella/Playbooks/CiscoUmbrella-GetDomainInfo/readme.md
> +1. In Azure sentinel analytical rules should be configured to trigger an incident. In the *Entity maping* section of the analytics rule creation workflow, malicious URL should be mapped to **Url** id
done

2021-07-08 09:36 UTC, vu-socprime commented
> Please remove any "en-us" localisation in URLs.
> 
> Please tidy up the grammar, spelling and punctuation in the readmes.

@sarah-yo Done

2021-07-08 23:08 UTC, v-jayakal commented
@vu-socprime , can you please move these files into solutions folder of Cisco Umbrella? Path for the Cisco Umbrella solution is https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CiscoUmbrella. Please add a folder called Playbooks and move these files. You can refer other solutions with playbooks (ex: Cisco ISE) for reference.

2021-07-08 23:09 UTC, v-jayakal commented
@vu-socprime , can you please move these files into solutions folder of Cisco Umbrella? Path for the Cisco Umbrella solution is https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CiscoUmbrella. Please add a folder called Playbooks and move these files. You can refer other solutions with playbooks (ex: Cisco ISE) for reference.

2021-07-14 08:09 UTC, vu-socprime commented
> Playbooks

@v-jayakal Done

2021-07-14 08:09 UTC, vu-socprime commented
> @vu-socprime , can you please move these files into solutions folder of Cisco Umbrella? Path for the Cisco Umbrella solution is https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/CiscoUmbrella. Please add a folder called Playbooks and move these files. You can refer other solutions with playbooks (ex: Cisco ISE) for reference.

@v-jayakal Done

2021-07-14 20:01 UTC, lior-tamir commented
Very nice playbooks + Logic Apps connectors!

The action "Get Domain Status and Categorization" is not parsed properly (shows only "body" field")
Same about "Assign a policy to an identity", but in this case depends if it can return success/failure status?
Experience for "block domains" is not ideal, must add a parameter to use, and fields names are not intuitive?

2021-07-16 22:35 UTC, sreedharande approved these changes

2021-07-19 08:27 UTC, vu-socprime commented
> The action "Get Domain Status and Categorization" is not parsed properly (shows only "body" field")

@lior-tamir fixed

2021-07-19 08:28 UTC, vu-socprime commented
> Same about "Assign a policy to an identity", but in this case depends if it can return success/failure status?

@lior-tamir Added catching of failures

2021-07-19 08:30 UTC, vu-socprime commented
> Experience for "block domains" is not ideal, must add a parameter to use, and fields names are not intuitive?

@lior-tamir Could you please specify what parameter should be added? Thanks

2021-08-04 13:45 UTC, lior-tamir approved these changes

2021-08-06 04:46 UTC, v-jayakal approved these changes

2021-08-06 04:46 UTC, merged