Added TargetAccount field
Azure/Azure-Sentinel pull request #2665
Opened 2021-07-13 09:45 UTC by jonyluke

I think it would be a good option to add the "TargetAccount" field to the query, in order to see which account the password was tried to change at a glance.

2021-07-19 20:27 UTC, ashwin-patil requested changes
Need version change, rest looks good. Thank you for submitting PR.

2021-07-19 20:27 UTC, ashwin-patil commented on Detections/SecurityEvent/ExcessiveLogonFailures.yaml
> +version: 1.0.0
please change the version to 2.0.0.

2021-07-21 14:38 UTC, ashwin-patil approved these changes

2021-07-22 07:16 UTC, jonyluke commented
Is it necessary any more changes or can the PR be closed? @ashwin-patil

2021-07-22 23:02 UTC, ashwin-patil requested changes
I have found some additional bugs with this query.. Adding the updated query including your proposed changes.. Please review and update PR accordingly..

Additional changes Added:
- Renamed `TargetResourceName` with `TargetUserName` in auditlogs
- replaced `makeset` with `make_set`
- in the output created additional field TargetUserList containing list of accounts
- created field TargetUserName selected recent account in order to assign entity

Final Query:
```
  let PerUserThreshold = 5;
  let TotalThreshold = 100;
  let action = dynamic(["change", "changed", "reset"]);
  let pWord = dynamic(["password", "credentials"]);
  let PasswordResetMultiDataSource =
  (union isfuzzy=true
  (//Password reset events
  //4723: An attempt was made to change an account's password
  //4724: An attempt was made to reset an accounts password
  SecurityEvent
  | where EventID in ("4723","4724")
  | project TimeGenerated, Computer, AccountType, Account, Type, TargetUserName),
  (//Azure Active Directory Password reset events
  AuditLogs
  | where OperationName has_any (pWord) and OperationName has_any (action)
  | extend AccountType = tostring(TargetResources[0].type), Account = tostring(TargetResources[0].userPrincipalName), 
  TargetUserName = tolower(tostring(TargetResources[0].displayName))
  | project TimeGenerated, AccountType, Account, Computer = "", Type),
  (//OfficeActive ActiveDirectory Password reset events
  OfficeActivity
  | where OfficeWorkload == "AzureActiveDirectory" 
  | where (ExtendedProperties has_any (pWord) or ModifiedProperties has_any (pWord)) and (ExtendedProperties has_any (action) or ModifiedProperties has_any (action))
  | extend AccountType = UserType, Account = OfficeObjectId 
  | project TimeGenerated, AccountType, Account, Type, Computer = ""),
  (// Unix syslog password reset events
  Syslog
  | where Facility in ("auth","authpriv")
  | where SyslogMessage has_any (pWord) and SyslogMessage has_any (action)
  | extend AccountType = iif(SyslogMessage contains "root", "Root", "Non-Root")
  | where SyslogMessage matches regex ".*password changed for.*"
  | parse SyslogMessage with * "password changed for" Account
  | project TimeGenerated, AccountType, Account, Computer = HostName, Type)
  );
  let pwrmd = PasswordResetMultiDataSource
  | project TimeGenerated, Computer, AccountType, Account, Type, TargetUserName;
  (union isfuzzy=true  
  (pwrmd
  | summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated), Computerlist = make_set(Computer, 25), AccountType = make_set(AccountType, 25), Computer = arg_max(Computer , TimeGenerated), TargetUserList = make_set(TargetUserName, 25), TargetUserName = arg_max(TargetUserName, TimeGenerated), Total=count() by Account, Type
  | where Total > PerUserThreshold
  | extend ResetPivot = "PerUserReset"),  
  (pwrmd
  | summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated), ComputerList = make_set(Computer, 25), AccountList = make_set(Account, 25), AccountType = make_set(AccountType, 25), Account = arg_max(Account, TimeGenerated), Computer = arg_max(Computer , TimeGenerated), TargetUserList = make_set(TargetUserName,25), TargetUserName = arg_max(TargetUserName, TimeGenerated), Total=count() by Type
  | where Total > TotalThreshold
  | extend ResetPivot = "TotalUserReset")
  )
  | extend timestamp = StartTimeUtc, AccountCustomEntity = Account, HostCustomEntity = Computer
```

2021-07-23 16:03 UTC, ashwin-patil approved these changes

2021-07-23 20:38 UTC, petebryan approved these changes

2021-07-23 20:38 UTC, merged