Updating the logo files for Azure Purview
Azure/Azure-Sentinel pull request #2674
Opened 2021-07-14 14:23 UTC by libarson

Fixes #

## Proposed Changes

  -
  -
  -

2021-07-14 19:10 UTC, v-rucdu requested changes

2021-07-14 19:10 UTC, v-rucdu commented on Logos/AzurePurview.svg
> +<linearGradient id="poh86209-a692-4bef-b7d5-514d43f4e5fa" x1="13.628" y1="14.626" x2="13.628" y2="4.193" gradientUnits="userSpaceOnUse">
Tests are failing because this is not a valid GUID. Please change this and its references.

2021-07-14 19:10 UTC, v-rucdu commented on Workbooks/Images/Logos/AzurePurview.svg
> +<linearGradient id="doh86209-a692-4bef-b7d5-514d43f4e5fa" x1="13.628" y1="14.626" x2="13.628" y2="4.193" gradientUnits="userSpaceOnUse">
Same as above, please generate a valid GUID and update it.

2021-07-15 04:35 UTC, v-jayakal approved these changes

2021-07-15 04:35 UTC, merged