update AutoConnect-ASCSubscriptions
Azure/Azure-Sentinel pull request #2764
Opened 2021-07-30 05:21 UTC by swiftsolves-msft

updated existing playbook AutoConnect-ASCSubscriptions.

1. Leverages MSI now instead of App Registration

2. Updates connector to use Bi-directional sync with Azure Defender

3. updated readme with information with changes.

Fixes #

## Proposed Changes

  -
  -
  -

2021-08-01 21:22 UTC, sarah-yo commented on Playbooks/AutoConnect-ASCSubscriptions/readme.md
> +<li><a href="https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview" target="_blank" rel="noopener">Learn more about Managed Service Identities in Azure A
please remove the "en-us" from the URL

2021-08-01 21:22 UTC, sarah-yo requested changes
Please remove the localisation in the URL (marked in the file) so the document validation doesn't fail, thanks!

2021-08-02 09:23 UTC, lior-tamir commented
@swiftsolves-msft Thanks for the great update!!
Why did we get the resource group/subscription as a parameter instead of the ARM template function?

2021-08-03 19:42 UTC, swiftsolves-msft commented
> @swiftsolves-msft Thanks for the great update!!
> Why did we get the resource group/subscription as a parameter instead of the ARM template function?

Thanks Lior apologies I ahve restored those deploy funcs and removed the params.

2021-08-04 13:46 UTC, lior-tamir approved these changes

2021-08-05 17:32 UTC, sreedharande approved these changes

2021-08-05 17:32 UTC, merged