Unicode obfuscation hunting query
Azure/Azure-Sentinel pull request #2785
Opened 2021-08-04 02:16 UTC by petebryan

New Hunting Query looking for unicode in command lines which could be used to obfuscate malicious activity.

2021-08-04 04:57 UTC, oshezaf requested changes
Pete, can we add imProcessCreate as well? Do you want me to do that?

2021-08-05 16:19 UTC, petebryan commented
> Pete, can we add imProcessCreate as well? Do you want me to do that?

Done

2021-08-05 21:40 UTC, oshezaf requested changes
Small one

2021-08-05 21:40 UTC, oshezaf commented on Hunting Queries/MultipleDataSources/UnicodeObfuscationInCommandLine.yaml
> +  | extend Account = ActorUsernameType, Computer = DeviceName))
1. Should be ActorUsername. Happy to discuss what those "*type" fields are about.
2. Should be DvcHostname, or just Dvc

2021-08-10 15:09 UTC, merged