Data Connector for Armorblox Solution
Azure/Azure-Sentinel pull request #2995
Opened 2021-09-10 20:27 UTC by ujayant

2021-09-12 18:47 UTC, ujayant commented
Looks like the `KqlValidations` are failing even when run for the master branch of the Sentinel repo. Not sure if these failures have got anything to do with this PR.

2021-09-14 08:51 UTC, NikTripathi requested changes

2021-09-14 08:51 UTC, NikTripathi commented on Solutions/Armorblox/Data Connectors/Armorblox_API_FunctionApp.json
> +            "description": "Use this method for automated deployment of the Armorblox data connector using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below. \n\n\t[![Deploy To Azure](
Fix typo Tempate as Template.

2021-09-14 08:51 UTC, NikTripathi commented on Solutions/Armorblox/Data Connectors/Armorblox_API_FunctionApp.json
> +            "description": "**1. Deploy a Function App**\n\n> **NOTE:** You will need to [prepare VS code](https://docs.microsoft.com/azure/azure-functions/functions-create-first-function-python#prer
Choose the subscription to use.\n\n\tc. (e.g. Armorblox).\n\n\te , Choose Python 3.8.\n\n\tf.  Why a c,e and f is at the end?

2021-09-14 08:51 UTC, NikTripathi commented on Solutions/Armorblox/Data Connectors/Armorblox_API_FunctionApp.json
> +            "description": "Use this method for automated deployment of the Armorblox data connector using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below. \n\n\t[![Deploy To Azure](
Please update deployment link as **https://aka.ms/sentinel-armorblox-azuredeploy**

2021-09-14 08:51 UTC, NikTripathi commented on Solutions/Armorblox/Data Connectors/azuredeploy_Armorblox_API_FunctionApp.json
> +                        "WEBSITE_RUN_FROM_PACKAGE": "https://raw.githubusercontent.com/armorblox/Azure-Sentinel/master/Solutions/Armorblox/Data%20Connectors/ArmorbloxAzureFunction.zip"
Please update WEBSITE_RUN_FROM_PACKAGE link as **https://aka.ms/sentinel-armorblox-functionapp**

2021-09-14 09:58 UTC, NikTripathi commented
Please provide sample data in JSON format.

2021-09-17 05:08 UTC, NikTripathi commented
> Please provide sample data in JSON format.
We have used .csv format so no need to update JSON format. Thank You.

2021-09-17 15:57 UTC, urajat commented
@NikTripathi Thanks for the review! All review comments have been addressed.

2021-09-21 13:46 UTC, NikTripathi commented
During the deployment function app is loading. But function is not loading in portal. I think it is a problem because of the structure of zip file. Please have a look on the zip file structure of [CiscoUmbrella](https://github.com/Azure/Azure-Sentinel/tree/master/DataConnectors/CiscoUmbrella). Let me know if something needs to done by my end.

2021-09-27 08:22 UTC, NikTripathi requested changes
Data connector deployment is successful but function name is still not loading. See image for reference.  ![image](https://user-images.githubusercontent.com/87809732/134871164-71c94561-b22d-4f50-aa04-86e680d6301b.png)

2021-09-27 09:11 UTC, ujayant commented
@NikTripathi I'm facing the same issue, and I'm trying to figure it out. It worked for the first time, but subsequent deployments have this issue. 

I faced the same issue even when I just deployed the function app for testing. Changing the name of the function app fixed the issue for me. Any ideas on this?

2021-10-01 11:46 UTC, NikTripathi commented
> @NikTripathi I'm facing the same issue, and I'm trying to figure it out. It worked for the first time, but subsequent deployments have this issue.
> 
> I faced the same issue even when I just deployed the function app for testing. Changing the name of the function app fixed the issue for me. Any ideas on this?

I changed the function name and redeployed it. Still facing the same issue. Function deploys successfully but function is not loading.

2021-10-04 11:48 UTC, urajat commented
@NikTripathi We tried the steps under Manual Deployment of Azure Functions section and that seems to work correctly - we are able to see the function app files load in the portal after deploying via VSCode. Only when we try the ARM template route using the Deploy To Azure button, it seems to show the behaviour that you are seeing with the deployment being successful, but function not loading. We are unable to spot any material differences between the Cisco one and ours. We also cross-checked against a couple of others like SentinelOne for e.g.

2021-10-04 20:15 UTC, ujayant commented
@NikTripathi It looks like there was an extra top-level folder in the zip file. I was able to test it through template-based deployment, and it worked properly. Let me know if you find anything else.

2021-10-04 22:15 UTC, v-jayakal commented
@ujayant - Function gets deployed successfully from template. Invocation logs show error that 'requests' module is missing. I am checking whether there is version issue at my end. Is it running good at your end without error? I will give you update about the version issue at my end by EOD. Please let us know about function invocation result  at your end. Thanks.

2021-10-05 10:19 UTC, NikTripathi commented
Provided zip package doesn't have .python-package folder. I added the python package and tested it. Can you please update the old zip package with the attached zip package.
[ArmorbloxAzureFunction.zip](https://github.com/Azure/Azure-Sentinel/files/7284911/ArmorbloxAzureFunction.zip)

2021-10-05 17:08 UTC, ujayant commented
@NikTripathi I've updated and tested this end-to-end. Everything is working fine.

2021-10-06 13:03 UTC, v-jayakal commented
@ujayant - Its working now, thanks.

2021-10-06 13:03 UTC, v-jayakal approved these changes

2021-10-06 13:04 UTC, merged