Update AzureFirewallWorkbook.json
Azure/Azure-Sentinel pull request #3089
Opened 2021-09-21 19:00 UTC by tobystic

change step function to grain instead of 24hours, to enable visibility for less than 24hours in Application rule logs

Fixes #

## Proposed Changes

  -
  -
  -

2021-09-22 07:41 UTC, NikTripathi commented
@tobystic  Please provide WorkbooksMetadata.json file.

2021-09-23 08:48 UTC, NikTripathi requested changes
@tobystic Please provide WorkbooksMetadata.json file. For any changes in workbook there should be a version update in WorkbooksMetadata.json. So please update WorkbooksMetadata.json and add that file in PR.

2021-10-01 12:59 UTC, NikTripathi commented
@tobystic Please provide WorkbooksMetadata.json file. For any changes in workbook there should be a version update in WorkbooksMetadata.json. So please update WorkbooksMetadata.json and add that file in PR.

2021-10-04 11:18 UTC, v-rucdu approved these changes

2021-10-04 11:18 UTC, merged