[Azure Sentinel Hackathon 2021] Azure Sentinel as new on premise SOAR replacement solution - IBM Qradar Connector
Azure/Azure-Sentinel pull request #3158
Opened 2021-10-03 17:51 UTC by hieuttmmo

When we were looking for hackathon ideas, we found that in common deployment scenario, Azure Sentinel just worked as a "complementary" or second SIEM, serving just for cloud environment and the primary SIEM solution is still typical on-premise product such as IBM QRadar or Splunk. Therefore, we want to do in opposite approach that **Sentinel will act as a primary SIEM/SOAR** - a single pane of glass for all security operation programs. Other SIEMs become the second, sending on premise signal data to Sentinel. Azure Sentinel is a new cyberdefense commander for cloud era. 

We think that this idea is a good fit for any enterprises in cloudification journey, when cloud becomes a major workload and the rest is on premise.

2021-12-16 16:27 UTC, NikTripathi commented
@hieuttmmo  Please resolve conflicts.

2021-12-23 18:38 UTC, NikTripathi requested changes

2021-12-23 18:38 UTC, NikTripathi commented on Sample Data/Event/QradarOffenses.json
> +[
Name of the sample data file should be same as legend name which is **QRadarOffense_CL**

2021-12-23 18:39 UTC, NikTripathi commented
@aprakash13 Please review detections.

2022-01-04 17:08 UTC, NikTripathi commented
@hieuttmmo please resolve conflicts. And please move this in solution folder.

2022-01-07 19:01 UTC, v-jayakal requested changes

2022-01-07 19:01 UTC, v-jayakal commented on Workbooks/WorkbooksMetadata.json
> -      {
Why these workbook entries are removed?

2022-01-18 10:48 UTC, aprakash13 reviewed
There is just one detection that looks ok.  Have made a small suggestion to be fixed. 
Once the submitter fixes it as well as fixes the validation errors, please feel free to approve, if other components look ok.

2022-01-18 10:48 UTC, aprakash13 commented on Detections/Qradar/QRadarMultipleOffensesFromSingleIP.yaml
> +version: 1.0.0
Please add the "kind: Scheduled" property in the end.

2022-02-14 13:35 UTC, v-sabiraj commented
Hey @hieuttmmo , please update the requested changes ,thanks.

2022-02-25 09:20 UTC, vmanojreddy commented
Please resolve conflicts

2022-02-28 11:04 UTC, vmanojreddy commented
@hieuttmmo Please move this in solution folder.

2022-03-06 06:06 UTC, hieuttmmo commented
> @hieuttmmo Please move this in solution folder.

@vmanojreddy Just moved, sorry for the delay

2022-03-10 09:07 UTC, vmanojreddy commented
@hieuttmmo  Workbook query's are failing please look into it. Thanks!!
![image](https://user-images.githubusercontent.com/90677907/157628055-ea6b434b-e287-4f23-baaa-9ec28da3b102.png)

2022-03-31 10:57 UTC, vmanojreddy commented
@hieuttmmo please update the requested changes ,thanks!!!

2022-04-04 11:58 UTC, vmanojreddy commented
@hieuttmmo please update the requested changes ,thanks!!!

2022-04-07 07:18 UTC, ashishsyal commented
@hieuttmmo - Please let us know if you will be able to move this forward..

2022-04-07 10:29 UTC, hieuttmmo commented
Can you guys check it again

2022-04-07 10:33 UTC, vmanojreddy commented
@hieuttmmo Please resolve conflicts. thanks!!!

2022-04-07 10:39 UTC, hieuttmmo commented
> @hieuttmmo Please resolve conflicts. thanks!!!

Conflict resolved

2022-04-07 10:42 UTC, hieuttmmo commented
> @hieuttmmo Workbook query's are failing please look into it. Thanks!! ![image](https://user-images.githubusercontent.com/90677907/157628055-ea6b434b-e287-4f23-baaa-9ec28da3b102.png)

I checked the table name again, it is correct. The might be the lack of the QradarOffenses_CL table in your Sentinel instance

2022-04-07 12:56 UTC, vmanojreddy commented
@hieuttmmo Please move the files into solution folder. thanks!!!

2022-04-07 17:51 UTC, hieuttmmo commented
> @hieuttmmo Please move the files into solution folder. thanks!!!

I moved the Detection rule and Workbook in to the Solutions/Qradar folder

2022-04-11 09:16 UTC, vmanojreddy commented
@hieuttmmo Please update the azuredeploy short link https://aka.ms/sentinel-qradarconnector-azuredeploy. thanks!!!

2022-04-11 09:41 UTC, hieuttmmo commented
> https://aka.ms/sentinel-qradarconnector-azuredeploy

Yes, I update the shorten link as per requested

2022-04-13 06:00 UTC, aprakash13 reviewed
There is just one query that looks ok from a query perspective.
Please feel free to merge if everything else looks good.

2022-06-01 09:36 UTC, vmanojreddy commented
@hieuttmmo  Please resolve conflicts. thanks!!!

2022-06-22 10:57 UTC, v-dvedak commented
@hieuttmmo, Please resolve conflicts.

2022-06-27 10:29 UTC, vmanojreddy commented
@hieuttmmo We wanted to check on the status of PR [IBM Qradar Connector](https://github.com/Azure/Azure-Sentinel/pull/3158#)
#3158. PR is pending from long time. Let us know if any assistance is required for this PR. Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

2022-07-06 05:09 UTC, vmanojreddy commented
@hieuttmmo We wanted to check on the status of PR https://github.com/Azure/Azure-Sentinel/pull/3158#
https://github.com/Azure/Azure-Sentinel/pull/3158. PR is pending from long time. Let us know if any assistance is required for this PR. Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

2022-07-25 08:14 UTC, v-spadarthi commented
@hieuttmmo : Could you please resolve the conflicts

2022-07-28 01:18 UTC, v-spadarthi commented
@hieuttmmo : Please resolve the conflicts. Thanks !

2022-08-05 07:34 UTC, v-dvedak commented
Hey @hieuttmmo, we wanted to check on the status of this [PR](https://github.com/Azure/Azure-Sentinel/pull/3158)
. It is pending from more than 60 days. Let us know if any assistance is required for this PR. Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

2022-08-16 02:43 UTC, v-spadarthi commented
Hi @hieuttmmo, since we have not received response from last 7 days, we are closing your PR per our standard operating procedures. If you still need support for this issue, you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

2022-08-16 02:43 UTC, closed without merging