Create DHCPAudit Parser Function
Azure/Azure-Sentinel pull request #3333
Opened 2021-10-28 15:54 UTC by mayurrr98

Fixes #

## Proposed Changes

  -
  -
  -

2021-10-31 08:47 UTC, oshezaf requested changes
Thanks for the contribution. 

Apart from the comments on specific lines, I would appreciate also the following: 

- Please add sample data to the `Sample Data/Custom` folder, so I can verify the parser.
- Please add to the description how to set up collection.
- Please rename: put in a folder under parsers and add an extension, for example `parsers/DHCP_OMS/DHCPAudit.txt`

2021-10-31 08:47 UTC, oshezaf commented on Parsers/DHCPAuditParserFunction
> +| mv-expand EventOriginalUid=splitted[0], Date=splitted[1], Time=splitted[2], EventOriginalType=splitted[3] ,SrcIpAddr=splitted[4], SrcHostname=splitted[5], SrcMacAddr=splitted[6], SrcUsername=splitt
Not sure why use `mv-expand` instead of just `extend`.

2021-10-31 08:47 UTC, oshezaf commented on Parsers/DHCPAuditParserFunction
> +// Author:          Microsoft
Should be the author of the parser, not the source.

2022-01-07 18:50 UTC, v-jayakal commented
@mayurrr98  - Can you please the comments provided, Thanks

2022-03-08 04:28 UTC, NikTripathi commented
@mayurrr98 Can you please resolve the comments.

2022-03-25 09:46 UTC, v-sabiraj commented
Hey @mayurrr98 , will you please resolve the requested changes, thanks.

2022-04-06 12:55 UTC, v-sabiraj commented
Hey @mayurrr98 , will you please resolve the requested changes, thanks.

2022-04-07 15:49 UTC, v-sabiraj commented
As @ashishsyal, has discussed with author @mayurrr98 we are closing this PR.

2022-04-07 15:49 UTC, closed without merging