Nginx content
Azure/Azure-Sentinel pull request #3397
Opened 2021-11-08 09:39 UTC by vu-socprime

## Proposed Changes

  - add Nginx workbook
  - add Nginx analytic rules
  - add Nginx hunting queries

2021-11-11 00:13 UTC, NikTripathi requested changes

2021-11-11 00:13 UTC, NikTripathi commented on Solutions/NGINX/Analytic Rules/NGINXRequestToSensitiveFiles.yaml
> +name: NGINX - Request to sensetive files
Typo sensetive  -> sensitive

2021-11-11 00:13 UTC, NikTripathi commented on Solutions/NGINX/Analytic Rules/NGINXRequestToSensitiveFiles.yaml
> +  'Detects request to sensetive files.'
Typo sensetive  -> sensitive

2021-11-11 00:16 UTC, NikTripathi commented
@aprakash13 Please review analytic rules.

2021-11-12 10:55 UTC, vu-socprime commented on Solutions/NGINX/Analytic Rules/NGINXRequestToSensitiveFiles.yaml
> +name: NGINX - Request to sensetive files
fixed

2021-11-12 10:55 UTC, vu-socprime commented on Solutions/NGINX/Analytic Rules/NGINXRequestToSensitiveFiles.yaml
> +  'Detects request to sensetive files.'
fixed

2021-11-19 10:01 UTC, NikTripathi reviewed
Workbook looks good. Can merge after @aprakash13's approval.

2021-11-24 12:31 UTC, NikTripathi requested changes

2021-11-24 12:31 UTC, NikTripathi commented on Solutions/NGINX/Analytic Rules/NGINXCoreDump.yaml
> +      - NGINXHTTPServer
The name 'NGINXHTTPServer' does not refer to any known table, tabular variable or function. Because of that validations are failing.  You will have to add its schema in json format under [CustomTable folder](https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables). Only than the validations would pass. Please update.

2021-11-26 11:10 UTC, vmanojreddy commented
@spsocprime In  checks list Kqlvalidations failing due to NGINXHTTPServer table does not refering to any table in CustomTables folder.Path refrence https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables.

2021-11-26 11:26 UTC, vmanojreddy commented
@vu-socprime   In  checks list failing due to connectorId  NGINXHTTPServer could not found in ValidConnectorIds file please add the Id in the file.
Path refrence: https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/detectionTemplateSchemaValidation/ValidConnectorIds.json.

2021-12-01 11:18 UTC, vu-socprime commented on Solutions/NGINX/Analytic Rules/NGINXCoreDump.yaml
> +      - NGINXHTTPServer
updated

2021-12-01 11:19 UTC, vu-socprime commented
> @vu-socprime In checks list Kqlvalidations failing due to NGINXHTTPServer table does not refering to any table in CustomTables folder.Path refrence https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables.

@vmanojreddy Updated

2021-12-01 11:21 UTC, vu-socprime commented
> @vu-socprime In checks list failing due to connectorId NGINXHTTPServer could not found in ValidConnectorIds file please add the Id in the file.
> Path refrence: https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/detectionTemplateSchemaValidation/ValidConnectorIds.json.

@vmanojreddy Updated

2021-12-04 19:57 UTC, NikTripathi commented
@aprakash13 Please review analytic rules. Thanks

2021-12-08 13:12 UTC, v-sabiraj commented
Hey @vu-socprime, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

2021-12-09 13:57 UTC, vu-socprime commented
> Hey @vu-socprime, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

@v-sabiraj Updated

2021-12-13 09:36 UTC, spsocprime commented
fixed

2021-12-13 17:58 UTC, NikTripathi commented
@aprakash13  Please verify the changes and approve. Thanks

2021-12-16 07:08 UTC, merged