Created Joshua Cyberiskvision Solution
Azure/Azure-Sentinel pull request #3427
Opened 2021-11-11 16:53 UTC by cyberiskvision

First revision of Joshua Cyberiskvision Solution for Microsoft Sentinel developed by Almaviva S.p.A.

For more information visit the following links:
https://www.cyberiskvision.com/
https://www.almaviva.it/en_GB

2021-11-19 05:10 UTC, ritika-msft commented
@anki-narravula please review this playbook. Thanks.

2021-11-23 15:44 UTC, anki-narravula commented
Hi @cyberiskvision Thank you for creating solution. Please find my comments below

1. Can you please move data connectors into Data Connectors folder - Solutions/Joshua-Cyberiskvision/Data Connectors/ to avoid confusion

> Solutions/Joshua-Cyberiskvision/Playbooks/Indicator-Processor/Joshua-Import-To-Sentinel.json
> Solutions/Joshua-Cyberiskvision/Playbooks/Indicator-Processor/Joshua-Indicators-Processor-DOMAIN.json
> Solutions/Joshua-Cyberiskvision/Playbooks/Indicator-Processor/Joshua-Indicators-Processor-EMAIL.json

2. Below will be remains in Playbooks folder 

> Solutions/Joshua-Cyberiskvision/Playbooks/Intel-Enrichment/Joshua-Intel-Enrichment-FILE.json
> Solutions/Joshua-Cyberiskvision/Playbooks/Intel-Enrichment/Joshua-Intel-Enrichment-URL.json
> Solutions/Joshua-Cyberiskvision/Playbooks/Intel-Enrichment/Joshua-Intel-Enrichment-IP.json

Below recommendations are for (Enrichment - Playbooks) those are in Playbooks folder. We will update you on Data Connectors soon

3. Unless it is mandatory as per the functionality, we recommend to start the playbook with incident trigger instead of alert trigger. So that you don't require 2 steps ( Alert Trigger --> Get - Incident details). You will get incident date from the Incident trigger itself. Let me know if there is any confusion in this

![image](https://user-images.githubusercontent.com/10404181/141415824-5854ea65-5940-437f-acbf-8d7a82f9d745.png)

New will be

![image](https://user-images.githubusercontent.com/10404181/141415952-88d12290-48ff-4abc-a70b-5710f0f6f5f5.png)


4. As a best practice, we recommend sentinel connection in playbooks uses "ManagedSecurityIdentity".
Please refer Sample [Template](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json) for sample template. For more details, refer [this](https://techcommunity.microsoft.com/t5/azure-sentinel/what-s-new-managed-identity-for-azure-sentinel-logic-apps/ba-p/2068204). Make sure to do changes at 3 places 

![image](https://user-images.githubusercontent.com/10404181/141414755-5b90164b-ae6c-415d-9ee2-4a2725ea6cd4.png)

![image](https://user-images.githubusercontent.com/10404181/141414637-b4c76777-4201-43e7-929f-4389cca0ef19.png)

![image](https://user-images.githubusercontent.com/10404181/141414457-2bb8c70a-7e3c-4897-8acb-84eeaba62681.png)

5. Avoid deployment parameters which are really don't require from user perspective. For example Tag and sentinel name can be avoided from deployment parameters

![image](https://user-images.githubusercontent.com/10404181/143055181-db6e85e7-fd9d-406b-b612-11a9f76d16c9.png)

6. Rename the deployment file to azuredeploy.json, you can refer to solution for folder structure https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/RiskIQ/Playbooks

7. Sample template available at for reference https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json

2021-11-27 19:53 UTC, NikTripathi requested changes

2021-11-27 19:53 UTC, NikTripathi commented on Solutions/Joshua-Cyberiskvision/Playbooks/Intel-Enrichment/README.md
> +Through this integration, the analist can enrich incidents with further information.
Typo analist -> analyst

2021-11-30 14:58 UTC, cyberiskvision commented
Hi @anki-narravula,
we can't switch trigger from "Alert" to "Incident" because enrichment should be available for manual trigger from alert investigation pane.
All other changes were made successfully.

2021-12-01 16:21 UTC, anki-narravula commented
> Hi @anki-narravula, we can't switch trigger from "Alert" to "Incident" because enrichment should be available for manual trigger from alert investigation pane. All other changes were made successfully.

Hi @cyberiskvision  Thanks for making changes. I don't see changes reflected for "Playbooks" (which are in Playbook folder) - like Using system managed account, renaming and removing deployment parameters. Am I missing something ?

2021-12-01 16:22 UTC, anki-narravula commented
Hi @v-jayakal  - Now we have data connectors moved to separate folder. Please review data connectors

2021-12-03 06:14 UTC, anki-narravula commented
Hi @cyberiskvision  Apologies, there was some confusion for TI category for Data connectors vs Playbooks. We need to go with Playbooks folder only for TI category. Can you please move everything into Playbooks folder and we are good to go.
And as I have recommended earlier, please use managed identity connection for all sentinel related connectors (for authentication with Sentinel) for playbooks "Joshua-Intel-Enrichment-FILE/URI/IP.json".

2021-12-04 19:56 UTC, NikTripathi commented
@anki-narravula  Please approve so that we can merge. Thank you.

2021-12-06 07:17 UTC, anki-narravula approved these changes
This looks good. We can merge it.

2021-12-08 11:45 UTC, v-rucdu approved these changes

2021-12-08 11:46 UTC, merged