add cisco secure endpoint analytic content
Azure/Azure-Sentinel pull request #3432
Opened 2021-11-12 14:27 UTC by spsocprime

Fixes #
Added analytic contetnt for Cisco Secure Endpoint Data Connector

2021-11-18 00:44 UTC, aprakash13 requested changes
The queries generally look good. However, for the  analytical rules  we need to add version number and kind in the end after entity mapping. Something like below.

version: 1.0.0
kind: Scheduled

See a detection rule as an example:  https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ASimFileEvent/imFileESolarWindsSunburstSupernova.yaml

2021-11-19 09:52 UTC, NikTripathi requested changes
Workbook queries are failing. Please look into it. Thanks
![image](https://user-images.githubusercontent.com/87809732/142602629-5d13bec2-4810-491a-af7d-547a6c49dd76.png)

2021-11-19 10:10 UTC, spsocprime commented
> Workbook queries are failing. Please look into it. Thanks ![image](https://user-images.githubusercontent.com/87809732/142602629-5d13bec2-4810-491a-af7d-547a6c49dd76.png)

We've made PR for updating parser/function for this data connector(https://github.com/Azure/Azure-Sentinel/pull/3431). So I guess your functions does not have this fields which were added in the PR.
If you merge abovementioned PR it will fix the issue

2021-11-24 10:14 UTC, NikTripathi approved these changes
Workbook looks good. Can merge once validations passes.

2021-11-24 10:20 UTC, NikTripathi requested changes

2021-11-24 10:20 UTC, NikTripathi commented on Solutions/CiscoSecureEndpoint/Analytic Rules/CiscoSEWebshell.yaml
> +id: b6df3e11-de70-4779-ac9a-276c454a9025
There should not be 2 templates with the same ID, but the id b6df3e11-de70-4779-ac9a-276c454a9025 is duplicated.

2021-11-24 12:26 UTC, NikTripathi commented
Since you are using the parser in queries, you will have to add its schema in json format under [CustomTable folder](https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables). Only than the validations would pass.

2021-11-26 11:02 UTC, vmanojreddy commented
@spsocprime  checks failing due to CiscoSecureEndpoint table could not found in CustomTables folder.
Path refrence https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables

2021-12-02 18:16 UTC, NikTripathi commented
@spsocprime Please update.

2021-12-09 08:46 UTC, NikTripathi commented
@spsocprime please address my comments. Thanks

2021-12-10 09:05 UTC, NikTripathi commented
@spsocprime Please resolve conflicts.

2021-12-10 14:11 UTC, spsocprime commented
fixed

2021-12-16 07:09 UTC, merged