analytic content for palo alto cdl
Azure/Azure-Sentinel pull request #3596
Opened 2021-12-01 17:30 UTC by spsocprime

## Proposed Changes
 Added analytic content for Palo Alto CDL data connector

2021-12-08 11:57 UTC, v-sabiraj commented
Hey @spsocprime, We have resolved the issue for PR Validations failure and request you to please update your PR branch with the latest changes from **Azure:master** so that the PR Validations can be executed.... Thanks!!!

2021-12-10 13:27 UTC, spsocprime commented
The only issue is with 'Recon' tactic. I guess it is not included in the list (within checking script) cause it is rather new one.
![image](https://user-images.githubusercontent.com/94110440/145580947-b34f23de-7efd-42e1-b9f0-acf9bb7e7647.png)

2021-12-16 16:16 UTC, NikTripathi commented
@aprakash13 Please review analytic rules.

2021-12-22 06:13 UTC, v-sabiraj commented
![image](https://user-images.githubusercontent.com/94349919/147044335-4410a688-ce0f-4846-b8fa-d248b6f98f59.png)
![image](https://user-images.githubusercontent.com/94349919/147044569-b6c01829-d271-4bb8-9b2c-39e1303e7e2b.png)
Please fix the workbooks query, thanks.

2021-12-23 12:09 UTC, spsocprime commented
> ![image](https://user-images.githubusercontent.com/94349919/147044335-4410a688-ce0f-4846-b8fa-d248b6f98f59.png) ![image](https://user-images.githubusercontent.com/94349919/147044569-b6c01829-d271-4bb8-9b2c-39e1303e7e2b.png) Please fix the workbooks query, thanks.

The query fails because this field name is dynamically created when there are certain types of events from that log source. I guess, the issue exists because there are no such events in your environment

2021-12-24 09:10 UTC, v-sabiraj commented
![image](https://user-images.githubusercontent.com/94349919/147338450-fb812b9c-de2e-4f51-a243-198eb7cde738.png)
The parser has same error, please update.

2021-12-28 10:50 UTC, v-sabiraj approved these changes

2021-12-28 10:50 UTC, v-sabiraj commented
Workbooks looks good, can merge once @aprakash13 review and approve, thanks.

2021-12-28 10:55 UTC, v-sabiraj commented
Workbooks look good, need to fix validation errors, thanks.

2021-12-28 13:22 UTC, v-rucdu commented
> The only issue is with 'Recon' tactic. I guess it is not included in the list (within checking script) cause it is rather new one. ![image](https://user-images.githubusercontent.com/94110440/145580947-b34f23de-7efd-42e1-b9f0-acf9bb7e7647.png)

Hey @spsocprime, we have added the attack tactics, can you please merge the latest from Azure:master and see if Validations are passing now... Thanks!!!

2021-12-28 13:45 UTC, v-rucdu commented
@aprakash13 : Can you please take a look at the Analytical Rules... Thanks!!!

2021-12-30 22:08 UTC, aprakash13 requested changes
Made some suggestions for improvement. Please have a look. Thanks.

2021-12-30 22:08 UTC, aprakash13 commented on Solutions/PaloAltoCDL/Hunting Queries/PaloAltoCDLIncompleteApplicationProtocol.yaml
> +  'Query shows incomplete application protocol'
Can we please check the detection logic and the description. From the logic seems like we are not checking anything related to incomplete application protocol. Please double check.

2021-12-30 22:08 UTC, aprakash13 commented on Solutions/PaloAltoCDL/Hunting Queries/PaloAltoCDLMultiDenyResultbyUser.yaml
> +  | where threshold < DenyCount
Wondering if we wanted DenyCount > Threshold here.

2021-12-30 22:08 UTC, aprakash13 commented on Solutions/PaloAltoCDL/Hunting Queries/PaloAltoCDLOutdatedAgentVersions.yaml
> +  'Query shows agent versions'
Should the description say something about showing agents that are not on the latest version as we are using | where PanOSAgentVersion != cur_ver in the query.

2021-12-30 22:08 UTC, aprakash13 commented on Solutions/PaloAltoCDL/Hunting Queries/PaloAltoCDLOutdatedConfigVersions.yaml
> +  'Query shows outdated config vesions'
Should the query description be the Query shows agent versions. I do not see the below being used in the query for comparison.
let cur_ver = dynamic(['0.1']); //put latest config version here

2021-12-30 22:08 UTC, aprakash13 commented on Solutions/PaloAltoCDL/Hunting Queries/PaloAltoCDLRareApplicationLayerProtocol.yaml
> +  | sort by ApplicationLayerProtocol asc
How do we determine what is rare. Did we also wanted to do a top 5 or top 10 here.

2022-01-10 07:20 UTC, v-sabiraj commented
@spsocprime , please fix the requested changes, thanks.

2022-01-14 11:40 UTC, v-sabiraj commented
@spsocprime ,please update the changes. Thanks.

2022-01-18 05:09 UTC, NikTripathi commented
@aprakash13 Please verify the changes made and approve. Thank you.

2022-01-19 15:07 UTC, aprakash13 approved these changes
Modified queries as suggested. Approved

2022-01-19 19:40 UTC, merged