MITRE notebook bugfixes and updated navigation layer files
Azure/Azure-Sentinel pull request #3662
Opened 2021-12-09 01:33 UTC by ashwin-patil

Fixes #

## Proposed Changes

  - Added bugfixes for notebook
  - sentinel rebranding 
  - updated output csv files
  - generated new navigator layer files with attack v10 - navigator - 4.5.2
  - updated svg files

2021-12-09 01:54 UTC, ashwin-patil commented
@aprakash13  sampleDataValidator test is failing for Navigator json layer files which are in different format as compared to traditional log files. Not sure how to add exception for these or recommended way to pass these tests. 

Let me know and will update PR accordingly.

2021-12-16 22:40 UTC, preetikr commented
@chinguyen1 - to help review notebooks included 
@ashishsyal  / @v-jayakal - to review everything else 

Thanks!

2021-12-17 18:42 UTC, chinguyen1 commented
Assigning notebook review to @ianhelle. Can you please help review the notebook?

2021-12-20 12:24 UTC, vmanojreddy commented
Logo should be less than 5kb.

2022-01-03 22:45 UTC, petebryan commented
So on the notebooks there are a few changes you can make:
init_notebook can be accessed directly msticpy now.
i.e.
```
import msticpy
msticyp.init_notebook()
```

You can remove the commented out widgets import now

Could we move the items defined as 'Custom dataset for non-standard formatted alerts in the doc. - May need updates to keep it current' to a table on GitHub to make version control and updates easier?

There are some other re-factoring elements you could also consider to reduce the amount of code needed but these aren't things that need to be done now.

2022-01-05 11:01 UTC, vmanojreddy requested changes

2022-01-18 19:29 UTC, ashwin-patil commented on Sample Data/MITRE ATT&CK/images/AWS_Layer_Json_File_for_Azure_Sentinel.svg
> -<svg width="1056" height="816" xmlns="http://www.w3.org/2000/svg" id="svgvm1"><g transform="translate(5,5)" style="font-family: sans-serif;"><g transform="translate(0,1)"><g><g class="tactic initial-
Unfortunately this is not possible. These are image file formats and it is required to display images correctly. We may have to add exception for such file formats in the failing tests.

2022-01-18 19:32 UTC, ashwin-patil commented
> Logo should be less than 5kb.

There are no logos in this PR. SVG files are referenced in Workbook as static representation of MITRE Matrix hence included in the Sample data folder. We may need some changes to tests to add exception for it.

2022-01-20 09:41 UTC, vmanojreddy commented
@ashwin-patil  Sample data file data must be in the form of array.

2022-02-16 15:43 UTC, vmanojreddy commented
@ashwin-patil  Please resolve conflicts.

2022-02-18 22:44 UTC, ashwin-patil commented
> @ashwin-patil Sample data file data must be in the form of array.

> @ashwin-patil Please resolve conflicts.

Clean PR #4221 is opened , closing this old PR. Please review new PR
Changes/Fixes: 
- resolve merge conflicts
- notebook updates.
- passing all validation checks

2022-02-18 22:44 UTC, closed without merging