Add Solution for Red Canary
Azure/Azure-Sentinel pull request #3858
Opened 2022-01-06 20:55 UTC by rc-iwoodley

**Description for the PR:**

[Red Canary website](https://redcanary.com).

Change(s):
- Added a Red Canary data connector, logo, and sample data.

**Testing Completed:**
Yes/ No : **Yes**

2022-01-20 10:36 UTC, v-sabiraj commented
Hey @aprakash13 ,please review Analytic Rules, thanks.

2022-01-26 16:34 UTC, samstraka-redcanary commented
Hey @aprakash13 , please let us know if you have any questions about the analytic, we are really excited to get this out!

2022-01-28 05:47 UTC, aprakash13 reviewed
Looks good from a query perspective. Please feel free to approve if other content looks good.

2022-01-28 06:46 UTC, v-sabiraj commented
Hey @samstraka-redcanary , please check and confirm for the above changes, otherwise we are good to merge.

2022-01-28 08:31 UTC, aprakash13 requested changes
Please make the changes in the Tactics section.

2022-01-28 08:31 UTC, aprakash13 commented on Solutions/RedCanary/Analytic Rules/RedCanaryThreatDetection.yaml
> +  - PreAttack
PreAttack is not currently a supported tactics for the Sentinel queries. Here is a list that we currently support: https://attack.mitre.org/tactics/enterprise/ 

Please remove this from the tactics list.

2022-01-31 05:34 UTC, v-sabiraj approved these changes

2022-01-31 06:52 UTC, merged