Adding a new workbook on Log4j hunting
Azure/Azure-Sentinel pull request #3888
Opened 2022-01-11 16:36 UTC by samikroy

Change(s):

Azure-Sentinel/Workbooks/Log4jPostCompromiseHunting - A new workbook added with the following tabs
FindTrace - A lookup to curated IOCs across all sentinel tables.
SecurityNestedRecommendation - This section uses the Azure Defender Security Nested Recommendations data to find
machines vulnerable to log4j CVE-2021-44228. Log4j is an open-source Apache logging library that is used in many Java-
based applications. Security Nested Recommendations data is sent to Microsoft Sentinel using the continuous export
feature of Azure Defender
AzureDiagnostics - Azure Diagnostics
MultipleDataSources - Across multiple data sources
Syslog - From Syslog Sources

Azure-Sentinel/Workbooks/WorkbooksMetadata.json - To add workbook metadata.

Azure-Sentinel/Workbooks/Images/Logos - To add workbook logo.

Azure-Sentinel/Workbooks/Images/Preview - To add preview images.

2022-01-12 05:15 UTC, v-rucdu requested changes
@samikroy : I think you missed to add workbook.json here, can you please add it... Thanks!!

2022-01-12 20:29 UTC, samikroy commented
> @samikroy : I think you missed to add workbook.json here, can you please add it... Thanks!!

@v-rucdu & @v-rucdu - Thank you for highlighting this. 
Have added the files as requested.
Please let me know for further changes.

2022-01-19 12:17 UTC, v-rucdu commented
> > @samikroy : I think you missed to add workbook.json here, can you please add it... Thanks!!
> 
> @v-rucdu & @v-jayakal - Thank you for highlighting this. Have added the files as requested. Please let me know for further changes.

@samikroy : You have added the workbook.json under Images folder, can you please delete and add it under Workbooks folder... and in solutions WorkbookMetadata.json is not required... please delete it... thanks!!!

2022-01-19 12:23 UTC, samikroy commented
> > > @samikroy : I think you missed to add workbook.json here, can you please add it... Thanks!!
> > 
> > 
> > @v-rucdu & @v-jayakal - Thank you for highlighting this. Have added the files as requested. Please let me know for further changes.
> 
> @samikroy : You have added the workbook.json under Workbooks-->Images folder, can you please delete and add it under Workbooks folder... and in solutions WorkbookMetadata.json is not required... please delete it... thanks!!!

Done.

2022-01-19 12:26 UTC, v-rucdu approved these changes

2022-01-19 12:27 UTC, merged

2022-01-19 12:36 UTC, samikroy commented
Thank you @v-rucdu for the approval & merge.