Rpressburger/align insights preview with investigation service
Azure/Azure-Sentinel pull request #3894
Opened 2022-01-12 10:17 UTC by rpressburger

There were some gaps between the investigation service and github.
We align both.

2022-01-20 08:04 UTC, aprakash13 requested changes
Made a few minor comments that probably need to be looked at before we can go ahead and merge these. Thanks, Royi.

2022-02-02 09:42 UTC, rpressburger commented on Insights/Account/AzActivity_AzureOps.yaml
> +  | where OperationNameValue contains "Run Command on Virtual Machine"
Value updated

2022-02-06 11:35 UTC, rpressburger commented
@aprakash13 Can you please take a look again?

2022-02-08 01:59 UTC, aprakash13 approved these changes
Thanks for the changes @rpressburger.

2022-02-08 01:59 UTC, merged