Windows events batch 2 v2
Azure/Azure-Sentinel pull request #4059
Opened 2022-02-01 12:52 UTC by yaelrbergman

-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> After the submission has been made, please look at the Validation Checks.

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2022-02-01 15:11 UTC, oshezaf requested changes
One last question! I promise (well I can never promise)

2022-02-01 15:45 UTC, yaelrbergman commented on Detections/SecurityEvent/PotentialBuildProcessCompromise.yaml
> +  | where EventID == 4663 and EventData has_any ("0x6", "0x4", "0X100") and EventData has_any ("*.cs$", "*.cpp$")
I tried to replace the endswith in line 83 with "$", the regexp won't work here?

2022-02-02 04:37 UTC, shainw commented
@yaelrbergman - Please be sure to fill out the PR template, it is required.  Additionally, looks you have conflicts with master that need to resolved.

2022-02-15 21:41 UTC, oshezaf commented on Detections/SecurityEvent/PotentialBuildProcessCompromise.yaml
> +  | where EventID == 4663 and EventData has_any ("0x6", "0x4", "0X100") and EventData has_any ("*.cs$", "*.cpp$")
No has_any does not support regex. It does not matter. has_any only prefitler. Line 83 will do the rest of the job. So, remove the "$"

2022-03-10 09:41 UTC, oshezaf approved these changes

2022-03-10 09:41 UTC, merged