Windows event batch3 v2
Azure/Azure-Sentinel pull request #4064
Opened 2022-02-01 16:42 UTC by yaelrbergman

-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> After the submission has been made, please look at the Validation Checks.

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

Added WindowsEvent to the detections:
powershell_empire
GainCodeExecutionADFSviaWMI
ADFS-DKM-MasterKey-Export
AADHostLoginCorrelation
EmailAccessviaActiveSync
ExchangeServerVulnerabilitiesMarch2021IoCs
-----------------------------------------------------------------------------------------------------------

2022-02-03 07:22 UTC, oshezaf requested changes
Actually it looks great. As I said: the first one is hard, but than things flow. And then, I still had comments :-)

2022-02-03 07:22 UTC, oshezaf commented on Detections/MultipleDataSources/GainCodeExecutionADFSviaWMI.yaml
> +  WindowsEvent
Here again the original did not check for an Event Id and we may need to. I think it is also good as a best practice.

2022-02-03 07:22 UTC, oshezaf commented on Detections/SecurityEvent/powershell_empire.yaml
> +  //where FileName in~ ("powershell.exe","powershell_ise.exe","pwsh.exe")
The comment would not work as is.

2022-02-03 07:22 UTC, oshezaf commented on Detections/SecurityEvent/powershell_empire.yaml
> +  | where EventData has_any ("-encodedCommand", "powershell.exe","powershell_ise.exe","pwsh.exe")
KQL may optimze for that, but I would start with the positive tests and than do the exclusion with not.

2022-02-07 08:42 UTC, yaelrbergman commented on Detections/MultipleDataSources/EmailAccessviaActiveSync.yaml
> +  ( WindowsEvent
should I add event 4688 filter to security events as well? @oshezaf

2022-02-07 10:02 UTC, oshezaf commented on Detections/MultipleDataSources/EmailAccessviaActiveSync.yaml
> +  ( WindowsEvent
Yes

2022-02-08 15:30 UTC, oshezaf requested changes
Two comments are nice to have and one I am not sure about: it seems you missed on a version number update, though you marked it as resolved, so maybe something on my system.

2022-02-08 15:30 UTC, oshezaf commented on Detections/MultipleDataSources/ExchangeServerVulnerabilitiesMarch2021IoCs.yaml
> +  (WindowsEvent
Not sure why, but it does not show as if the version number was updated.

2022-02-21 08:31 UTC, oshezaf approved these changes

2022-02-21 08:32 UTC, merged