InsightVMCloud - adding chunks, fixes
Azure/Azure-Sentinel pull request #4140
Opened 2022-02-09 15:08 UTC by averbn

Change(s):
   - Adding chunks for split big messages for avoiding 413 Error 

   Reason for Change(s):
   - 413 Error while sending messages to the Microsoft Sentinel

2022-03-03 11:41 UTC, v-rucdu requested changes

2022-03-03 12:31 UTC, averbn commented on Solutions/Rapid7InsightVM/Data Connectors/InsightVMCloudAPISentinelConnector/function.json
> +      "schedule": "0 0 0 * * *"
A report for all hosts will be generated at each running. I think it makes no sense to generate a report every hour, so I set it for every day. So customer can change the schedule according to his scan schedule(once per day/week/month)

2022-04-04 11:01 UTC, v-sabiraj commented
Hey @averbn, please resolve the conflicts, thanks.

2022-04-04 11:28 UTC, averbn commented
We need to close this PR because  the new PR was created: https://github.com/Azure/Azure-Sentinel/pull/4504

2022-04-04 11:28 UTC, closed without merging