Update Potential_IIS_CodeInject.yaml
Azure/Azure-Sentinel pull request #4161
Opened 2022-02-14 10:05 UTC by 4R9UN

using "ipv4_is_private()" operator to identify the private IP, reduced noise from loopback IP

   Required items, please complete
   
   Change(s):
    Update Potential_IIS_CodeInject.yaml
     using "ipv4_is_private()" operator to identify the private IP, exclude loopback IP . 
  
   Reason for Change(s):
   - generated FP results 

   Testing Completed:
   - yes

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2022-02-15 10:16 UTC, 4R9UN reviewed
done changes related to YAML

2022-02-16 11:32 UTC, aprakash13 reviewed
Thanks @4R9UN . The changes look great. Please remove the extra line in the end and this should be ready to be merged.

2022-02-16 15:55 UTC, 4R9UN reviewed
@aprakash13, removed the blank lines, ready for the merge.

2022-02-16 19:21 UTC, shainw commented
@4R9UN - Please add the entity mapping fields at the end for the query, same as we do for detections.  We are doing this to support future functionality.

2022-02-16 19:23 UTC, shainw requested changes

2022-02-16 19:23 UTC, shainw commented on Hunting Queries/W3CIISLog/Potential_IIS_CodeInject.yaml
> +  |where cIP != "::1"
Please add a space in front of the where clause here to align with standards.

2022-03-09 12:52 UTC, aprakash13 commented
> @4R9UN - Please add the entity mapping fields at the end for the query, same as we do for detections. We are doing this to support future functionality.

When you have some time @4R9UN please have a look at this suggestion. Thanks

2022-03-10 08:10 UTC, 4R9UN commented
Hi @aprakash13 , Thanks for the reminder, I added Entity mapping, kindly review the query and let me know if anything is missing.

2022-03-18 17:35 UTC, aprakash13 approved these changes
Thanks @4R9UN

2022-03-18 17:38 UTC, merged