Create ChiaCryptoMining_WindowsEvent
Azure/Azure-Sentinel pull request #4231
Opened 2022-02-21 14:46 UTC by yaelrbergman

Required items, please complete
   
   Change(s):
Added ChiaCryptoMining detection for WindowsEvent 
   
Reason for Change(s):
Adding WindowsEvent as a source

   Version Updated:
Yes
   Testing Completed:
Yes

   Checked that the validations are passing and have addressed any issues that are present:
Yes

2022-02-27 11:29 UTC, oshezaf requested changes

2022-02-27 11:29 UTC, oshezaf commented on Detections/WindowsEvent/ChiaCryptoMining_WindowsEvent.yaml
> +id: 4d173248-439b-4741-8b37-f63ad0c896ae
We use tags to refer to the original for code maintenance reasons. See [here](https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ASimWebSession/PossibleDGAContacts.yaml)

2022-02-27 11:29 UTC, oshezaf commented on Detections/WindowsEvent/ChiaCryptoMining_WindowsEvent.yaml
> +  let process = (iocs | where Type =~ "process" | project IoC);
No need to keep the lists you don't use.

2022-03-09 13:24 UTC, aprakash13 reviewed
@yaelrbergman Just wondering if we want a new query for this or do we want to include this in the existing ChiaCryptoMining detection.

2022-03-09 13:34 UTC, oshezaf commented
> @yaelrbergman Just wondering if we want a new query for this or do we want to include this in the existing ChiaCryptoMining detection.

@aprakash13 : as noted in another PR - Yael added a new version when the original was too long to add to.

2022-03-10 10:52 UTC, oshezaf approved these changes

2022-03-10 10:52 UTC, merged