Adding schemas to tester
Azure/Azure-Sentinel pull request #4234
Opened 2022-02-21 17:44 UTC by YaronFruchtmann

Required items, please complete
   
   Change(s):
   - Process Event
   - Registry Event
   - Some fields label changed Enum*a*rated to Enum*e*rated

2022-02-21 19:27 UTC, oshezaf requested changes

2022-02-21 19:27 UTC, oshezaf commented on ASIM/dev/ASimTester/ASimTester.csv
> +EventProduct,string,Mandatory,RegistryEvent,,,
For event product I do maintain a list as enumerated.

2022-02-21 19:27 UTC, oshezaf commented on ASIM/dev/ASimTester/ASimTester.csv
> +DvcIpAddr,string,Recommended,RegistryEvent,,,
You should the relevant Logical types (IP address, Hostname etc.) see the schemas I created or the data tester script.

2022-03-31 08:24 UTC, vmanojreddy commented
@YaronFruchtmann Please resolve conflicts. thanks!!!

2022-04-12 11:14 UTC, vmanojreddy commented
@YaronFruchtmann Please resolve conflicts. thanks!!!

2022-04-24 08:48 UTC, closed without merging