Hunting queries windows event batch3
Azure/Azure-Sentinel pull request #4243
Opened 2022-02-22 14:45 UTC by yaelrbergman

Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2022-02-27 09:23 UTC, oshezaf requested changes

2022-02-27 09:23 UTC, oshezaf commented on Hunting Queries/SecurityEvent/powershell_downloads.yaml
>    | where FileName in~ ("powershell.exe", "powershell_ise.exe","pwsh.exe")
Add those using "EventData has" above.

2022-03-08 07:42 UTC, vmanojreddy commented
@aprakash13  Please review hunting queries. thanks

2022-03-31 08:42 UTC, vmanojreddy commented
@yaelrbergman please update the requested changes ,thanks!!!

2022-04-06 11:49 UTC, vmanojreddy commented
@yaelrbergman please update the requested changes ,thanks!!!

2022-04-26 12:05 UTC, vmanojreddy commented
@oshezaf Can you please check and approve the changes. thanks!!!

2022-08-17 00:58 UTC, v-spadarthi commented
@oshezaf: Could you please check and approve the changes. thanks!!!

2022-09-07 10:02 UTC, v-mchatla commented
Hi @oshezaf
Can we close this and reopen whenever required as you have labelled it as differed.
Thanks

2022-09-07 10:44 UTC, closed without merging

2022-09-07 10:44 UTC, oshezaf commented
Done