iboss Sentinel Solution
Azure/Azure-Sentinel pull request #4324
Opened 2022-03-05 15:53 UTC by mvforgione

Required items, please complete
   
   Change(s):
   - Initial commits

   Reason for Change(s):
   - New iboss solution for Microsoft Sentinel

   Testing Completed:
   - Passed!  - Failed:     0, Passed:  1872, Skipped:     0, Total:  1872, Duration: 25 s - Kqlvalidations.Tests.dll (netcoreapp3.1)

2022-03-08 13:01 UTC, v-sabiraj requested changes

2022-03-08 13:01 UTC, v-sabiraj commented on Solutions/iboss/Data Connectors/iboss_cef.json
> +    "id": "Unique Identifier (GUID) used to identify dependencies and content from solutions or community.",
@mvforgione , please add Unique Identifier (GUID), thanks.

2022-03-10 12:41 UTC, v-sabiraj commented
Hey @oshezaf , will please once have look for the parser , thanks.

2022-03-10 13:00 UTC, oshezaf reviewed
General: I cannot validate the parser itself. This requires a testing environment, understanding of the source and the logs. While I provided some general comments, to ensure quality, parsers, like any code, need to be reviewed by someone who is part of the project team.

2022-03-10 13:00 UTC, oshezaf commented on Solutions/iboss/Parsers/ibossUrlEvent.txt
> +| project-away DeviceCustomNumber1Label
A style not project-away accepts wilecards, so this command can be shortened to project-away DeviceCustom*, Flex*

2022-03-10 14:24 UTC, mvforgione commented on Solutions/iboss/Workbooks/Images/Logo/iboss_full-logo_2020_vector_white.svg
> +<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" x="0" y="0" viewBox="0 0 499.986 144.457" style="enable-background:new 0 0 499.98557 144.45694" xml:space="preserve"><style>.st1{fil
@v-sabiraj thank you for the assistance on the images. I checked the guidelines and was not able to find the restrictions/rules for these. I'll work with our graphics team to have these updated ASAP.

2022-03-10 14:27 UTC, mvforgione commented on Solutions/iboss/Parsers/ibossUrlEvent.txt
> +// This function maps iboss URL events to Azure Sentinel Information Model (ASIM) (https://docs.microsoft.com/azure/sentinel/normalization).
@oshezaf thank you for the detailed review. I patterned the parser from other solutions present in the Solutions directory of the repo, so I apologize the wording here. Does Microsoft prefer that ASIM parsers be used for solutions or is it really up to the developer to determine what is the best fit for their data?

2022-03-10 14:38 UTC, oshezaf commented on Solutions/iboss/Parsers/ibossUrlEvent.txt
> +// This function maps iboss URL events to Azure Sentinel Information Model (ASIM) (https://docs.microsoft.com/azure/sentinel/normalization).
Our goal is certainly to have ASIM parsers in solutions. It significantly increases the value customers get from your solution as it enables your solution to use alot of the Sentinel built-in capabilities. It does take more effort in creating the parser.

Today, most if not all solutions do not support ASIM, and ASIM parsers are delivered as part of the ASIM project.

Now, sticking to ASIM field names does help users, even if it does not provide the full ASIM value, so overall it is a good choice.

2022-03-11 12:11 UTC, v-sabiraj commented
Hey @mvforgione , the workbook query is failing, please check and update, thanks.
![image](https://user-images.githubusercontent.com/94349919/157864595-6c197ee6-027b-47c5-af69-b4a8e0f3a383.png)

2022-03-15 13:53 UTC, mvforgione commented on Solutions/iboss/Parsers/ibossUrlEvent.txt
> +// This function maps iboss URL events to Azure Sentinel Information Model (ASIM) (https://docs.microsoft.com/azure/sentinel/normalization).
Thank you for the feedback here. I have removed the wording in the interim as I explore creating an ARM template. I attempted to map all appropriate fields to the ASIM schema and I successfully ran the schema validator (`ibossUrlEvent | getschema | invoke ASimSchemaTester('<schema>')`), so I believe we are getting closer to that particular target.

2022-03-15 16:08 UTC, mvforgione commented on Solutions/iboss/Workbooks/Images/Logo/iboss_full-logo_2020_vector_black.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 499.986 144.457" style="enable-background:new 0 0 499.98557 144.45694" xml:space="preserve"><switch><g><path d="M493.63 18.961c0 5.58-4.38 9.96-10
@v-sabiraj I understand the logos still have illegal attributes. I'm taking this back to our design team to provide new. Please standby.

2022-03-17 13:25 UTC, v-sabiraj approved these changes

2022-03-22 01:39 UTC, merged