Update Table Names
Azure/Azure-Sentinel pull request #4338
Opened 2022-03-08 06:42 UTC by ThijsLecomte

Required items, please complete
   
   Change(s):
   - Updated table names for entire solution

   Reason for Change(s):
   - Table Name change was required for other PR #4244

   Version Updated:
   - /

   Testing Completed:
   - OK

   Checked that the validations are passing and have addressed any issues that are present:
   - OK

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2022-03-08 09:35 UTC, v-sabiraj requested changes

2022-03-08 09:35 UTC, v-sabiraj commented on Solutions/LastPass/Analytic Rules/HighlySensitivePasswordAccessed.yaml
>    | extend timestamp = , AccountCustomEntity = Username_s, IPCustomEntity = IP_Address_s, URLCustomEntity = Data_s
Hey @ThijsLecomte , there is error in query for **timestamp= ,** as it is blank, please check and update, thanks.

2022-03-08 14:57 UTC, ThijsLecomte commented
@v-sabiraj now it fails because this was excluded from validation as it used a Watchlist.
Can you confirm the validations now support watchlists?

2022-03-09 14:03 UTC, v-rucdu approved these changes

2022-03-09 14:03 UTC, merged