Create Detection for Password Spray against ADFSSignInLogs
Azure/Azure-Sentinel pull request #4349
Opened 2022-03-08 22:17 UTC by ep3p

Change(s):
   - A detection for ADFSSignInLogs.

   Version Updated:
   - Does not apply

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

-----------------------------------------------------------------------------------------------------------
Feel free to change query frequency/period.

Please, could you check other scenarios where this detection might be a false positive? (for example depending on Authentication Details)

2022-03-09 11:55 UTC, ep3p commented
I have observed that ADFSSignInLogs might not arrive instantaneously, and thus possible alerts might be lost. So the query should wait a bit for the logs to arrive, and maybe the queryfrequency should be increased.

2022-03-30 08:54 UTC, ep3p commented
Substituted the query_wait by ingestion_time()

2022-04-01 08:21 UTC, vmanojreddy commented
@aprakash13 Please review Detections. Thanks.

2022-04-22 05:57 UTC, aprakash13 requested changes
Thanks for all your contributions @ep3p. Can you please fix the validation issues before we can merge these? Also, a couple of very minor things to look at.

2022-04-22 05:57 UTC, aprakash13 commented on Detections/SigninLogs/ADFSSignInLogsPasswordSpray.yaml
> +
Please remove the additional line. Not needed.

2022-04-22 05:57 UTC, aprakash13 commented on Detections/SigninLogs/ADFSSignInLogsPasswordSpray.yaml
> +
Please remove the additional line. Not needed.

2022-04-22 06:32 UTC, ep3p commented
> Thanks for all your contributions @ep3p. Can you please fix the validation issues before we can merge these? Also, a couple of very minor things to look at.

@aprakash13 sorry I don't know yet how to fix this, ADFSSignInLogs is not being recognized as a valid table by KQL Validations yet. I guess somewhere in this repo "ADFSSignInLogs" string could be added a valid parameter for Analytic Rules templates, but I don't know where exactly, could you guide me if you want me to mess with that?

https://dev.azure.com/azure/Azure-Sentinel/_build/results?buildId=40174&view=logs&j=2bbe2297-1b5b-54f3-6060-67e7b289f6c3&t=293f4a23-e36d-5efa-3a4e-ea46d4ab6d83&l=27

2022-04-22 08:52 UTC, ep3p commented
@aprakash13 I have opened a PR for the custom table for KQL validation for ADFSSignInLogs

https://github.com/Azure/Azure-Sentinel/pull/4700

2022-04-22 14:33 UTC, aprakash13 commented
> @aprakash13 I have opened a PR for the custom table for KQL validation for ADFSSignInLogs
> 
> #4700

Thanks @ep3p . Once the Custom tables in https://github.com/Azure/Azure-Sentinel/pull/4700 gets merged. We can move forward with this.

2022-05-11 12:13 UTC, aprakash13 approved these changes
Thanks @ep3p for all your contributions.

2022-05-11 12:13 UTC, merged