Created NRT_PrivlegedRoleAssignedOutsidePIM.yaml
Azure/Azure-Sentinel pull request #4545
Opened 2022-03-31 15:15 UTC by samikroy

Required items, please complete
   
   Change(s):
   - Created NRT_PrivlegedRoleAssignedOutsidePIM.yaml

   Reason for Change(s):
   - New NRT rule addition.

   Version Updated:
   - Initial Version

   Testing Completed:
   - Yes

2022-04-05 12:44 UTC, samikroy commented
@aprakash13  - Please let me know for any updates needed to this rule.

2022-04-19 13:24 UTC, vmanojreddy commented
@aprakash13  Please review and provide your feedback. thanks!!!

2022-04-22 12:59 UTC, aprakash13 requested changes
Small change suggested. Please modify.

2022-04-22 12:59 UTC, aprakash13 commented on Detections/AuditLogs/NRT_PrivlegedRoleAssignedOutsidePIM.yaml
> +  - PrivilegeEscalation
Please add the relevantTechniques

2022-04-22 13:56 UTC, aprakash13 approved these changes
Thanks @samikroy for all your contributions.

2022-04-22 13:57 UTC, merged

2022-04-22 14:19 UTC, samikroy commented
Thank you for the approval & merge @aprakash13 .