VMWare analytic rules update
Azure/Azure-Sentinel pull request #4591
Opened 2022-04-07 12:12 UTC by spsocprime

Required items, please complete
   
   Change(s):
   - Analytic rules update:
        ESXiRootLogin.yaml
        ESXiSharedOrStolenRootAccount

   Reason for Change(s):
   - Create high severity rules

   Version Updated:
   - yes

   Testing Completed:
   - yes

   Checked that the validations are passing and have addressed any issues that are present:
   - yes

2022-04-07 12:22 UTC, spsocprime commented
Unexpected errors during running checks
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/94110440/162197450-c7586e1b-5ada-4414-86e2-8bd0e9a0a082.png">

2022-04-07 12:22 UTC, spsocprime commented
Unexpected errors during running checks
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/94110440/162197450-c7586e1b-5ada-4414-86e2-8bd0e9a0a082.png">

2022-04-11 22:22 UTC, aprakash13 requested changes
Thanks. Made one small suggestion. Please take a look.

2022-04-11 22:22 UTC, aprakash13 commented on Solutions/VMWareESXi/Analytic Rules/ESXiRootLogin.yaml
> +  | where SrcIpAddr in (root_ips)
Wondering, since we are doing login from uncommon IP address should we not be doing '!in' instead of 'in' here

2022-04-13 05:56 UTC, aprakash13 approved these changes
Thanks.

2022-04-29 10:52 UTC, aprakash13 commented
@v-sabiraj : This looks good from a query perspective and I have already approved this. Since this is part of a solution and not a simple detection/hunting query, I will let the CAT team merge this. Thanks.

2022-05-06 04:30 UTC, merged