Update azuredeploy.json
Azure/Azure-Sentinel pull request #4662
Opened 2022-04-17 04:44 UTC by AcceleryntSecurityDev

Change(s):
- updated sensitive parameters to secure string

   Reason for Change(s):
   - security improvement

   Version Updated:
   - No

   Testing Completed:
   - No

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

2022-04-19 00:06 UTC, sreedharande commented on Playbooks/AS_Alert_Spiderfoot_Scan/azuredeploy.json
> +            "defaultValue": "",
@AcceleryntSecurityDev - Delete "Default Value" to make it Required Column

2022-04-19 00:08 UTC, sreedharande requested changes
@AcceleryntSecurityDev - Delete "defaultValue" to make it Required Column, as API key is required value for the Playbook

2022-04-25 18:21 UTC, sreedharande requested changes
@AcceleryntSecurityDev - SpiderfootURL - make it required by removing defaultValue. Add "metadata": {
            "description": ""
        } that doesn't have default value

2022-04-29 01:07 UTC, AcceleryntSecurityDev commented
@sreedharande I am unable to re-request review on this PR for some reason, please review when you get a chance

2022-04-29 23:44 UTC, sreedharande approved these changes

2022-04-29 23:45 UTC, merged