New Detection - KrbRelayUp Tool
Azure/Azure-Sentinel pull request #4883
Opened 2022-05-11 12:03 UTC by BlackB0lt

Required items, please complete

Change(s):

Create New rule to detect service creation from KrbRelayUp tool
Reason for Change(s):

New rule to detect service creation from KrbRelayUp tool
Version Updated: 1.0

Required only for Detections/Analytic Rule templates
Testing Completed:

Tested on event with sigma rule
Checked that the validations are passing and have addressed any issues that are present:

See guidance below
References: https://github.com/Dec0ne/KrbRelayUp

   Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2022-05-11 12:54 UTC, aprakash13 requested changes
Please take a quick look at the suggested changes.

2022-05-11 12:54 UTC, aprakash13 commented on Hunting Queries/SecurityEvent/KrbRelayUpServiceCreation
> +  | where ServiceName has_any (MaliciousServiceArtifacts) or ImagePath has_any (MaliciousServiceArtifacts)
Seems like we should have MaliciousService vs  MaliciousServiceArtifacts in here.

2022-05-26 09:09 UTC, BlackB0lt commented
This detection is related with this article.

https://www.microsoft.com/security/blog/2022/05/25/detecting-and-preventing-privilege-escalation-attacks-leveraging-kerberos-relaying-krbrelayup/

2022-06-10 20:13 UTC, aprakash13 approved these changes
Thanks @BlackB0lt

2022-06-10 20:13 UTC, merged