Symantec Integrated Cyber Defense TemplateSpec Solution
Azure/Azure-Sentinel pull request #4911
Opened 2022-05-12 12:37 UTC by v-atulyadav

As I have seen comma separated publisher Id's so not changing publisher id only Offer Id changed

![image](https://user-images.githubusercontent.com/104008048/168076238-197852ff-3b4b-4fe5-82a8-c7a75a3925de.png)

2022-05-13 12:28 UTC, mkchiliveri requested changes
SolutionMetadata.json contains "publisherId": "publisherId_test", we need to update this with correct value.

2022-06-28 11:26 UTC, NikTripathi approved these changes

2022-06-29 09:25 UTC, v-sabiraj submitted a review, later dismissed

2022-06-29 12:14 UTC, NikTripathi approved these changes

2022-06-29 12:41 UTC, v-sabiraj approved these changes

2022-06-29 12:42 UTC, merged