[Microsoft Sentinel Hackathon Spring 2022] Manage secure multi cloud environment with Sentinel
Azure/Azure-Sentinel pull request #4944
Opened 2022-05-16 16:42 UTC by tungnt77

Building and utilizing multi cloud environment nowadays is the best choice for most of organization and enterprise when they start their cloud journey. Therefore, in day-to-day work of a Microsoft Sentinel Consulting team, we are often challenged by clients about how to leverage Sentinel as a good-to-go solution for managing the security events in their multi cloud environment, especially AWS and Azure. So when we started this hackathon, we want to solve this problem completely but in a "cloud native" way.

When we looked up existing applications on Sentinel marketplace for connecting Sentinel to AWS environment and AWS security specific services (Security Hub, Inspector) we found that they have some limited

Common integration is using API, causing many issues when running into high load production environment.
S3 integration is new upgrade but it is still in preview and support a little of services: VPC Flow Logs, GuardDuty and CloudTrail.
All of these problems inspired us to building an end-to-end security solution to leverage Microsoft Sentinel as a core component for a secure multi cloud environment. We want to use Sentinel to collect security findings in some AWS security services by using S3 bucket for log integration that we call an AWS native approach.

2022-05-31 06:46 UTC, v-sabiraj commented
Hey @tungnt77 , can you please add the sample data, for the tables mentioned i.e Macie_CL and AWS_Inspector_CL  thanks.

2022-05-31 07:39 UTC, v-sabiraj requested changes

2022-05-31 07:39 UTC, v-sabiraj commented on Solutions/AWS/Data Connectors/azuredeploy_AWSConnector_API_FunctionApp.json
> +{
Hey @tungnt77, Please check the [template  ](https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/DataConnectors/Templates/Connector_REST_API_AzureFunctionApp_template/azuredeploy_DataConnector_API_AzureFunctionApp_template.json) and update azuredeploy file format accordingly.

2022-05-31 07:39 UTC, v-sabiraj commented on Solutions/AWS/Data Connectors/Connector_AWSInspectorAndMacie.json
> +        "id": "Unique Identifier (GUID) used to identify dependencies and content from solutions or community.",
Hey @tungnt77, please update the id with proper GUID value, thanks.

2022-05-31 07:39 UTC, v-sabiraj commented on Solutions/AWS/Data Connectors/Connector_AWSInspectorAndMacie.json
> +            "kind": "source type of the content. Value must be one of these : localWorkspace | community | solution | sourceRepository",
@tungnt77, please add the source details (value for kind and name), thanks.

2022-05-31 07:53 UTC, v-sabiraj commented
Hi @tungnt77, please add the zip file for data connector, and also check the folder structure for data connector, you can refer [sample connector](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Box/Data%20Connectors), just for the refence, thanks.

2022-06-13 15:25 UTC, v-sabiraj commented
Hey @tungnt77, please resolve the requested changes, thanks.

2022-06-23 09:31 UTC, v-spadarthi commented
@tungnt77, please resolve the requested changes and validation checks as well, thanks.

2022-06-30 04:33 UTC, aprakash13 requested changes
Please fix the validation issues before this can be approved.

The Solution uses custom tables like AWS_Inspector_CL and Macie_CL. We probably need to define this in the custom table. Please see an example here: https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/KqlvalidationsTests/CustomTables/AWSGuardDuty.json

Please also include the **entityMappings** and **kind** fields for the analytic templates

2022-07-06 07:04 UTC, vmanojreddy commented
@tungnt77 Please address the above comments. thanks!!!

2022-07-22 10:22 UTC, v-sabiraj commented
@tungnt77 , please update the requested changes. Thanks.

2022-07-27 10:58 UTC, v-spadarthi commented
@tungnt77, please address the requested changes and validation checks as well, thanks.

2022-08-03 08:49 UTC, v-spadarthi commented
@tungnt77, please address the requested changes and validation checks as well, thanks.

2022-08-03 09:15 UTC, pemontto commented
@v-spadarthi @v-sabiraj @v-marimanda 
Seems like shouting into a void, would Microsoft consider just taking on the remaining tasks to get some much needed additional functionality into Sentinel?

2022-09-02 06:29 UTC, v-marimanda commented
Hi @tungnt77,
We wanted to check on the status of PR [4944](https://github.com/Azure/Azure-Sentinel/pull/4944). PR is pending from long time. Let us know if any assistance is required for this PR. Per our standard operating procedures if no response is received in the next 7 business days we will close this PR. Thank you for your cooperation.

2022-09-08 20:13 UTC, NikTripathi commented
@tungnt77 Can you please provide some update. @v-marimanda Please do the needful.

2022-09-12 07:48 UTC, v-marimanda commented
Hi @tungnt77,
Since we have not received response from last 10 days, we are closing your PR #4944 per our standard operating procedures. If you still need support for this PR you can re-open the PR at any time.
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

2022-09-22 15:36 UTC, v-mchatla commented
Hi @v-sabiraj,
Can you please provide update on this PR
Thanks

2022-09-27 14:42 UTC, v-mchatla commented
Hi @v-sabiraj 
Can you please provide update on this.
Thanks

2022-09-30 05:24 UTC, v-sabiraj commented
Hi, need to work on this, let you know once done.

2022-10-04 18:45 UTC, v-mchatla commented
Hi @v-sabiraj,
Please provide an update on the progress once you started working on it.
Thanks

2022-10-07 04:49 UTC, v-sabiraj commented
Hi, will start working on this soon.

2022-10-11 06:22 UTC, v-spadarthi commented
Hi @v-sabiraj,
Please provide an update on the progress once you started working on it.
Thanks

2022-10-13 06:43 UTC, v-sabiraj commented
Closing this for now, will reopen once we start working.

2022-10-13 06:43 UTC, closed without merging