[Hunting] Entity map update
Azure/Azure-Sentinel pull request #5038
Opened 2022-05-20 22:27 UTC by shainw

Change(s):
   - Adding additional entity outputs
   - Fixed some incorrect connector names
   - adjusted some queries timeframes to provide better results
   - fixed some spacing issues

   Reason for Change(s):
   - as needed by other tooling
   - to support future automap of entities similar to Detections

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Will check

2022-05-20 23:24 UTC, ashwin-patil requested changes
required changes based on couple of comments , rest looks good.

2022-05-20 23:24 UTC, ashwin-patil commented on Hunting Queries/SigninLogs/SpikeInFailedSignInAttempts.yaml
> +      - identifier: AadUserId
identifier should be FullName instead of AadUserId based on ColumnName: UserPrincipalName

2022-05-20 23:24 UTC, ashwin-patil commented on Hunting Queries/BehaviorAnalytics/Anomalous AAD Account Manipulation.yaml
> +        columnName: UserPrincipalNam
Typo - UserPrincipalName in multiple files in this PR

2022-05-21 02:02 UTC, aprakash13 submitted a review, later dismissed
++ It seems there are about 15 queries where we might have to rectify a typo related to UserPrincipalName. It can be quickly searched by looking for below string.
columnName: UserPrincipalNam

++ For the DNS related queries not sure if IpAddress is a supported identifier for DNS Entity. DomainName seems to be only one visible in the console with **+Add Identifier** button greyed out.
![image](https://user-images.githubusercontent.com/37783395/169630124-180afa04-58be-4144-8fce-a7814c8a6f31.png)

2022-05-21 14:58 UTC, shainw commented on Hunting Queries/W3CIISLog/RareClientFileAccess.yaml
> +  - entityType: CloudLogonSession
Yeah, it is not exposed yet, but it doesn't hurt us to keep it in.

2022-05-21 15:01 UTC, shainw commented on Hunting Queries/BehaviorAnalytics/Anomalous AAD Account Manipulation.yaml
> + '7be44c8a-adaf-4e2a-84d6-ab2649e08a13','e8611ab8-c189-46e8-94e1-60213ab1f814']);
I am not sure I am clear; this is a tabular expression not a list of expressions.  You wouldn't quote them.

2022-05-21 15:04 UTC, shainw commented on Hunting Queries/W3CIISLog/RareClientFileAccess.yaml
> +  - entityType: CloudLogonSession
On the DNS one, again this is fine, it does not hurt us to keep it in.

2022-05-23 17:42 UTC, ashwin-patil approved these changes

2022-05-23 17:44 UTC, merged