The Hive playbooks
Azure/Azure-Sentinel pull request #5083
Opened 2022-05-24 13:54 UTC by vu-socprime

Added The Hive Custom API Logic App Connector and 3 playbooks

2022-05-27 08:51 UTC, vu-socprime commented on Solutions/TheHive/Playbooks/azuredeploy.json
> +                        "Value": "[parameters('onPremiseGatewayName')]"
On Premise Data gateway should be deployed under the same subscription and resource group as playbooks. Nevertheless it is not necessary to provide valid onPremiseGateway name during the deployment. Playbooks will be deployed in any case. Link to the gateway can be changed later during configuring API connections.

2022-06-24 08:29 UTC, v-spadarthi commented
@rushriva : Please provide your comments

2022-07-27 06:24 UTC, v-spadarthi commented
@rushriva : Could you please review the playbooks. Thanks!

2022-08-03 15:09 UTC, ospeka commented on Solutions/TheHive/Playbooks/azuredeploy.json
> +                        "Value": "[parameters('onPremiseGatewayName')]"
You need to have valid On-Premises Data Gateway under the same subscription and resource group for deploy. The gateway must at least exist for deploy. Please, try again and if it fails ping me or vu-socprime.

2022-08-08 06:13 UTC, anki-narravula requested changes
Hi @vu-socprime - Can you please make following changes. Thanks in advance

1. For all playbooks, metadata object is missing. With the new template spec (for gallery), this is mandatory. Please look at the [ latest guide for playbooks contribution](https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide)
2. For all playbooks custom connector name must be included in the Parameters and use the parameter directly in "id" attribute of API. For example 
```
 "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', variables('customApis_vendorproduct_name'))]"
 "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', parameter('customApis_rapid7'))]"
```
3. In Custom Connector - name of the custom connector must be a parameter and keep default value (same as the current) also we suggest making host url also as parameter
4. Wherever sentinel connection used, use Managed Identity always - [refer template for an example ](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json)
5. Please consider limited actions for Custom connector actions (whatever relevant or closer to SOAR perspective). Also please describe in readme (if it is missing)
6. (If not implemented) Make sure playbook should not fail in case of API does not find entity / specified identity. Rather it should write in Sentinel comment that "Unable to find ......., hence no action taken) 
7. Make sure images are loading in readme files

2022-08-12 08:09 UTC, vu-socprime commented
> Hi @vu-socprime - Can you please make following changes. Thanks in advance
> 
> 1. For all playbooks, metadata object is missing. With the new template spec (for gallery), this is mandatory. Please look at the [ latest guide for playbooks contribution](https://github.com/Azure/Azure-Sentinel/tree/master/docs/New%20Playbooks%20Contribution%20Guide)
> 2. For all playbooks custom connector name must be included in the Parameters and use the parameter directly in "id" attribute of API. For example
> 
> ```
>  "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', variables('customApis_vendorproduct_name'))]"
>  "id": "[concat('/subscriptions/', subscription().subscriptionId, '/resourceGroups/', resourceGroup().name, '/providers/Microsoft.Web/customApis/', parameter('customApis_rapid7'))]"
> ```
> 
>  3. In Custom Connector - name of the custom connector must be a parameter and keep default value (same as the current) also we suggest making host url also as parameter
> 4. Wherever sentinel connection used, use Managed Identity always - [refer template for an example ](https://github.com/Azure/Azure-Sentinel/blob/master/Playbooks/.template/incident-trigger/azuredeploy.json)
> 5. Please consider limited actions for Custom connector actions (whatever relevant or closer to SOAR perspective). Also please describe in readme (if it is missing)
> 6. (If not implemented) Make sure playbook should not fail in case of API does not find entity / specified identity. Rather it should write in Sentinel comment that "Unable to find ......., hence no action taken)
> 7. Make sure images are loading in readme files

Hi @anki-narravula 
The playbooks were updated according to the feedback

2022-08-22 06:15 UTC, anki-narravula requested changes
Hi @vu-socprime  - We are good now. Can you please change the azure deploy links to point to master now. Also please see the readme file of TheHive-CreateCase, screenshot is not loading

2022-08-23 14:56 UTC, vu-socprime commented
> Hi @vu-socprime - We are good now. Can you please change the azure deploy links to point to master now. Also please see the readme file of TheHive-CreateCase, screenshot is not loading

Hi @anki-narravula - Screenshot loading fixed. Links already point to master.

2022-08-24 05:45 UTC, anki-narravula commented
> > Hi @vu-socprime - We are good now. Can you please change the azure deploy links to point to master now. Also please see the readme file of TheHive-CreateCase, screenshot is not loading
> 
> Hi @anki-narravula - Screenshot loading fixed. Links already point to master.

Hi @vu-socprime  - I am somehow seeing that it is referencing to socprime branch. Below is the screenshot attached
![image](https://user-images.githubusercontent.com/10404181/186339845-9c6f057e-f080-4abe-a8e5-7e4b86f5e35b.png)

2022-08-24 14:27 UTC, vu-socprime commented
> > > Hi @vu-socprime - We are good now. Can you please change the azure deploy links to point to master now. Also please see the readme file of TheHive-CreateCase, screenshot is not loading
> > 
> > 
> > Hi @anki-narravula - Screenshot loading fixed. Links already point to master.
> 
> Hi @vu-socprime - I am somehow seeing that it is referencing to socprime branch. Below is the screenshot attached ![image](https://user-images.githubusercontent.com/10404181/186339845-9c6f057e-f080-4abe-a8e5-7e4b86f5e35b.png)

@anki-narravula - Fixed

2022-08-26 10:12 UTC, anki-narravula approved these changes
Looks good. Approved.

2022-08-26 10:12 UTC, merged