Auth0 data connector
Azure/Azure-Sentinel pull request #5454
Opened 2022-06-24 14:44 UTC by ospeka

Change(s):
   - Added Auth0 function app data connector

2022-06-27 04:38 UTC, v-sabiraj commented
Hey @ospeka, please sign the CLA, thanks.

2022-06-27 20:34 UTC, ospeka commented on Solutions/Auth0/Data Connectors/Auth0_FunctionApp.json
> +	]
added

2022-06-27 21:12 UTC, ospeka commented on Parsers/Auth0/Auth0.txt
> +    HttpRequestMethod = details_request_method_s,
Unfortunately, I don't have access to Auth0AM but have a git parsed sample of response. Hope it will be enough.

2022-07-01 11:39 UTC, v-sabiraj submitted a review, later dismissed

2022-07-01 11:39 UTC, v-sabiraj commented on Solutions/Auth0/Data Connectors/Logo/Auth0.svg
> +    </path>
@ospeka, please make the code inline. Thanks.

2022-07-01 11:39 UTC, v-sabiraj commented on Sample Data/Custom/Auth0AM_CL.json
> +      "details_response_statusCode": "201",
@ospeka, as the value of "details_response_statusCode" is given with "" it is saved as string, please check and update, thanks.

2022-07-01 11:39 UTC, v-sabiraj commented on Solutions/Auth0/Parsers/Auth0.txt
> +    Dst = details_request_body_audience_s
@ospeka, please add " , " (comma) at end of this line, thanks.

2022-07-01 12:25 UTC, v-sabiraj commented
@ospeka, same parser is added at both places in parser folder as well as in solution folder, the parser file from standalone folder can be removed, thanks.

2022-08-04 16:13 UTC, v-spadarthi commented
@ospeka : Please resolve the below comments
Sample data ingestion done and working fine 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/101796244/182883179-76b62fbe-43e3-474a-8bca-68a5ed650fc8.png">
Logo is validated 
Parser is looking good
<img width="797" alt="image" src="https://user-images.githubusercontent.com/101796244/182884612-82800d22-935f-44ae-855c-6c64d650d946.png">
Dataconnector function app is not working please fix
<img width="809" alt="image" src="https://user-images.githubusercontent.com/101796244/182893827-d29d8370-73f1-4912-88ad-cd50e9156786.png">

2022-08-10 10:44 UTC, v-spadarthi requested changes

2022-08-10 10:44 UTC, v-spadarthi commented on Solutions/Auth0/Data Connectors/Auth0_FunctionApp.json
> +            "link":"https://github.com/Azure/Azure-Sentinel/issues"
@ospeka : Could you please change link ? current link points to github issues it seems to be incorrect

2022-08-10 10:44 UTC, v-spadarthi commented on Solutions/Auth0/Data Connectors/Auth0_FunctionApp.json
> +			"description": "Use this method for automated deployment of the Auth0 Access Management data connector using an ARM Tempate.\n\n1. Click the **Deploy to Azure** button below. \n\n\t[![Deploy To Az
@ospeka :Could you please correct the typo for "Tempate".

2022-08-10 10:44 UTC, v-spadarthi commented on Solutions/Auth0/Data Connectors/Auth0_FunctionApp.json
> +			"description": ">**NOTE:** This connector uses Azure Functions to connect to the Auth0 Management APIs to pull its logs into Azure Sentinel. This might result in additional data ingestion costs. C
@ospeka : Please replace "Azure Sentinel" to Microsoft Sentinel" where ever it's applicable.

2022-08-16 06:28 UTC, v-spadarthi approved these changes

2022-08-16 07:10 UTC, NikTripathi approved these changes

2022-08-16 07:11 UTC, merged