Azure AD playbook preparation
Azure/Azure-Sentinel pull request #5606
Opened 2022-07-13 07:51 UTC by v-sabiraj

Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2022-07-27 14:03 UTC, v-rucdu requested changes

2022-07-27 14:03 UTC, v-rucdu commented on Playbooks/Block-AADUser/alert-trigger/azuredeploy.json
> +        "lastUpdateTime": "2022-07-11T00:00:00.000Z",
@v-sabiraj : we should add this prop with default value as current date only if it does not exist, please revert this date change

2022-07-28 06:30 UTC, v-sabiraj commented on Playbooks/Block-AADUser/alert-trigger/azuredeploy.json
> +        "prerequisites": [""],
@v-rucdu, I have modified the value of prerequisites to  "prerequisites": ["None"],

2022-07-29 13:41 UTC, v-rucdu commented
@v-sabiraj : Please move all the playbook files to solutions --> Playbooks folder... rest looks good to me... Thanks!!

2022-07-30 04:54 UTC, merged