Add ReversingLabs logo
Azure/Azure-Sentinel pull request #5671
Opened 2022-07-20 19:20 UTC by AaronHoffmannRL

Required items, please complete
   
   Change(s):
   - Adds the ReversingLabs logo SVG file

   Reason for Change(s):
   - Prep for solution updates

   Version Updated:
   - N/A

   Testing Completed:
   - N/A

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

2022-07-21 11:27 UTC, v-sabiraj requested changes

2022-07-21 11:27 UTC, v-sabiraj commented on Logos/reversinglabs.svg
> +<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
@AaronHoffmannRL, Id should be some unique value, please update, thanks.

2022-07-21 11:27 UTC, v-sabiraj commented on Logos/reversinglabs.svg
> +<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
@AaronHoffmannRL, logo file should not contain illegal attributes: data-name, style, xmlns:link

2022-07-21 15:05 UTC, AaronHoffmannRL commented
@v-sabiraj requested changes have been made

2022-07-22 10:20 UTC, v-sabiraj approved these changes

2022-07-22 12:09 UTC, NikTripathi approved these changes

2022-07-22 12:09 UTC, merged