Create ShadowCopyDeletion.yml
Azure/Azure-Sentinel pull request #6116
Opened 2022-09-07 19:02 UTC by Bert-JanP

Required items, please complete
   
   Change(s):
   - Added new Hunting query

   Reason for Change(s):
   - Addition to the current query pack

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - No

2022-09-08 01:42 UTC, v-spadarthi commented
@aprakash13 : Please Review the Hunting queries and provide your comments. Thanks!!

2022-09-08 18:59 UTC, NikTripathi commented
@aprakash13 please have a look.

2022-09-11 15:14 UTC, shainw requested changes

2022-09-11 15:14 UTC, shainw commented on Hunting Queries/Microsoft 365 Defender/Ransomware/ShadowCopyDeletion.yml
> +  | project-reorder Timestamp, ProcessCommandLine, DeviceName, AccountName
@Bert-JanP  -  Please change Timestamp to standard time column of TimeGenerated.  They are equal, but TimeGenerated is the standard.

2022-09-11 16:01 UTC, shainw approved these changes

2022-09-11 16:01 UTC, shainw commented on Hunting Queries/Microsoft 365 Defender/Ransomware/ShadowCopyDeletion.yml
> +  | project-reorder Timestamp, ProcessCommandLine, DeviceName, AccountName
@Bert-JanP - Nevermind, missed this was in M365 Hunting folder, Timestamp is good here.

2022-09-11 16:01 UTC, merged