Update ReversingLabs solution
Azure/Azure-Sentinel pull request #6144
Opened 2022-09-12 20:01 UTC by AaronHoffmannRL

Required items, please complete
   
   Change(s):
   - This PR re-introduces the ReversingLabs Sentinel solution
   - Adds 1 new playbook to replace the previous playbook
   - Adds 1 new workbook

   Reason for Change(s):
   - Updating solution to better fit capabilities

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

2022-09-13 12:46 UTC, v-marimanda requested changes

2022-09-13 12:46 UTC, v-marimanda commented on Solutions/ReversingLabs/Data/Solution_ReversingLabs.json
> +  "TemplateSpec": false
@AaronHoffmannRL  can please change  TemplateSpec value  true and please add one more property "Is1Pconnector": false.

2022-09-13 12:46 UTC, v-marimanda commented on Solutions/ReversingLabs/Data/Solution_ReversingLabs.json
> +  "Version": "1.0.0",
@AaronHoffmannRL Please update the version 2.0.0.thanks!!

2022-09-13 12:49 UTC, v-marimanda commented
@AaronHoffmannRL Please update package with above changes as well. thanks!!!

2022-09-13 12:49 UTC, v-marimanda commented
@rushriva  and @devikamehra  Please review the playbook provide your sign off. thanks!!!

2022-09-13 12:52 UTC, v-marimanda commented
Workbook is looking good. 
![image](https://user-images.githubusercontent.com/90677907/189905781-de01e0de-abc2-4576-b06a-6162eb4f3fc4.png)

2022-09-13 14:14 UTC, AaronHoffmannRL commented
@v-marimanda requested changes to Solution_ReversingLabs.json have been completed

2022-09-14 05:59 UTC, v-marimanda commented
@AaronHoffmannRL  Please update package with v2 tool. thanks!!!
Tool reference path : https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2

2022-09-14 06:04 UTC, v-marimanda commented
@AaronHoffmannRL Please don't delete old zip files from package folder. thanks!!!

2022-09-16 05:06 UTC, v-marimanda commented
@rushriva  and @devikamehra  Please review the playbook provide your sign off. thanks!!!

2022-09-19 06:36 UTC, v-marimanda commented
@rushriva and @devikamehra Please review the playbook provide your sign off. thanks!!!

2022-09-19 17:02 UTC, AaronHoffmannRL commented
@v-marimanda I've re-packaged the solution with the V2 script and added the old ZIP archives back to the folder

2022-09-20 07:06 UTC, v-marimanda commented
@manishkumar1991  Please review the playbook provide your sign off. thanks!!!

2022-09-22 03:01 UTC, v-marimanda commented
@rahul0216  and @manishkumar1991  Please review the playbook provide your sign off. thanks!!!

2022-09-26 06:42 UTC, manishkumar1991 approved these changes
All changes Looks good , 
Createuidefinition file and maintemplate files are also giving successful results

2022-09-28 06:08 UTC, v-atulyadav commented
Hi @manishkumar1991 , can you please merge this PR. Thanks.

2022-09-30 04:28 UTC, v-atulyadav commented
Hi @manishkumar1991 , can you please merge this PR. Thanks.

2022-10-04 06:55 UTC, v-marimanda approved these changes

2022-10-04 09:50 UTC, merged