Create AWS Create Policy Version to allow all resources
Azure/Azure-Sentinel pull request #6231
Opened 2022-09-27 07:03 UTC by praveenthepro

Required items, please complete
   
   Change(s):
   - See guidance below

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2022-09-28 21:33 UTC, ashwin-patil requested changes

2022-09-28 21:33 UTC, ashwin-patil commented on Hunting Queries/AWSCloudTrail/AWS Create Policy Version to allow all resources
> + | where EventSource == "iam.amazonaws.com" and EventName == "CreatePolicyVersion" and isempty(ErrorMessage) and UserAgent !has "Terraform"
Lets remove UserAgent filter.. its too broad to filter all terraform events. and add custom allowlist to filter out.

2022-09-28 21:33 UTC, ashwin-patil commented on Hunting Queries/AWSCloudTrail/AWS Create Policy Version to allow all resources
> + | where EventSource == "iam.amazonaws.com" and EventName == "CreatePolicyVersion" and isempty(ErrorMessage) and UserAgent !has "Terraform"
Add CreatePolicy to the event list. i tested the query and it works for both events.  
`EventName in ("CreatePolicy","CreatePolicyVersion")`

2022-09-28 21:33 UTC, ashwin-patil commented on Hunting Queries/AWSCloudTrail/AWS Create Policy Version to allow all resources
> + | summarize EventCount = count(), StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated), Policy_added = make_set(Action) by UserIdentityUserName, EventSource, EventName,UserAgent,AWSReg
Add a filter for interesting actions.

`| where Action in (ActionToMonitor)`

2022-10-03 12:37 UTC, v-dvedak commented
@praveenthepro, Can you please address the comments shared?

2022-10-06 14:54 UTC, v-marimanda commented
@praveenthepro  can you please take look  on above comments.

2022-10-07 04:11 UTC, praveenthepro commented
Currently this use case is discussion for clubbing this with another privilege escalation use case. Hopefully will update the changes next week.

2022-10-11 09:34 UTC, v-spadarthi commented
@praveenthepro : Could you please update if any ?

2022-10-11 11:12 UTC, closed without merging

2022-10-11 11:15 UTC, praveenthepro commented
This is an dublicate use case, which is already covered in the below PRhttps://github.com/Azure/Azure-Sentinel/commit/d3683d8deaee64938d434d51a348751362e4f05f