Add Initial Parser for Window Sysmon Event 3
Azure/Azure-Sentinel pull request #6530
Opened 2022-11-01 09:06 UTC by goosvorbook

Required items, please complete
   
   Change(s):
    - Added ASIM parser for Sysmon Event 3 ( both Event and WindowsEvent)

   Reason for Change(s):
   - New addition.

   Version Updated:
   - Non-existent to 0.0.1 

   Testing Completed:
   - See guidance below

2022-11-02 07:01 UTC, oshezaf requested changes

2022-11-02 07:01 UTC, oshezaf commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionMicrosoftSysmon.yaml
> +            IpAddr = SourceIp,
While correct, I feel it is somewhat confusing. I would project-rename to DstIpAddr and SrcIpAddr and have the others as aliases using extend later on.

2022-11-03 19:41 UTC, goosvorbook commented
@microsoft-github-policy-service agree [company="{Wortell}"]


Met vriendelijke groet / Kind regards,​​
Guus Verbeek
.
Bekijk
​ook eens:
***@***.***<https://www.wortell.nl/nl/themas/secure>
Consultant
.
+31611084192<tel:+31611084192>


From: microsoft-github-policy-service[bot] ***@***.***>
Sent: dinsdag 1 november 2022 10:07
To: Azure/Azure-Sentinel ***@***.***>
Cc: Guus Verbeek ***@***.***>; Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Add Initial Parser for Window Sysmon Event 3 (PR #6530)


@goosvorbook<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgoosvorbook&data=05%7C01%7Cguus.verbeek%40wortell.nl%7C20ee7de7d1f24e8322fb08dabbe87937%7Cb1a6616c94734cab82b6b6affeed3e12%7C1%7C0%7C638028904388015991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XV8feVvc%2BPc%2FDlcJYzhDgIYivCWPR25jyQwoSIJ0C64%3D&reserved=0> please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@microsoft-github-policy-service agree [company="{your company}"]



Options:

  *   (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
  *   (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
Contributor License Agreement
Contribution License Agreement

This Contribution License Agreement (“Agreement”) is agreed to by the party signing below (“You”),
and conveys certain license rights to Microsoft Corporation and its affiliates (“Microsoft”) for Your
contributions to Microsoft open source projects. This Agreement is effective as of the latest signature
date below.

  1.  Definitions.
“Code” means the computer software code, whether in human-readable or machine-executable form,
that is delivered by You to Microsoft under this Agreement.
“Project” means any of the projects owned or managed by Microsoft and offered under a license
approved by the Open Source Initiative (www.opensource.org<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.opensource.org%2F&data=05%7C01%7Cguus.verbeek%40wortell.nl%7C20ee7de7d1f24e8322fb08dabbe87937%7Cb1a6616c94734cab82b6b6affeed3e12%7C1%7C0%7C638028904388015991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FH%2BaP6gOTAjyNTt3Bohg0cnDMjze2EUx%2FrLPlgeRUp4%3D&reserved=0>).
“Submit” is the act of uploading, submitting, transmitting, or distributing code or other content to any
Project, including but not limited to communication on electronic mailing lists, source code control
systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
discussing and improving that Project, but excluding communication that is conspicuously marked or
otherwise designated in writing by You as “Not a Submission.”
“Submission” means the Code and any other copyrightable material Submitted by You, including any
associated comments and documentation.
  2.  Your Submission. You must agree to the terms of this Agreement before making a Submission to any
Project. This Agreement covers any and all Submissions that You, now or in the future (except as
described in Section 4 below), Submit to any Project.
  3.  Originality of Work. You represent that each of Your Submissions is entirely Your original work.
Should You wish to Submit materials that are not Your original work, You may Submit them separately
to the Project if You (a) retain all copyright and license information that was in the materials as You
received them, (b) in the description accompanying Your Submission, include the phrase “Submission
containing materials of a third party:” followed by the names of the third party and any licenses or other
restrictions of which You are aware, and (c) follow any other instructions in the Project’s written
guidelines concerning Submissions.
  4.  Your Employer. References to “employer” in this Agreement include Your employer or anyone else
for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
Submission is made in the course of Your work for an employer or Your employer has intellectual
property rights in Your Submission by contract or applicable law, You must secure permission from Your
employer to make the Submission before signing this Agreement. In that case, the term “You” in this
Agreement will refer to You and the employer collectively. If You change employers in the future and
desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
and secure permission from the new employer before Submitting those Submissions.
  5.  Licenses.

  *   Copyright License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license in the
Submission to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute
the Submission and such derivative works, and to sublicense any or all of the foregoing rights to third
parties.
  *   Patent License. You grant Microsoft, and those who receive the Submission directly or
indirectly from Microsoft, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license under
Your patent claims that are necessarily infringed by the Submission or the combination of the
Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
import or otherwise dispose of the Submission alone or with the Project.
  *   Other Rights Reserved. Each party reserves all rights not expressly granted in this Agreement.
No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
granted by implication, exhaustion, estoppel or otherwise.

  1.  Representations and Warranties. You represent that You are legally entitled to grant the above
licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
have disclosed under Section 3). You represent that You have secured permission from Your employer to
make the Submission in cases where Your Submission is made in the course of Your work for Your
employer or Your employer has intellectual property rights in Your Submission by contract or applicable
law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
  2.  Notice to Microsoft. You agree to notify Microsoft in writing of any facts or circumstances of which
You later become aware that would make Your representations in this Agreement inaccurate in any
respect.
  3.  Information about Submissions. You agree that contributions to Projects and information about
contributions may be maintained indefinitely and disclosed publicly, including Your name and other
information that You submit with Your Submission.
  4.  Governing Law/Jurisdiction. This Agreement is governed by the laws of the State of Washington, and
the parties consent to ex [...]

2022-11-03 19:42 UTC, goosvorbook commented
@microsoft-github-policy-service agree company="Wortell"


Met vriendelijke groet / Kind regards,​​
Guus Verbeek
.
Bekijk
​ook eens:
***@***.***<https://www.wortell.nl/nl/themas/secure>
Consultant
.
+31611084192<tel:+31611084192>


From: microsoft-github-policy-service[bot] ***@***.***>
Sent: donderdag 3 november 2022 20:42
To: Azure/Azure-Sentinel ***@***.***>
Cc: Guus Verbeek ***@***.***>; Mention ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] Add Initial Parser for Window Sysmon Event 3 (PR #6530)


@goosvorbook<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgoosvorbook&data=05%7C01%7Cguus.verbeek%40wortell.nl%7Ceb01ab4ededf418d778508dabdd36e5a%7Cb1a6616c94734cab82b6b6affeed3e12%7C1%7C0%7C638031013027382198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pODV14oc3sVaUVFfyJQqrmmlbHlpPf65pbxD80l0nq8%3D&reserved=0> the command you issued was incorrect. Please try again.

Examples are:

@microsoft-github-policy-service agree

and

@microsoft-github-policy-service agree company="your company"

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzure-Sentinel%2Fpull%2F6530%23issuecomment-1302584552&data=05%7C01%7Cguus.verbeek%40wortell.nl%7Ceb01ab4ededf418d778508dabdd36e5a%7Cb1a6616c94734cab82b6b6affeed3e12%7C1%7C0%7C638031013027538434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yNYaGZrvTLrC0YcfKfkz8rIhX%2FLUg6icjGx72MXp42Y%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFUKSRK2JROJYNZY2XKIUETWGQIPJANCNFSM6AAAAAART3STGE&data=05%7C01%7Cguus.verbeek%40wortell.nl%7Ceb01ab4ededf418d778508dabdd36e5a%7Cb1a6616c94734cab82b6b6affeed3e12%7C1%7C0%7C638031013027538434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vlDfuUXPM4aYTewDy0ZXNDNprHaz70OUjI7EM5JYH4I%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-11-11 12:25 UTC, goosvorbook commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionMicrosoftSysmon.yaml
> +let OutboundNetworkEvents =  union Sysmon3_Event, Sysmon3_WindowsEvent
I can probably do something like SourceIp in ('127.0.0.1', '0.0.0.0')
But these datafeeds do not contain HostIP

2022-11-11 12:26 UTC, goosvorbook commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionMicrosoftSysmon.yaml
> +            ASimMatchingHostname = "Both",
Can you specify which two are not needed of these 4

2022-11-13 08:10 UTC, oshezaf commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionMicrosoftSysmon.yaml
> +let OutboundNetworkEvents =  union Sysmon3_Event, Sysmon3_WindowsEvent
Indeed. It seems that Sysmon behaved differently on Linux and Windows. Actually, there is no easy way, as the source port is already defined as source port. Comparing to destination port does not provide more information. Our challenge in this case is limited to correctly assigning the process and user fields. 

Two heuristics that work for some cases are:
- Check which address is private. If only one address is private, it is the local machine, and they user and process fields should assume its role. 
- If either the source or destination hostname are empty ("-"), the other one is the local machine.

If both fail, let's just put the user and process fields on source. It is not correct, but I can't think of something else.

2022-11-13 08:50 UTC, oshezaf commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionMicrosoftSysmon.yaml
> +            ASimMatchingHostname = "Both",
The comment is always on the last line. GitHub just displays 4 lines for your convenience. Always, ASimMatchingHostname, And ASimMatchingIpAddr

2022-12-13 09:15 UTC, closed without merging