PCMatic Sentinel Solution
Azure/Azure-Sentinel pull request #6827
Opened 2022-12-06 18:14 UTC by johnpcmatic

Required items, please complete
   
   Change(s):
   - Initial PR

   Reason for Change(s):
   - NRT analytic rules not converting correctly to json. Have to manually update mainTemplate.json and createUiDefinition.json to validate and deploy

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - Need help

   Checked that the validations are passing and have addressed any issues that are present:
   - Need help

2022-12-06 18:22 UTC, johnpcmatic commented
@microsoft-github-policy-service agree [company="pcmatic inc"]



*John Farley*
Developer
732-718-6472



On Tue, Dec 6, 2022 at 1:14 PM microsoft-github-policy-service[bot] <
***@***.***> wrote:

> @johnpcmatic <https://github.com/johnpcmatic> please read the following
> Contributor License Agreement(CLA). If you agree with the CLA, please reply
> with the following information.
>
> @microsoft-github-policy-service agree [company="{your company}"]
>
>
> Options:
>
>    - (default - no company specified) I have sole ownership of
>    intellectual property rights to my Submissions and I am not making
>    Submissions in the course of work for my employer.
>    - (when company given) I am making Submissions in the course of work
>    for my employer (or my employer has intellectual property rights in my
>    Submissions by contract or applicable law). I have permission from my
>    employer to make Submissions and enter into this Agreement on behalf of my
>    employer. By signing below, the defined term “You” includes me and my
>    employer.
>
> Contributor License Agreement Contribution License Agreement
>
> This Contribution License Agreement (*“Agreement”*) is agreed to by the
> party signing below (*“You”*),
> and conveys certain license rights to Microsoft Corporation and its
> affiliates (“Microsoft”) for Your
> contributions to Microsoft open source projects. This Agreement is
> effective as of the latest signature
> date below.
>
>    1. *Definitions*.
>    *“Code”* means the computer software code, whether in human-readable
>    or machine-executable form,
>    that is delivered by You to Microsoft under this Agreement.
>    *“Project”* means any of the projects owned or managed by Microsoft
>    and offered under a license
>    approved by the Open Source Initiative (www.opensource.org).
>    *“Submit”* is the act of uploading, submitting, transmitting, or
>    distributing code or other content to any
>    Project, including but not limited to communication on electronic
>    mailing lists, source code control
>    systems, and issue tracking systems that are managed by, or on behalf
>    of, the Project for the purpose of
>    discussing and improving that Project, but excluding communication
>    that is conspicuously marked or
>    otherwise designated in writing by You as “Not a Submission.”
>    *“Submission”* means the Code and any other copyrightable material
>    Submitted by You, including any
>    associated comments and documentation.
>    2. *Your Submission*. You must agree to the terms of this Agreement
>    before making a Submission to any
>    Project. This Agreement covers any and all Submissions that You, now
>    or in the future (except as
>    described in Section 4 below), Submit to any Project.
>    3. *Originality of Work*. You represent that each of Your Submissions
>    is entirely Your original work.
>    Should You wish to Submit materials that are not Your original work,
>    You may Submit them separately
>    to the Project if You (a) retain all copyright and license information
>    that was in the materials as You
>    received them, (b) in the description accompanying Your Submission,
>    include the phrase “Submission
>    containing materials of a third party:” followed by the names of the
>    third party and any licenses or other
>    restrictions of which You are aware, and (c) follow any other
>    instructions in the Project’s written
>    guidelines concerning Submissions.
>    4. *Your Employer*. References to “employer” in this Agreement include
>    Your employer or anyone else
>    for whom You are acting in making Your Submission, e.g. as a
>    contractor, vendor, or agent. If Your
>    Submission is made in the course of Your work for an employer or Your
>    employer has intellectual
>    property rights in Your Submission by contract or applicable law, You
>    must secure permission from Your
>    employer to make the Submission before signing this Agreement. In that
>    case, the term “You” in this
>    Agreement will refer to You and the employer collectively. If You
>    change employers in the future and
>    desire to Submit additional Submissions for the new employer, then You
>    agree to sign a new Agreement
>    and secure permission from the new employer before Submitting those
>    Submissions.
>    5. *Licenses*.
>
>
>    - *Copyright License*. You grant Microsoft, and those who receive the
>    Submission directly or
>    indirectly from Microsoft, a perpetual, worldwide, non-exclusive,
>    royalty-free, irrevocable license in the
>    Submission to reproduce, prepare derivative works of, publicly
>    display, publicly perform, and distribute
>    the Submission and such derivative works, and to sublicense any or all
>    of the foregoing rights to third
>    parties.
>    - *Patent License*. You grant Microsoft, and those who receive the
>    Submission directly or
>    indirectly from Microsoft, a perpetual, worldwide, non-exclusive,
>    royalty-free, irrevocable license under
>    Your patent claims that are necessarily infringed by the Submission or
>    the combination of the
>    Submission with the Project to which it was Submitted to make, have
>    made, use, offer to sell, sell and
>    import or otherwise dispose of the Submission alone or with the
>    Project.
>    - *Other Rights Reserved*. Each party reserves all rights not
>    expressly granted in this Agreement.
>    No additional licenses or rights whatsoever (including, without
>    limitation, any implied licenses) are
>    granted by implication, exhaustion, estoppel or otherwise.
>
>
>    1. *Representations and Warranties*. You represent that You are
>    legally entitled to grant the above
>    licenses. You represent that each of Your Submissions is entirely Your
>    original work (except as You may
>    have disclosed under Section 3). You represent that You have secured
>    permission from Your employer to
>    make the Submission in cases where Your Submission is made in the
>    course of Your work for Your
>    employer or Your employer has intellectual property rights in Your
>    Submission by contract or applicable
>    law. If You are signing this Agreement on behalf of Your employer, You
>    represent and warrant that You
>    have the necessary authority to bind the listed employer to the
>    obligations contained in this Agreement.
>    You are not expected to provide support for Your Submission, unless
>    You choose to do so. UNLESS
>    REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE
>    WARRANTIES
>    EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED
>    UNDER THIS AGREEMENT IS
>    PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO,
>    ANY WARRANTY OF
>    NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
>    2. *Notice to Microsoft*. You agree to notify Microsoft in writing of
>    any facts or circumstances of which
>    You later become aware that would make Your representations in this
>    Agreement inaccurate in any
>    respect.
>    3. *Information about Submissions*. You agree that contributions to
>    Projects and information about
>    contributions may be maintained indefinitely and disclosed publicly,
>    including Your name and other
>    information that You submit with Your Submission.
>    4. *Governing Law/Jurisdiction*. This Agreement is governed by the
>    laws of the State of Washington, and
>    the parties consent to exclusive jurisdiction and venue in the federal
>    courts sitting in King County,
>    Washington, unless no federal subject matter jurisdiction exists, in
>    which case the parties consent to
>    exclusive jurisdiction and venue in the Superior Court of King County,
>    Washington. The parties waive all
>    defenses of lack of personal jurisdiction and forum non-conveniens.
>    5. *Entire Agreement/Assignment*. This Agreement is the entire
 [...]

2022-12-06 18:24 UTC, johnpcmatic commented
@microsoft-github-policy-service agree company="pcmatic inc"



*John Farley*
Developer
732-718-6472



On Tue, Dec 6, 2022 at 1:23 PM microsoft-github-policy-service[bot] <
***@***.***> wrote:

> @johnpcmatic <https://github.com/johnpcmatic> the command you issued was
> incorrect. Please try again.
>
> Examples are:
>
> @microsoft-github-policy-service agree
>
> and
>
> @microsoft-github-policy-service agree company="your company"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/Azure-Sentinel/pull/6827#issuecomment-1339792012>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZEA6TET7KLR4YDPV6G6N7DWL6AAZANCNFSM6AAAAAASV2PPQQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-08 06:04 UTC, v-sabiraj commented on Tools/Create-Azure-Sentinel-Solution/input/Solution_PCMaticSuperShield.json
> +    "Key Vault": [
Hey @johnpcmatic, you can't directly add the keyvault file in input file, can you please add the raw link of this file in pre requisites of playbooks if it is used there, thanks.

2022-12-08 14:37 UTC, johnpcmatic commented
Hi,

I have most of these worked out. There were just a couple items that I
could not fix.
I could not find this line in any of my templates: [image: image.png]

Also, I'm not sure how to remove the <unset> from this dropdown using a
query.

[image: image.png]

*John Farley*
Developer
732-718-6472



On Thu, Dec 8, 2022 at 1:04 AM v-sabiraj ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> Tools/Create-Azure-Sentinel-Solution/input/Solution_PCMaticSuperShield.json
> <https://github.com/Azure/Azure-Sentinel/pull/6827#discussion_r1042960318>
> :
>
> > +    "Parsers": [
> +      "Parsers/SuperShieldActivity.txt"
> +    ],
> +    "Analytic Rules": [
> +      "Analytic Rules/NRTKnownBadProcess.yaml",
> +      "Analytic Rules/NRTUnknownProcess.yaml",
> +      "Analytic Rules/NRTAllowedProcess.yaml"
> +    ],
> +    "Playbooks": [
> +      "Playbooks/BlockAllowProcess/azureDeploy.json",
> +      "Playbooks/RemoveProcess/azureDeploy.json"
> +    ],
> +    "Workbooks": [
> +      "Workbooks/PCMaticIncidentOverview.json"
> +    ],
> +    "Key Vault": [
>
> Hey @johnpcmatic <https://github.com/johnpcmatic>, you can't directly add
> the keyvault file in input file, can you please add the raw link of this
> file in pre requisites of playbooks if it is used there, thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/Azure-Sentinel/pull/6827#pullrequestreview-1209503573>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZEA6TEDQ2WYD2XWG5YUCFLWMF27DANCNFSM6AAAAAASV2PPQQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-15 05:11 UTC, v-mchatla commented
Hi @v-spadarthi,
Please help the author with his Queries.
Thanks

2022-12-15 13:42 UTC, v-sabiraj commented
@johnpcmatic , can you please check and revert the changes from Iotthreatmonitering zip ? thanks.
![image](https://user-images.githubusercontent.com/94349919/207873756-d8c68a94-e908-4190-bba7-1ffc9f511743.png)

2022-12-15 13:49 UTC, v-sabiraj requested changes

2022-12-15 13:49 UTC, v-sabiraj commented on Solutions/PCMatic SuperShield/Logo/pcmatic-green-outline.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 730.55 166.19"><defs><style>.cls-1{fill:#29b34b;}.cls-2{fill:#1e4620;}</style></defs><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-na
@johnpcmatic, Do not use illegal attributes: data-name, style, xmlns:link and SVG Id should be unique guid, thanks.

2022-12-15 13:49 UTC, v-sabiraj commented on Solutions/PCMatic SuperShield/Data/Solution_PCMaticSuperShield.json
> +    "Logo": "<img src=\"https://raw.githubusercontent.com/johnpcmatic/Azure-Sentinel/pcm-sentinel/Solutions/PCMatic%20SuperShield/Logo/pcmatic-green-outline.png\" width=\"200px\" height=\"45px\">",
@johnpcmatic , please use the raw libk of svg, and also check for the dimensions [here](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2). 
![image](https://user-images.githubusercontent.com/94349919/207875208-7e166909-b962-4a86-858a-8939ea89e626.png)

2022-12-15 13:50 UTC, v-sabiraj commented
@johnpcmatic, as suggested please create solution with V2 tool of solution packaging. Please find the guidelines for the same [here](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md).

2022-12-15 13:51 UTC, v-sabiraj commented
@aprakash13, can you please check the Analytic Rules, thanks.

2022-12-15 15:52 UTC, johnpcmatic commented
@v-sabiraj, I think I solved the Analytic Rules issue. The query data was
nested under a "properties" property. Once I moved the query data outside
that property, the rules converted correctly.


*John Farley*
Developer
732-718-6472



On Thu, Dec 15, 2022 at 8:51 AM v-sabiraj ***@***.***> wrote:

> @aprakash13 <https://github.com/aprakash13>, can you please check the
> Analytic Rules, thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/Azure-Sentinel/pull/6827#issuecomment-1353114950>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZEA6TGPBMYIAOCKI42P5XDWNMO5NANCNFSM6AAAAAASV2PPQQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-15 15:54 UTC, johnpcmatic commented
And just to confirm, the end user should create a Key Vault before
deploying the Sentinel solution, correct?


*John Farley*
Developer
732-718-6472



On Thu, Dec 15, 2022 at 10:52 AM John Farley ***@***.***> wrote:

> @v-sabiraj, I think I solved the Analytic Rules issue. The query data was
> nested under a "properties" property. Once I moved the query data outside
> that property, the rules converted correctly.
>
>
> *John Farley*
> Developer
> 732-718-6472
>
>
>
> On Thu, Dec 15, 2022 at 8:51 AM v-sabiraj ***@***.***>
> wrote:
>
>> @aprakash13 <https://github.com/aprakash13>, can you please check the
>> Analytic Rules, thanks.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Azure/Azure-Sentinel/pull/6827#issuecomment-1353114950>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AZEA6TGPBMYIAOCKI42P5XDWNMO5NANCNFSM6AAAAAASV2PPQQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-12-20 06:28 UTC, v-sabiraj commented
@aprakash13, can you please check on the Analytic rules, thanks.

2022-12-23 05:33 UTC, v-spadarthi commented
@aprakash13, can you please check on the Analytic rules, thanks.

2022-12-26 07:18 UTC, v-spadarthi commented
@johnpcmatic : Please resolve the conflicts and below comments
<img width="493" alt="image" src="https://user-images.githubusercontent.com/101796244/209515848-4afbd5aa-22a2-4a80-9a00-1459a23f1acc.png">
1.For Logo ,Do not use illegal attributes: data-name, style, xmlns:link and SVG Id should be unique guid
<img width="830" alt="image" src="https://user-images.githubusercontent.com/101796244/209514395-c26dc9f1-3329-48b2-8c96-e6d543479ccb.png">
2.In solution input file please change the below highlighted contents
<img width="697" alt="image" src="https://user-images.githubusercontent.com/101796244/209514868-d1c3cbe7-a94a-4bbf-bc0f-112bc387fe15.png">
Please update the Logo path and extension
Please use the version 2.0.0 and
Please remove the Keyvault in solution inputfile as suggested by @v-sabiraj and can you please add the raw link of this file in prerequisites of playbooks if it is used there, thanks.
3.For workbook please fix below errors
Please use "fromTemplateId" like below
[Azure-Sentinel](https://github.com/Azure/Azure-Sentinel)/[Solutions](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions)/[OracleWebLogicServer](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/OracleWebLogicServer)/[Workbooks](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/OracleWebLogicServer/Workbooks)/OracleWorkbook.json 
<img width="953" alt="image" src="https://user-images.githubusercontent.com/101796244/209515676-b0007c8e-299d-4826-9142-d9886e3b92b5.png">
<img width="871" alt="image" src="https://user-images.githubusercontent.com/101796244/209515727-20cf1f4c-f3d2-465a-a22f-e4e239b85c8b.png">
Once done above changes please re-create a package with V2 tool of solution packaging. Please find the guidelines for the same [here](https://github.com/Azure/Azure-Sentinel/blob/master/Tools/Create-Azure-Sentinel-Solution/V2/README.md).

2022-12-28 05:06 UTC, v-spadarthi commented
@johnpcmatic : Please address the above comments.

2022-12-28 14:34 UTC, johnpcmatic commented
Regarding the highlighted workbook activities, those sections are copied
from the Microsoft Incident Overview workbook. I believe the tactics, owner
and product name come from the selected incident so I'm not sure what I
need to fix. Can you please let me know? Thanks!


*John Farley*
Developer
732-718-6472



On Wed, Dec 28, 2022 at 12:06 AM v-spadarthi ***@***.***>
wrote:

> @johnpcmatic <https://github.com/johnpcmatic> : Please address the above
> comments.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/Azure-Sentinel/pull/6827#issuecomment-1366371902>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZEA6TB4TY2EM7WID7NFJ2TWPPDHBANCNFSM6AAAAAASV2PPQQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-03 04:44 UTC, manishkumar1991 commented
@johnpcmatic  for creating the playbooks arm template 
kindly use the playbook arm template generator tool for creating the playbook template and then fill out all the necessary meta data ,

Kindly check below link for arm template generator
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Playbook-ARM-Template-Generator

kindly check below link for reference on metadata details 
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/ThreatXCloud/Playbooks/ThreatXPlaybooks/ThreatX-BlockIP-URL  

And kindly create readme.md file for both the playbooks, kindly take the reference of below link
https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/ThreatXCloud/Playbooks/ThreatXPlaybooks/ThreatX-BlockIP-URL

2023-01-05 08:30 UTC, aprakash13 requested changes
The query logic are simple and look straightforward. However, 

1. For the sake of uniformity can we please have the analytic rule template's fields ordered to something similar to this: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/AristaAwakeSecurity/Analytic%20Rules/HighMatchCountsByDevice.yaml
2.  Please fix the validation errors that we are currently getting.

2023-01-05 13:37 UTC, johnpcmatic commented
***@***.***, thank you. *

Is it typical to have to go through maintemplate.json and
createUiDefinition.json and fix the errors manually? Most of the errors
seem to be introduced by createSolutionV2.ps1 when it creates unreferenced
variables.


*John Farley*
Developer
732-718-6472



On Thu, Jan 5, 2023 at 3:30 AM aprakash13 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The query logic are simple and look straightforward. However,
>
>    1. For the sake of uniformity can we please have the analytic rule
>    template's fields ordered to something similar to this:
>    https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/AristaAwakeSecurity/Analytic%20Rules/HighMatchCountsByDevice.yaml
>    2. Please fix the validation errors that we are currently getting.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/Azure-Sentinel/pull/6827#pullrequestreview-1236999277>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZEA6TG6EULNIN2FA74N4Z3WQ2BB3ANCNFSM6AAAAAASV2PPQQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-10 04:33 UTC, v-atulyadav commented
Hi @johnpcmatic , please resolve checks failed. Thank you.

2023-01-12 11:15 UTC, aprakash13 commented
> The query logic are simple and look straightforward. However,
> 
> 1. For the sake of uniformity can we please have the analytic rule template's fields ordered to something similar to this: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/AristaAwakeSecurity/Analytic%20Rules/HighMatchCountsByDevice.yaml
> 2. Please fix the validation errors that we are currently getting.

To give a little additional context on the validation errors. Below are the errors that we are getting: 

  1.  "Errors: The name 'SuperShieldActivity' does not refer to any known table, tabular variable or function."
 
  We probably need to define the schema of the SuperShieldActivity table here:  https://github.com/Azure/Azure-Sentinel/tree/master/.script/tests/KqlvalidationsTests/CustomTables
as json  - read here https://github.com/Azure/Azure-Sentinel#pull-request-kql-validation-check


 2.  Error:  " In template NRTKnownBadProcess.yaml/ NRTUnknownProcess.yaml/ NRTAllowedProcess.yaml there was an error while parsing: Invalid data model. Missing required identifiers in 'EntityMappings' for type 'FileHash'. Required identifiers are one of the following combinations: Algorithm, Value, but found System.Exception with message "Invalid data model. Missing required identifiers in 'EntityMappings' for type 'FileHash'. Required identifiers are one of the following combinations: Algorithm, Value"


In the entity mapping of the analytical rule - we probably need to change how the FileHash entity type is mapped. It should be something similar to below where we have both the identifiers - Algorithm, Value

 entityType: FileHash
    fieldMappings:
      - identifier: Value
        columnName: FileHashValue
      - identifier: Algorithm
        columnName: FileHashType

2023-01-16 02:37 UTC, aprakash13 commented
Thanks for making the changes. I still see a bunch of validation errors. Could you please look into these as well?

##[error]Content Validation check Failed: Please update text from 'Azure Sentinel' to 'Microsoft Sentinel' in file '.github/workflows/sentinel-deploy-fc73a920-ad71-42b0-ab9a-2cd8ed01205c.yml'

##[error]Incorrect Json file. File path: Tools/Create-Azure-Sentinel-Solution/V2/WorkbookMetadata/WorkbooksMetadata.json. Error message: Unexpected string in JSON at position 166177

##[error]Error: File 'Solutions/PCMatic SuperShield/Data/Solution_PCMaticSuperShield.json' has a total of '1' broken hyperlinks. Please review and rectify the following hyperlinks: 
 https://raw.githubusercontent.com/Azure-Sentinel/pcm-sentinel/Solutions/PCMatic%20SuperShield/Logo/pcmatic-green-outline.png

2023-01-23 05:41 UTC, v-atulyadav commented
@johnpcmatic , please use the raw link of svg, and also check for the dimensions [here](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2).
<img width="484" alt="image" src="https://user-images.githubusercontent.com/104008048/213972741-649dbaec-c4f7-4f67-be80-07db4bf9f47a.png">

2023-01-25 04:25 UTC, v-atulyadav commented
> @johnpcmatic , we still waiting for fix of raw link check for the dimensions [here](https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V2). <img alt="image" width="484" src="https://user-images.githubusercontent.com/104008048/213972741-649dbaec-c4f7-4f67-be80-07db4bf9f47a.png">

please see below FYR
<img width="520" alt="image" src="https://user-images.githubusercontent.com/104008048/214479632-4e92e706-d166-49e6-84ab-e3d7405b19b3.png">

2023-01-27 07:40 UTC, v-atulyadav commented on Solutions/PCMatic SuperShield/Workbooks/PCMaticWorkbook.json
> +  "fallbackResourceIds": [
Hi @johnpcmatic , can you please leave fallbackResourceIds as an empty array.

2023-02-02 06:04 UTC, aprakash13 approved these changes
Approved from a query perspective. Please feel free to merge if other components look good.

2023-02-02 06:19 UTC, v-atulyadav commented
Hi @johnpcmatic, I could see the following error when deploying the workbook. Could you please fix it? or you can paste screenshots of the working workbook here. Thanks.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/104008048/216247185-8d73e5cd-3cc2-4bbe-8ee1-d73d455ca87b.png">

2023-02-07 03:54 UTC, v-atulyadav commented
Hi @johnpcmatic, waiting for your reply. Thanks.

2023-02-07 08:26 UTC, manishkumar1991 commented on Solutions/PCMatic SuperShield/Playbooks/BlockAllowProcess/readme.md
> +
Because of the space in between the url "PCMatic SuperShield" Links are not working, Kindly check.

2023-02-07 08:26 UTC, manishkumar1991 commented on Solutions/PCMatic SuperShield/Playbooks/RemoveProcess/readme.md
> +[![Deploy to Azure Gov](https://aka.ms/deploytoazuregovbutton)](https://portal.azure.us/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Sentinel%2Fmaster%2FSolu
Because of the space in between the url "PCMatic SuperShield" Links are not working, Kindly check.

2023-02-07 08:51 UTC, manishkumar1991 commented on Solutions/PCMatic SuperShield/Playbooks/BlockAllowProcess/readme.md
> +    * PC Matic API Credentials Secret name : Your Key name for the stored api secret .
during deployment of Playbook i, Keyvault name is not asked 
![image](https://user-images.githubusercontent.com/97503740/217197018-afa67525-5fac-48f3-9269-55e7a1d68a05.png)

2023-02-07 08:57 UTC, manishkumar1991 commented on Solutions/PCMatic SuperShield/Playbooks/RemoveProcess/readme.md
> +    * PC Matic API Credentials Secret name : Your Key name for the stored api secret .
Same here , Keyvault name is not getting asked 

![image](https://user-images.githubusercontent.com/97503740/217198315-bc0b6a25-8a10-455e-8c78-43e00dd28953.png)

2023-02-07 13:06 UTC, johnpcmatic commented
Hi All,

Sorry, I have been pulled off onto another project temporarily. I will get
back to this soon. Thanks!


*John Farley*
Developer
732-718-6472



On Tue, Feb 7, 2023 at 3:57 AM Manish Kumar ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In Solutions/PCMatic SuperShield/Playbooks/RemoveProcess/readme.md
> <https://github.com/Azure/Azure-Sentinel/pull/6827#discussion_r1098363428>
> :
>
> > + ## IMPORTANT NOTE
> + The following instructions apply only to the Logic Apps. For comprehensive, detailed instructions, please use the documentation at  - [PC Matic Sentinel Solution support documentation](https://www.pcmatic.com/)
> +
> +### Prerequisites
> +1. API credentials. To get API credentials, login into the PC Matic portal and navigate to Account Settings --> User Management. Click the 'Add User' button and create a new user with the 'API Credentials' user role.
> +3. [Important step]Store the API username and password as a secret in Key vault. Format the secret as a colon-separated pair, e.g. ***@***.***:passw0rd.Provide the name of the stored secret during deployment.
> +
> +### Deployment instructions
> +1. Deploy the playbook by clicking on "Deploy to Azure" button. This will take you to deploying an ARM Template wizard.
> +
> +[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Sentinel%2Fmaster%2FSolutions%2FPCMatic <https://aka.ms/deploytoazurebutton)%5D(https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Sentinel%2Fmaster%2FSolutions%2FPCMatic> SuperShield%2FPlaybooks%2FRemoveProcess%2Fazuredeploy.json)
> +[![Deploy to Azure Gov](https://aka.ms/deploytoazuregovbutton)](https://portal.azure.us/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Sentinel%2Fmaster%2FSolutions%2FPCMatic <https://aka.ms/deploytoazuregovbutton)%5D(https://portal.azure.us/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FAzure-Sentinel%2Fmaster%2FSolutions%2FPCMatic> SuperShield%2FPlaybooks%2FRemoveProcess%2Fazuredeploy.json)
> +
> +2. Fill in the required parameters:
> +    * Keyvault name : Enter the key vault name where secret key is stored .
> +    * PC Matic API Credentials Secret name : Your Key name for the stored api secret .
>
> Same here , Keyvault name is not getting asked
>
> [image: image]
> <https://user-images.githubusercontent.com/97503740/217198315-bc0b6a25-8a10-455e-8c78-43e00dd28953.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/Azure-Sentinel/pull/6827#pullrequestreview-1286663536>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZEA6TDMNGAJZM5VSWXCDHLWWIFAHANCNFSM6AAAAAASV2PPQQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-10 05:59 UTC, v-atulyadav commented
Hi @johnpcmatic, please respond on above comments. Thanks

2023-02-15 04:39 UTC, v-atulyadav commented
Hi @johnpcmatic, can you please assign someone who will take care of this PR?

2023-02-15 12:26 UTC, johnpcmatic commented
Hi Atul,

I believe Sherry was closing this PR for now.


*John Farley*
Developer
732-718-6472



On Tue, Feb 14, 2023 at 11:39 PM v-atulyadav ***@***.***>
wrote:

> Hi @johnpcmatic <https://github.com/johnpcmatic>, can you please assign
> someone who will take care of this PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Azure/Azure-Sentinel/pull/6827#issuecomment-1430746359>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZEA6TH6EX355SBIZNWEO6DWXRMY5ANCNFSM6AAAAAASV2PPQQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-16 04:26 UTC, v-atulyadav commented
Hi Atul,

Sorry... I think I forgot to mention that PC Matic PR #6827 will need to be closed temporarily.
They will reopen it when they have a bit more time.

Thanks,
Sherry

2023-02-16 04:26 UTC, closed without merging