Hunting Queries KQL validations for Multiple Solutions
Azure/Azure-Sentinel pull request #7285
Opened 2023-02-07 05:24 UTC by v-vdixit

Required items, please complete
   
   Change(s):
   - Fixed failing kql validations in multiple solutions Hunting Queries

   Reason for Change(s):
   - Failing kql validation tests

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2023-03-06 13:52 UTC, devikamehra requested changes

2023-03-06 13:52 UTC, devikamehra commented on Solutions/Oracle Cloud Infrastructure/Hunting Queries/OCIDestinationsOut.yaml
> +  | summarize count() by SrcIpAddr, DstIpAddr, DstPortNumber, data_sourceAddress_s
Remove data_sourceAddress_s and map IPCustomEntity = SrcIpAddr.

2023-03-06 13:52 UTC, devikamehra commented on Solutions/OracleDatabaseAudit/Hunting Queries/OracleDBAuditDbConnectNonOperationalTime.yaml
> +  | where tostring(day_of_week) in~ ('0.00:00:00', '6.00:00:00') or hour_of_day between (18 .. 8)
In addition to this, hour_of_day between (8 .. 18)

2023-03-06 13:52 UTC, devikamehra commented on Solutions/GoogleCloudPlatformDNS/Hunting Queries/GCPDNSRareDomains.yaml
> +  | summarize count() by Query, SrcIpAddr
In this case also, remove the SrcIpAddr as this hunting query is only looking for DNS query alone.

2023-03-07 11:48 UTC, v-vdixit commented on Solutions/GoogleWorkspaceReports/Hunting Queries/GWorkspaceRareDocType.yaml
> +  | extend AccountCustomEntity = users
Hi @devikamehra I have added 'users' parameter from line 18 only in the query, thanks!

2023-03-07 11:52 UTC, v-vdixit commented on Solutions/GoogleCloudPlatformDNS/Hunting Queries/GCPDNSRareErrors.yaml
> +  | summarize count() by EventResultDetails, Query, SrcIpAddr
Once we remove SrcIpAddr from line 18, the query is unable to identify SrcIpAddr column being used in line 21 of the query, please suggest a fix for this, thanks!

2023-03-13 12:57 UTC, devikamehra requested changes

2023-03-13 12:57 UTC, devikamehra commented on Solutions/GoogleCloudPlatformDNS/Hunting Queries/GCPDNSRareErrors.yaml
> +  | summarize count() by EventResultDetails, Query, SrcIpAddr
I understand that would happen. We would have to remove it from mapping at line 21 also.

2023-03-13 12:57 UTC, devikamehra commented on Solutions/GoogleWorkspaceReports/Hunting Queries/GWorkspaceRareDocType.yaml
>    | summarize users = makeset(ActorEmail), count() by DocType
Use make_set instead

2023-03-14 05:49 UTC, devikamehra requested changes

2023-03-14 05:49 UTC, devikamehra commented on Solutions/GoogleCloudPlatformDNS/Hunting Queries/GCPDNSRareDomains.yaml
>      fieldMappings:
Remove IP from field mapping as well. This is applicable to all the queries.

2023-03-14 10:06 UTC, devikamehra approved these changes

2023-03-14 10:18 UTC, v-dvedak approved these changes

2023-03-14 10:18 UTC, merged