Added 2 new queries related to suspicious BEC file access.
Azure/Azure-Sentinel pull request #7421
Opened 2023-02-24 00:33 UTC by petebryan

Required items, please complete
   
   Change(s):
   - Added 2 new queries looking for suspicious file access patterns related to Business Email Compromise scenarios

   Reason for Change(s):
   - New content

   Version Updated:
   - N/A

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

2023-02-26 09:32 UTC, oshezaf requested changes

2023-02-27 20:19 UTC, petebryan commented on Detections/ASimFileEvent/SuspiciousAccessOfBECRelatedDocuments.yaml
> +  | where EventProduct in ("SharePoint 365", "Azure File Storage", "OneDrive" , "SharePoint")
I've responded to this via email.

2023-02-27 20:24 UTC, petebryan commented on Detections/ASimFileEvent/SuspiciousAccessOfBECRelatedDocuments.yaml
> +  | extend IpAddr = columnifexists("IpAddr", SrcIpAddr)
In several situations I have found IpAddr isn't present so this is needed to ensure it works across all workspaces.

2023-02-28 09:20 UTC, oshezaf commented on Detections/ASimFileEvent/SuspiciousAccessOfBECRelatedDocuments.yaml
> +  | project-reorder TimeGenerated, User, EventType, EventResult, EventProduct, FilePath, HttpUserAgent, IpAddr, number_of_files_accessed, baseline_count, files_accessed
For 2: I meant [this](https://learn.microsoft.com/en-us/azure/sentinel/surface-custom-details-in-alerts) (and the [YAML counterpart](https://github.com/Azure/Azure-Sentinel/wiki/Query-Style-Guide#customdetails)). While projected fields appear when the user go to "events" to run the query, custom fields are now available directly in the incident experience.

2023-03-08 05:09 UTC, v-sabiraj commented
@petebryan, there are few comments, can you please check on them, thanks.

2023-03-13 23:17 UTC, petebryan commented on Detections/ASimFileEvent/SuspiciousAccessOfBECRelatedDocuments.yaml
> +  | extend OriginalEvent = columnifexists("EventOriginalType","Unknown")
So this was something that was flagged by the validations here - we've asked for these edge cases to be fixed and hopefully they will be improved soon but these are needed for the pipeline to pass for now and given the minimal cost of this I will leave it in.

2023-03-13 23:43 UTC, petebryan commented on Detections/ASimFileEvent/SuspiciousAccessOfBECRelatedDocuments.yaml
> +  | extend SPuser = case(gettype(_AuthDetails) == "array", tostring(parse_json(tostring(todynamic(_AuthDetails)[0].principals))[0].id), "Unknown")
1 & 2. I've collected these elements and will look at telemetry for more detail on specific events where it's populated to understand the full range of situations. I will feed this into planning to get this updated to the parser, we can then update this query once the new parser is out.
3. Moved this down to after our User extraction.
4. In testing on large data sets parse_json was quicker to execute than parse on a consistent basis. However I have simplified this line as it was un-necessarily complex.

2023-03-13 23:59 UTC, petebryan commented on Detections/ASimFileEvent/SuspiciousAccessOfBECRelatedDocuments.yaml
> +alertDetailsOverride:
Added

2023-03-13 23:59 UTC, petebryan commented on Detections/ASimFileEvent/SuspiciousAccessOfBECRelatedDocuments.yaml
> +  | summarize number_of_files_accessed = dcount(FilePath), files_accessed=make_set(FilePath, MaxSize=1000) by User, bin(TimeGenerated, 1d)
Good point, added

2023-03-14 00:04 UTC, petebryan commented on Detections/ASimFileEvent/SuspiciousAccessOfBECRelatedDocuments.yaml
> +  | project-reorder TimeGenerated, User, EventType, EventResult, EventProduct, FilePath, HttpUserAgent, IpAddr, number_of_files_accessed, baseline_count, files_accessed
Understood, I've added those

2023-03-14 00:04 UTC, petebryan commented on Detections/ASimFileEvent/SuspiciousAccessOfBECRelatedDocuments.yaml
> +  | where isnotempty(User)
Good suggestion, have re-written.

2023-03-27 21:58 UTC, ashwin-patil approved these changes

2023-03-27 22:22 UTC, merged