AzureStorage-Enrichment
Azure/Azure-Sentinel pull request #7496
Opened 2023-03-06 03:19 UTC by rushriva

Required items, please complete
   
   Change(s):
   - Added analytical rule and workbook to Azure storage solution

   Reason for Change(s):
   - Azure Storage Solution Enrichment

   Version Updated:
   - NA
   
   Testing Completed:
   - Tested in local subscription

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

-----------------------------------------------------------------------------------------------------------

2023-03-08 07:40 UTC, v-prasadboke commented
Hello @rushriva One of the check is failing for the pr,
Can you please resolve the following

2023-03-15 04:50 UTC, v-atulyadav commented
Looking into this validation failures.

2023-03-24 03:25 UTC, shainw requested changes

2023-03-24 03:25 UTC, shainw commented on Solutions/Azure Storage/Analytic Rules/Detection of data exfiltration activities from Azure storage.yaml
> +      - identifier: FullName
Don't use legacy entity mapping any longer, change to Name + NTDomain or another strong identifier pair - https://learn.microsoft.com/en-us/azure/sentinel/entities-reference#user-account

2023-03-24 03:25 UTC, shainw commented on Solutions/Azure Storage/Analytic Rules/Detection of data exfiltration activities from Azure storage.yaml
> +version: 1.0.1
First version should be 1.0.0, right?

2023-03-24 03:25 UTC, shainw commented on Solutions/Azure Storage/Analytic Rules/Detection of data exfiltration activities from Azure storage.yaml
> +queryFrequency: 20m
20m, seems closer to an NRT analytic.  If that is the case, then we should change it to that type.  If not, then have it query over a longer period of time and simply bin(TimeGenerated, 20m) the results so your failureCountThreshold still applies.

https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/binfunction

2023-03-30 10:42 UTC, v-prasadboke commented
Hello @shainw any updates

2023-04-11 13:52 UTC, v-prasadboke commented
Hello @vakohl any feedback on this

2023-04-25 11:48 UTC, v-prasadboke commented
Hello @vakohl please provide your update on this

2023-04-27 10:57 UTC, v-prasadboke commented
Hello @vakohl waiting for your feedback

2023-05-03 05:04 UTC, v-prasadboke commented
Hello @vakohl waiting for your feddback

2023-05-05 05:08 UTC, v-prasadboke commented
Hello @vakohl waiting for your feedback

2023-05-09 12:00 UTC, v-prasadboke commented
Hello @vakohl waiting for your feedback

2023-05-18 16:18 UTC, v-prasadboke commented
Hello @vakohl shain has made some changes

2024-11-29 06:01 UTC, closed without merging