New queries for AAD Connect and OAuth app abuse
Azure/Azure-Sentinel pull request #7608
Opened 2023-03-20 23:54 UTC by petebryan

Required items, please complete
   
   Change(s):
   - Created new detection looking for full_access_as_app being granted to application
   - Created new detection to look for suspicious signins by AAD Connect sync accounts
   - Created hunting query to look for SSH connections to hots running AAD Connect

   Reason for Change(s):
   - New content

   Testing Completed:
   - Y

   Checked that the validations are passing and have addressed any issues that are present:
   - Y

2023-03-24 06:03 UTC, v-sabiraj commented
@devikamehra, can you please check on the files added, thanks.

2023-03-27 21:53 UTC, ashwin-patil requested changes, later dismissed
Other Queries looks good just connector missing for one of the query.

2023-03-27 21:53 UTC, ashwin-patil commented on Hunting Queries/MultipleDataSources/PotentialSSHTunneltoAADConnectHost.yaml
> +requiredDataConnectors:
Connector missing for imNetworkSesssion

2023-03-28 13:41 UTC, ashwin-patil approved these changes

2023-03-28 14:03 UTC, merged