Update in MultiplePasswordresetsbyUser.yaml Detection
Azure/Azure-Sentinel pull request #7672
Opened 2023-03-28 13:12 UTC by v-vdixit

Required items, please complete
   
   Change(s):
   - Tuning the rule to reduce noise due to inclusion of SSPR and Password flow interrupt events

   Reason for Change(s):
   - Changes as per the issue #6799 

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2023-03-30 12:05 UTC, v-atulyadav commented
Hi @devikamehra,
please provide your feedback on this
Thanks

2023-04-04 08:55 UTC, devikamehra requested changes

2023-04-04 08:55 UTC, devikamehra commented on Detections/MultipleDataSources/MultiplePasswordresetsbyUser.yaml
>          columnName: AccountCustomEntity
1. This should be Name.
2. Also, line 101 is not required. We can directly use Account and Computer.
3. For Host also, map Name and NTDomain/DnsDomain mapping. FullName is deprecated.
4. TargetUserName also requires split by @

2023-04-04 10:28 UTC, v-atulyadav commented
Hi @v-vdixit, please check above comments from @devikamehra. Thanks

2023-04-04 16:22 UTC, devikamehra approved these changes

2023-04-05 04:22 UTC, v-dvedak approved these changes

2023-04-05 04:22 UTC, merged