Quality upgrade in queries
Azure/Azure-Sentinel pull request #7707
Opened 2023-03-31 04:44 UTC by v-vdixit

Required items, please complete
   
   Change(s):
   - Updating queries of analytic rules to be migrated to AAD  solution

   Reason for Change(s):
   - See guidance below

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - See guidance below

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

# Guidance <- remove section before submitting
-----------------------------------------------------------------------------------------------------------
## Before submitting this PR please ensure that you have read the following sections and filled out the changes, reason for change and testing complete sections:

Thank you for your contribution to the Microsoft Sentinel Github repo.

> Details of the code changes in your submitted PR.  Providing descriptions for pull requests ensures there is context to changes being made and greatly enhances the code review process.  Providing associated Issues that this resolves also easily connects the reason.
   
   Change(s):
   - Updated syntax for XYZ.yaml

   Reason for Change(s):
   - New schema used for XYZ.yaml
   - Resolves ISSUE #1234

   Version updated:
   - Yes
   - Detections/Analytic Rule templates are required to have the version updated

> The code should have been tested in a Microsoft Sentinel environment that does not have any custom parsers, functions or tables, so that you validate no incorrect syntax and execution functions properly.  If your submission requires a custom parser or function, it must be submitted with the PR.

   Testing Completed:
   - Yes/No/Need Help

_Note: If updating a detection, you must update the version field._

> Before the submission has been made, please look at running the KQL and Yaml Validation Checks locally.
> https://github.com/Azure/Azure-Sentinel#run-kql-validation-locally

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes/No/Need Help
   
   _Note: Let us know if you have tried fixing the validation error and need help._

> References: 
> - [Guidance for Detection checks](https://github.com/Azure/Azure-Sentinel#pull-request-detection-template-structure-validation-check)
> - [General contribution guidance](https://github.com/Azure/Azure-Sentinel/wiki#what-can-you-contribute-and-how-can-you-create-contributions)
> - [PR validation troubleshooting](https://github.com/Azure/Azure-Sentinel#pull-request)

-----------------------------------------------------------------------------------------------------------

2023-04-03 17:24 UTC, devikamehra requested changes
Please verify queries for different suggestions. Also, please check if any of the query is duplicate with AAD solution content. We should not add those in the solution.

2023-04-03 17:24 UTC, devikamehra commented on Detections/AuditLogs/Cross-tenantAccessSettingsOrganizationInboundDirectSettingsChanged.yaml
>    | where B2BType = TargetResources[0].modifiedProperties[0].displayName has "b2bDirectInbound"
There is only b2bDirectConnectInbound

2023-04-03 17:24 UTC, devikamehra commented on Detections/AuditLogs/Cross-tenantAccessSettingsOrganizationOutboundDirectSettingsChanged.yaml
>    | where B2BType = TargetResources[0].modifiedProperties[0].displayName has "b2bDirectOutbound"
Again, only b2bDirectConnectOutbound

2023-04-03 17:24 UTC, devikamehra commented on Detections/AuditLogs/GuestAccountsAddedinAADGroupsOtherThanTheOnesSpecified.yaml
>    - entityType: Account
InitiatedByActionUserInformation can also be mapped as one entity of type account.

2023-04-04 09:35 UTC, devikamehra requested changes

2023-04-04 09:35 UTC, devikamehra commented on Detections/AuditLogs/Cross-tenantAccessSettingsOrganizationAdded.yaml
> +      - identifier: Name
This is not a valid Account value. Use custom details for storing this value.

2023-04-04 09:35 UTC, devikamehra commented on Detections/AuditLogs/Cross-tenantAccessSettingsOrganizationInboundCollaborationSettingsChanged.yaml
> +  | where B2BType = Properties.displayName has "b2bCollaborationInbound"
This is not required. Move lines 37 to 42 here.

2023-04-04 09:35 UTC, devikamehra commented on Detections/AuditLogs/Cross-tenantAccessSettingsOrganizationInboundCollaborationSettingsChanged.yaml
>          columnName: InitiatedByActionUserInformation
This should be Name

2023-04-04 09:35 UTC, devikamehra commented on Detections/AuditLogs/GuestAccountsAddedinAADGroupsOtherThanTheOnesSpecified.yaml
>          columnName: InitiatedByActionUserInformation
Map "Name" here.

2023-04-05 04:00 UTC, devikamehra requested changes

2023-04-06 08:09 UTC, devikamehra submitted a review, later dismissed

2023-04-10 09:28 UTC, v-rbajaj approved these changes

2023-04-10 14:30 UTC, v-dvedak approved these changes

2023-04-10 14:30 UTC, merged