FortiNet FortiGate - Updated category filter to use new CEF field
Azure/Azure-Sentinel pull request #7823
Opened 2023-04-16 09:37 UTC by devikamehra

Change(s):
   - Replaced AdditionalExtensions with DeviceEventCategory field to check for traffic field

   Reason for Change(s):
   - Change in CEF schema

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

2023-04-16 09:42 UTC, oshezaf approved these changes

2023-04-16 10:52 UTC, oshezaf commented
@devikamehra : we have here again the DeviceEventCategory validation issue:
- I asked Ashish to take over updating the validation with new schemas. We need to move forward with that.
- For now, probably best to do the same trick you did in another parsers using column_ifexists.

2023-04-16 10:55 UTC, oshezaf requested changes
Note my comment on the validation issue.

2023-04-17 04:57 UTC, devikamehra commented
> @devikamehra : we have here again the DeviceEventCategory validation issue:
> 
> * I asked Ashish to take over updating the validation with new schemas. We need to move forward with that.
> * For now, probably best to do the same trick you did in another parsers using column_ifexists.

@oshezaf I have made the changes for now. Also, work is already underway to improve the nuget packages for these fields.

2023-04-17 05:24 UTC, oshezaf approved these changes

2023-04-17 05:25 UTC, merged