AMA troubleshoot v2
Azure/Azure-Sentinel pull request #7966
Opened 2023-05-03 16:16 UTC by MeirLevinMicrosoft

Required items, please complete
   
   Change(s):
   - Printer should be static
   - Refactor Command classes
   - Comply PEP 8
   - Add argparse

   Reason for Change(s):
   - Prepare code for Cisco ASA support

   Version Updated:
   - Required only for Detections/Analytic Rule templates
   - See guidance below

   Testing Completed:
   - Tested both for python2 and python3

   Checked that the validations are passing and have addressed any issues that are present:
   - See guidance below

2023-05-05 04:51 UTC, v-prasadboke commented
Hello @MeirLevinMicrosoft looking into this

2023-05-09 10:14 UTC, NoamLandress requested changes

2023-05-09 10:24 UTC, MeirLevinMicrosoft commented on DataConnectors/CEF/cef_AMA_troubleshoot.py
> +PY3 = sys.version_info[0] == 3
Will do thanks

2023-05-09 10:24 UTC, MeirLevinMicrosoft commented on DataConnectors/CEF/cef_AMA_troubleshoot.py
> -MACHINE_ENV = "Prod" #Default value is Prod
Moved to find_dcr_cloud_environment since it used only there

2023-05-09 10:24 UTC, MeirLevinMicrosoft commented on DataConnectors/CEF/cef_AMA_troubleshoot.py
> +            if should_decode and PY3:
in verify_dcr_has_valid_content we need specific decoding to break the json lines

2023-05-09 10:24 UTC, MeirLevinMicrosoft commented on DataConnectors/CEF/cef_AMA_troubleshoot.py
> +        command_repr = super(CommandVerification, self).__repr__()
Not needed, solved it for both by adding inheritance from object

2023-05-09 10:24 UTC, MeirLevinMicrosoft commented on DataConnectors/CEF/cef_AMA_troubleshoot.py
> +                print_warning(self.Syslog_daemon_not_listening_warning.format(self.SYSLOG_DAEMON))
sting formatting, not sure I answered, please elaborate if needed

2023-05-09 10:24 UTC, MeirLevinMicrosoft commented on DataConnectors/CEF/cef_AMA_troubleshoot.py
> +    def format_command(command_object):
Will add

2023-05-09 11:54 UTC, v-prasadboke commented
Hello @MeirLevinMicrosoft please go through the following

2023-05-10 09:35 UTC, NoamLandress approved these changes

2023-05-10 11:47 UTC, MeirLevinMicrosoft commented
@microsoft-github-policy-service agree

2023-05-10 11:49 UTC, haim-na approved these changes

2023-05-10 11:55 UTC, merged