Replacing classic entity mapping style for detection with new
Azure/Azure-Sentinel pull request #8230
Opened 2023-06-09 12:44 UTC by d1mav0

Required items, please complete
   
   Change(s):
   - Updated Detections\MultipleDataSources\AADHostLoginCorrelation.yaml

   Reason for Change(s):
   - New style of entity mapping

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

2023-06-09 14:56 UTC, devikamehra requested changes

2023-06-11 10:08 UTC, d1mav0 commented on Detections/MultipleDataSources/AADHostLoginCorrelation.yaml
> -        columnName: AccountCustomEntity
Thanks for the comment! 

Where could I find the definition of what is currently supported for the analytics rule structure?

2023-06-18 09:41 UTC, devikamehra commented on Detections/MultipleDataSources/AADHostLoginCorrelation.yaml
> -        columnName: AccountCustomEntity
https://learn.microsoft.com/en-us/azure/sentinel/entities-reference

2023-06-21 04:49 UTC, v-atulyadav commented
Hi @d1mav0, @devikamehra shared a link with you please modify rule accordingly. Thanks

2023-06-22 13:44 UTC, v-atulyadav commented
Hi @d1mav0, looking forward to your response to the above comments. Thanks

2023-07-05 05:17 UTC, v-atulyadav commented
Hi @d1mav0, we are still waiting for your response . Thanks

2023-07-07 02:32 UTC, v-atulyadav commented
Hi @d1mav0, @devikamehra shared a link with you please modify rule accordingly. Thanks

2023-07-11 09:06 UTC, v-atulyadav commented
Hi @d1mav0, I look forward to hearing back from you regarding the comments above. Thanks

2023-07-13 09:43 UTC, v-atulyadav commented
Hi @d1mav0, we are still waiting for your response . Thanks

2023-07-18 09:41 UTC, v-atulyadav commented
We wanted to check on the status of PR #8230. PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation

2023-07-27 06:56 UTC, v-atulyadav commented
Hi @d1mav0, Since we have not received a response in the last 7 days, we are closing your PR #8230 per our standard operating procedures. If you still need support for this issue, you can re-open the PR at any time. 
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation.

2023-07-27 06:56 UTC, closed without merging