Vim auth update
Azure/Azure-Sentinel pull request #8580
Opened 2023-07-20 10:02 UTC by sparkmark

Required items, please complete
   
   Change(s):
   - Update VIM Parser to include new event ID's

   Reason for Change(s):
   - Update parser for better coverage

   Version Updated:
   - N/A

   Testing Completed:
   - Testing completed in my lab

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

2023-07-25 10:54 UTC, sparkmark commented
@vakohl ... just in case this is new PR that includes both files. I have also added the results of the tester. All the errors we get are from the config of the original parser. Let me know if you want to update the original parser to fix those issues as part of this update ?

2023-07-25 11:04 UTC, v-atulyadav commented
Hi @sparkmark,
Thank you for these commits. We will provide an update as soon as possible.

2023-08-04 02:46 UTC, vakohl commented
@sparkmark Thank you for your contribution. Can you please attach parser test results as file? Please follow guidelines: https://learn.microsoft.com/en-us/azure/sentinel/normalization-develop-parsers#test-results-submission-guidelines

Also, if you can attach the sample data too https://learn.microsoft.com/en-us/azure/sentinel/normalization-develop-parsers#samples-submission-guidelines

2023-08-04 02:46 UTC, vakohl requested changes

2023-08-04 02:46 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/ASimAuthenticationMicrosoftWindowsEvent.yaml
>  ParserQuery: |
can you increase the parser version to 0.2.2

2023-08-04 02:46 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/ASimAuthenticationMicrosoftWindowsEvent.yaml
>  ParserQuery: |
can you please add following property under ParserName?
EquivalentBuiltInParser: _ASim_Authentication_MicrosoftWindowsEvent

For reference: https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASimAuthentication/Parsers/ASimAuthenticationCiscoASA.yaml

2023-08-04 02:46 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/ASimAuthenticationMicrosoftWindowsEvent.yaml
> +  let WinLogin4768 = (disabled:bool=false){
do we need this block if we add 4768 in LogonEvents variable declared above?

2023-08-04 02:46 UTC, vakohl commented on Parsers/ASimAuthentication/Parsers/vimAuthenticationMicrosoftWindowsEvent.yaml
> +  let LogonStatus4768=datatable
same comments as ASIM parser applicable here.

2023-08-08 04:03 UTC, v-atulyadav commented
Hi @sparkmark, hope you are doing well. Just wanted to check if you got a chance to look at the suggestions shared. Please feel free to reach out to us for any queries and/or support.

2023-08-10 08:12 UTC, v-atulyadav commented
Hi @sparkmark,
We'd appreciate it if you could let us know when your work is finished. Feel free to contact us with any queries or support.
Thanks

2023-08-11 04:33 UTC, vakohl commented
@v-atulyadav I'm looking into past discussions internally regarding this PR. Pls wait for my update

2023-10-23 05:30 UTC, vakohl commented
@sparkmark Wanted to check regarding this PR. Would you like us to review the changes in this PR?

2023-10-25 05:51 UTC, v-atulyadav commented
Hi @sparkmark,
Please confirm if you would like us to review the changes in this PR as per vakohl's comment? Thanks

2023-10-27 04:32 UTC, v-atulyadav commented
Hi @sparkmark,
We're waiting for an update on this. Thanks

2023-10-30 07:49 UTC, sparkmark commented
> Hi @sparkmark,
> We're waiting for an update on this. Thanks

Hi, at this point in time we are not progressing with ASIM.

2023-10-30 13:50 UTC, v-atulyadav commented
Hi @sparkmark,
We are closing this PR now if you still need support for this issue, you can re-open the PR at any time. 
If you do re-open, we simply request that you ensure the PR has response to the last request. Thank you for your cooperation. Thank you.

2023-10-30 13:50 UTC, closed without merging