ASIM NetworkSession schema parser with its sample data and tester files for Palo Alto Cortex Data Lake
Azure/Azure-Sentinel pull request #9126
Opened 2023-09-29 15:09 UTC by niralishah-crest

Change(s):

- Added ASIM NetworkSession schema parser for Palo Alto Cortex Data Lake based on CEF data

Reason for Change(s):

- Initial version ASIM NetworkSession Parser

Version Updated:

- Initial version

Testing Completed:

- Yes

Checked that the validations are passing and have addressed any issues that are present:

- Yes

2023-10-03 04:44 UTC, v-atulyadav commented
Hi @niralishah-crest,
Thank you for raising Pull Request with us! We will review the Pull Request and get back to you by shortly. Thanks

2023-10-23 08:16 UTC, vakohl requested changes

2023-10-23 08:27 UTC, v-atulyadav commented
Hi @niralishah-crest, please check comments above from @vakohl and act accordingly. Thanks

2023-10-25 06:04 UTC, v-atulyadav commented
Hi @niralishah-crest,
To follow up appropriately, we would appreciate some indication of the timeframe for these changes. Thanks

2023-10-27 05:05 UTC, v-atulyadav commented
Hi @niralishah-crest, please act on @vakohl's comments. Thanks

2023-10-31 05:52 UTC, v-atulyadav commented
Hi @niralishah-crest,
We're waiting for an update on this. Thanks

2023-11-02 05:42 UTC, v-atulyadav commented
Hi @niralishah-crest,
A few changes were suggested by @vakohl 3 weeks back. Could you please make those changes and update this request accordingly? Thanks

2023-11-06 07:49 UTC, v-atulyadav commented
Hi @niralishah-crest, 
We look forward to hearing back from you. Thanks

2023-11-15 04:44 UTC, v-atulyadav commented
Hi @niralishah-crest, please update on above pending comments. Thanks

2023-11-17 10:12 UTC, v-rusraut commented
Hi @niralishah-crest,
Please work on above comment.
Thanks

2023-11-22 09:26 UTC, v-atulyadav commented
We wanted to check on the status of PR #9126. PR is pending for more than 30 days. Please let us know if you need any assistance to review this PR. Per our standard operating procedures if no response is received in the next 7 business days, we will close this PR. Thank you for your cooperation.

2023-11-24 09:20 UTC, jayeshprajapaticrest commented
@v-atulyadav 
Sorry for the inconvenience.
We are unable to get chance to fix the suggested changes.
But now we are working on it and will update the PR with the fix of suggested changes by next week. So please do not close this PR.
Thanks.

2023-11-24 09:33 UTC, v-atulyadav commented
Noted @jayeshprajapaticrest. Thanks

2023-12-01 10:41 UTC, v-atulyadav commented
Noted @niralishah-crest. Thanks

2023-12-11 13:21 UTC, niralishah-crest commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionPaloAltoCortexDataLake.yaml
> +  Title: Network Session ASIM filtering parser for Palo Alto Cortex Data Lake
Done

2023-12-11 13:24 UTC, niralishah-crest commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionPaloAltoCortexDataLake.yaml
> +      "10", "High"
We have done this based on mapping given in CommonSecuritLog table documentation as we don't have numeric mapping of severityLevel available in PaloAlto document.
![image](https://github.com/Azure/Azure-Sentinel/assets/107753570/d9b2cbea-25b5-4e12-9fc3-91dc2fdf3fda)
https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/commonsecuritylog

2023-12-11 13:25 UTC, niralishah-crest commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionPaloAltoCortexDataLake.yaml
> +          DstIpAddr = coalesce(DeviceCustomIPv6Address3, DestinationIP),
Done

2023-12-11 13:27 UTC, niralishah-crest commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionPaloAltoCortexDataLake.yaml
> +          DvcIpAddr = Computer,
Not sure as we don't have a live setup available. But in document, Computer field contains IP Addr while DeviceName contains host value.

2023-12-11 13:29 UTC, niralishah-crest commented on Parsers/ASimNetworkSession/Tests/PaloAlto_CortexDataLake_ASimNetworkSession_SchemaTest.csv
> +"(1) Warning: Missing recommended field [EventResultDetails]"
Done based on Reason field. Prepared a lookup based on possible values available in document.
https://docs.paloaltonetworks.com/pan-os/11-0/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/traffic-log-fields

2023-12-11 13:30 UTC, niralishah-crest commented on Sample Data/ASIM/CommonSecurityLog_Schema.csv
> +Activity,6,"System.String",string
Mapped with EventOriginalSubType

2023-12-11 13:30 UTC, niralishah-crest commented on Sample Data/ASIM/PaloAlto_CortexDataLake_ASimNetworkSession_RawLogs.txt
> +Mar 1 20:46:50 198.51.100.0 2206 4581 <14>1 2021-03-01T20:46:50.869Z stream-logfwd20-587718190-03011242-xynu-harness-zpqg logforwarder - panwlogs - CEF:0|Palo Alto Networks|LF|2.0|TRAFFIC|end|3|Profi
Done

2023-12-11 13:31 UTC, niralishah-crest commented on Parsers/ASimNetworkSession/Tests/PaloAlto_CortexDataLake_ASimNetworkSession_SchemaTest.csv
> +"(2) Info: Missing optional field [SrcUserId]"
Done

2023-12-11 13:33 UTC, niralishah-crest commented on Sample Data/ASIM/CommonSecurityLog_Schema.csv
> +DeviceCustomNumber2Label,113,"System.String",string
NetworkPackets is already mapped with FieldDeviceCustomNumber2

2023-12-11 13:34 UTC, niralishah-crest commented on Sample Data/ASIM/CommonSecurityLog_Schema.csv
> +DeviceCustomNumber3Label,116,"System.String",string
NetworkDuration is already mapped with FieldDeviceCustomNumber3

2023-12-11 13:34 UTC, niralishah-crest commented on Sample Data/ASIM/CommonSecurityLog_Schema.csv
> +DeviceCustomString1Label,118,"System.String",string
NetworkRuleName is already mapped with DeviceCustomString1

2023-12-11 13:36 UTC, niralishah-crest commented on Sample Data/ASIM/CommonSecurityLog_Schema.csv
> +DeviceCustomString5Label,126,"System.String",string
Done.
SrcZone = DeviceCustomString4
DstZone = DeviceCustomString5

2023-12-11 13:37 UTC, niralishah-crest commented on Sample Data/ASIM/CommonSecurityLog_Schema.csv
> +SimplifiedDeviceAction,156,"System.String",string
SimplifiedDeviceAction contains value in simplifiedform for DeviceAction. e.g. if DeviceAction field contains value as "Allowed" then SimplifiedDeviceAction field will have "Allow" as value.

2023-12-11 13:38 UTC, niralishah-crest commented
@v-atulyadav @vakohl 
We have addressed all review comments.
Thanks

2023-12-11 14:33 UTC, v-atulyadav commented
Thanks @niralishah-crest.

2023-12-29 04:34 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionPaloAltoCortexDataLake.yaml
> +      "10", "High"
@niralishah-crest @jayeshprajapaticrest 
We should not follow generic metric for this.

2023-12-29 04:35 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionPaloAltoCortexDataLake.yaml
> +          EventType = "NetworkSession"
@niralishah-crest @jayeshprajapaticrest 
pls update

2023-12-29 04:44 UTC, vakohl commented on Parsers/ASimNetworkSession/Tests/PaloAlto_CortexDataLake_ASimNetworkSession_SchemaTest.csv
> +"(1) Warning: Missing recommended field [EventResultDetails]"
great

2023-12-29 04:52 UTC, vakohl commented on Sample Data/ASIM/PaloAlto_CortexDataLake_ASimNetworkSession_RawLogs.txt
> +Mar 1 20:46:50 198.51.100.0 2206 4581 <14>1 2021-03-01T20:46:50.869Z stream-logfwd20-587718190-03011242-xynu-harness-zpqg logforwarder - panwlogs - CEF:0|Palo Alto Networks|LF|2.0|TRAFFIC|end|3|Profi
@niralishah-crest could find it mapped. Please re-check

2023-12-29 04:55 UTC, vakohl commented on Sample Data/ASIM/PaloAlto_CortexDataLake_ASimNetworkSession_RawLogs.txt
> +Mar 1 20:46:50 198.51.100.0 2206 4581 <14>1 2021-03-01T20:46:50.869Z stream-logfwd20-587718190-03011242-xynu-harness-zpqg logforwarder - panwlogs - CEF:0|Palo Alto Networks|LF|2.0|TRAFFIC|end|3|Profi
@niralishah-crest is this done?

2023-12-29 04:56 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionPaloAltoCortexDataLake.yaml
> +          DstDomain = coalesce(DestinationNTDomain, DstDomain)
@niralishah-crest 
please check this

2023-12-29 04:59 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionPaloAltoCortexDataLake.yaml
> +          DstUserIdType = iff(isnotempty(DstUserId), "UID", ""),
@niralishah-crest 
is this linux user id?
![image](https://github.com/Azure/Azure-Sentinel/assets/97222872/38cf5867-6d17-4247-84df-41eebd6e7c78)

2023-12-29 05:02 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionPaloAltoCortexDataLake.yaml
> +          DstUserIdType = iff(isnotempty(DstUserId), "UID", ""),
@niralishah-crest 
are values of linux user id type?
![image](https://github.com/Azure/Azure-Sentinel/assets/97222872/1bad8f9d-71f1-4e12-92da-62cbb4a4cb0d)

2023-12-29 05:06 UTC, vakohl commented on Sample Data/ASIM/CommonSecurityLog_Schema.csv
> +DeviceCustomNumber2Label,113,"System.String",string
ok

2023-12-29 05:06 UTC, vakohl commented on Sample Data/ASIM/CommonSecurityLog_Schema.csv
> +DeviceCustomNumber3Label,116,"System.String",string
ok

2023-12-29 05:07 UTC, vakohl commented on Sample Data/ASIM/CommonSecurityLog_Schema.csv
> +DeviceCustomString1Label,118,"System.String",string
ok

2023-12-29 05:08 UTC, vakohl commented on Sample Data/ASIM/CommonSecurityLog_Schema.csv
> +SimplifiedDeviceAction,156,"System.String",string
ok. DvcAction is mapped already

2023-12-29 05:45 UTC, vakohl commented on Parsers/ASimNetworkSession/Tests/PaloAlto_CortexDataLake_ASimNetworkSession_DataTest.csv
> +"(0) Error: 2 invalid value(s) (up to 10 listed) in 6 records (200.0%) for field [EventVendor] of type [Enumerated]: [""Palo Alto Networks""] (Schema:NetworkSession)"
@niralishah-crest 
duplicate entry. Palo Alto is already present. Please remove this change

2024-01-02 07:08 UTC, v-atulyadav commented
Hi @niralishah-crest,
There are some changes that Varun has suggested, please take a look at them. Thanks

2024-01-04 06:08 UTC, v-atulyadav commented
Hi @niralishah-crest,
We're waiting for an update on this. Thanks

2024-01-04 06:23 UTC, vakohl commented on ASIM/dev/ASimTester/ASimTester.csv
> +EventVendor,string,Mandatory,FileEvent,Enumerated,Microsoft|SentinelOne|Palo Alto Networks,
@niralishah-crest @jayeshprajapaticrest 
why updating FileEvent entry?

2024-01-04 06:28 UTC, vakohl commented on ASIM/dev/ASimTester/ASimTester.csv
> +EventProduct,string,Mandatory,NetworkSession,Enumerated,Fortigate|IOS|ISE|SDP|Vectra Stream|NSGFlow|Fireware|VPC|Azure Defender for IoT|Azure Firewall|M365 Defender for Endpoint|Sysmon|Sysmon for Lin
@niralishah-crest seems like an extra space

2024-01-04 06:59 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionPaloAltoCortexDataLake.yaml
> +          and (eventresult == "*" or eventresult == "Success")
@niralishah-crest @jayeshprajapaticrest 
Don't think this is correct, we are setting both success and failure. please validate

2024-01-04 07:09 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionPaloAltoCortexDataLake.yaml
> +          and (array_length(dvcaction) == 0)
@niralishah-crest @jayeshprajapaticrest 
DeviceAction value being set. Please validate this filter

2024-01-09 10:45 UTC, v-atulyadav commented
Hi @niralishah-crest, please check comments above from @vakohl and act accordingly. Thanks

2024-01-11 09:39 UTC, v-atulyadav commented
Hi @niralishah-crest, please act on above comments. Also check for branch conflicts. Thanks

2024-01-16 04:50 UTC, v-atulyadav commented
Hi @niralishah-crest,
There are some changes that Varun has suggested, please take a look at them. Thanks

2024-01-18 04:40 UTC, v-atulyadav commented
Hi @niralishah-crest,
Please work on above comment. Also look for a branch conflicts. Thanks

2024-01-19 11:52 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionPaloAltoCortexDataLake.yaml
> +          EventType = "NetworkSession"
NetworkSession seems valid.

2024-01-19 11:58 UTC, vakohl commented on Parsers/ASimNetworkSession/Tests/PaloAlto_CortexDataLake_ASimNetworkSession_SchemaTest.csv
> +"(1) Warning: Missing recommended field [EventResultDetails]"
couldn't find metric but sample log below has reason field.
https://docs.paloaltonetworks.com/cortex/cortex-data-lake/log-forwarding-schema-reference/network-logs/network-traffic-log/network-traffic-cef-fields

2024-01-19 12:00 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionPaloAltoCortexDataLake.yaml
> +      "10", "High"
keeping 9 and 10 as high only.

2024-01-19 12:02 UTC, vakohl commented on Sample Data/ASIM/PaloAlto_CortexDataLake_ASimNetworkSession_RawLogs.txt
> +Mar 1 20:46:50 198.51.100.0 2206 4581 <14>1 2021-03-01T20:46:50.869Z stream-logfwd20-587718190-03011242-xynu-harness-zpqg logforwarder - panwlogs - CEF:0|Palo Alto Networks|LF|2.0|TRAFFIC|end|3|Profi
no response, closing comment.

2024-01-19 12:13 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/ASimNetworkSessionPaloAltoCortexDataLake.yaml
> +          DstDomain = coalesce(DestinationNTDomain, DstDomain)
based on sample log. Couldn't find this value in sample log.

2024-01-19 12:18 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionPaloAltoCortexDataLake.yaml
> +          DstUserIdType = iff(isnotempty(DstUserId), "UID", ""),
userid mapping seems correct as per documentation - https://docs.paloaltonetworks.com/cortex/cortex-data-lake/log-forwarding-schema-reference/network-logs/network-traffic-log#network-traffic_network-traffic-source-user-info.uuid
but could validate id type as sample value not available.

2024-01-19 12:29 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionPaloAltoCortexDataLake.yaml
> +          and (eventresult == "*" or eventresult == "Success")
I've updated filter to check with EventResult field

2024-01-19 12:32 UTC, vakohl commented on Parsers/ASimNetworkSession/Parsers/vimNetworkSessionPaloAltoCortexDataLake.yaml
> +          and (array_length(dvcaction) == 0)
I've corrected this.

2024-01-19 12:44 UTC, vakohl commented on ASIM/dev/ASimTester/ASimTester.csv
> +EventProduct,string,Mandatory,NetworkSession,Enumerated,Fortigate|IOS|ISE|SDP|Vectra Stream|NSGFlow|Fireware|VPC|Azure Defender for IoT|Azure Firewall|M365 Defender for Endpoint|Sysmon|Sysmon for Lin
fixed

2024-01-19 12:44 UTC, vakohl commented on ASIM/dev/ASimTester/ASimTester.csv
> +EventVendor,string,Mandatory,FileEvent,Enumerated,Microsoft|SentinelOne|Palo Alto Networks,
removed

2024-01-19 12:47 UTC, vakohl commented on Parsers/ASimNetworkSession/Tests/PaloAlto_CortexDataLake_ASimNetworkSession_DataTest.csv
> +"(0) Error: 2 invalid value(s) (up to 10 listed) in 6 records (200.0%) for field [EventVendor] of type [Enumerated]: [""Palo Alto Networks""] (Schema:NetworkSession)"
fixed in parser

2024-01-19 13:04 UTC, vakohl approved these changes

2024-01-19 13:07 UTC, v-atulyadav approved these changes

2024-01-19 13:08 UTC, merged