Update "TI Map" analytics rules for performance
Azure/Azure-Sentinel pull request #9181
Opened 2023-10-09 16:47 UTC by kfriede

Required items, please complete
   
   Change(s):
   - Changed query to put any applicable WHERE filters before any SUMMARIZE calls for performance. 
   - Added ThreatIntelligenceTaxii data connector on missing analytics.

   Reason for Change(s):
   - Many of these queries would fail on real-world datasets due to summarization of unnecessary data. 
   - ThreatIntelligenceTaxii is a valid provider of ThreatIntelligenceIndicator table data and should be included

   Version Updated:
   - Yes

   Testing Completed:
   - Yes, as much as possible (don't have all data sources to test appropriately for some rules)

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

2023-10-09 18:33 UTC, kfriede commented
To whoever ends up picking this up, the KQL validation failures is due to Line 397 of  https://github.com/Azure/Azure-Sentinel/blob/master/.script/tests/KqlvalidationsTests/KqlValidationTests.cs 

The regex being used is overly-specific and not conducive for the performance improvements being made here.

2023-10-10 12:48 UTC, v-rbajaj commented
Hi @kfriede, thanks for raising this PR. We will review this PR by 13 Oct 2023.

2023-10-10 13:32 UTC, kfriede commented
This traces back to commit [16564be](https://github.com/Azure/Azure-Sentinel/commit/16564be03e3302e33a19e035a36e0b84c8426d44) from @aprakash13

2023-10-13 13:42 UTC, v-rbajaj commented
Hi @kfriede, for KQL validation, we will see what can be done in this case. 

We would need you to repackage this solution using this tool https://github.com/Azure/Azure-Sentinel/tree/master/Tools/Create-Azure-Sentinel-Solution/V3

Thanks

2023-10-17 09:08 UTC, v-rbajaj commented
Hi @kfriede, please provide update on above comment.

2023-10-20 11:53 UTC, v-rbajaj commented
Hi @kfriede, please provide some update on this PR

2023-10-23 10:21 UTC, kfriede commented
Hi @v-rbajaj, apologies I was out last week. I will look at repackaging the solution for these edits

2023-10-25 14:59 UTC, v-rbajaj commented
> Hi @v-rbajaj, apologies I was out last week. I will look at repackaging the solution for these edits
> 
> Edit: Solution has been repackaged for 3.0.2

Thanks @kfriede, will review the PR by 27 Oct, 2023.

2023-10-27 10:57 UTC, v-rbajaj commented on Solutions/Threat Intelligence/Package/createUiDefinition.json
> +        "description": "<img src=\"https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Logos/Azure_Sentinel.svg\"width=\"75px\" height=\"75px\">\n\n**Note:** _There may be [known issues](ht
Hi @kfriede, Please revert this change.

2023-10-27 12:39 UTC, kfriede commented on Solutions/Threat Intelligence/Package/createUiDefinition.json
> +        "description": "<img src=\"https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Logos/Azure_Sentinel.svg\"width=\"75px\" height=\"75px\">\n\n**Note:** _There may be [known issues](ht
@v-rbajaj done!

2023-10-31 10:43 UTC, v-rbajaj commented
Hi @kfriede, thanks. We are currently looking into the KQL validations and once that is fixed, we will revisit this PR by 2 Nov 2023.

2023-11-02 10:51 UTC, v-rbajaj commented
Hi @kfriede, we are still investigating on KQL validations, will get back to by 03 Nov 2023.

2023-11-13 11:53 UTC, kfriede commented
Hi @v-rbajaj, it's been over 1 week since your last update. Is this still under review?

2023-11-15 09:20 UTC, v-atulyadav commented
Hi @kfriede,
Apologies for the inconvenience, but due to unavailability, the review has been delayed. We assure you that you will receive an update on this by the end of the day tomorrow. Thank you.

2023-11-16 09:38 UTC, v-rbajaj commented
Hi @kfriede, we are working on the KQL changes and we will soon provide an update.

2023-11-17 16:06 UTC, blauwers requested changes

2023-11-17 16:06 UTC, blauwers commented on Solutions/Threat Intelligence/Analytic Rules/DomainEntity_CommonSecurityLog.yaml
>        | where Active == true and ExpirationDateTime > now()
This where statement needs to follow the summarize statement. Same for the other KQL queries.

2023-11-22 16:00 UTC, kfriede commented
@v-rbajaj after refactoring, files now give: `Kqlvalidations.Tests.KqlValidationTests.Validate_DetectionQueries_SkippedTemplatesDoNotHaveValidKql(fileName: "IPEntity_DuoSecurity.yaml", encodedFilePath: "L2hvbWUvdnN0cy93b3JrLzEvcy9Tb2x1dGlvbnMvVGhyZWF0IE"...)` in testing

2023-11-27 12:51 UTC, v-rbajaj commented
Hi @kfriede, sorry for the above commits, was trying to fix few errors from KQL validations. We are checking on it, will get back to you by 29 Nov 2023.

2023-11-29 17:11 UTC, kfriede commented
@v-rbajaj I’m good with #9369, and we can close this (#9181) when #9369 is merged


--
Kevin Friedemann
On Nov 28, 2023 at 5:01 AM -0800, v-rbajaj ***@***.***>, wrote:
> Hi @kfriede, can we merge #9369 as the changes there look similar and all the KQL validations have been fixed by @blauwers.
> If there are any changes you want to suggest on #9369 or want to contribute your changes, can you please comment on that PR?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-30 06:52 UTC, v-rbajaj commented
Thanks @kfriede, I have changed the PR status from open to draft and will close later once #9369 is merged.

2023-12-12 11:16 UTC, closed without merging

2023-12-12 11:16 UTC, v-rbajaj commented
Closing this PR as #9369 is merged.