SecurityAlert Entity Mapping Updates
Azure/Azure-Sentinel pull request #9407
Opened 2023-11-15 22:35 UTC by ddamenova

Change(s):
   - Manny and Diana updating account updating by splitting UPNSuffix and account name
- Changing authors of entity mappigns
- Removing extraneous custom entity named columns

   Reason for Change(s):
   -  Adjusting entity mappings for correlations

   Version Updated:
   - yes

   Testing Completed:
   - yes

   Checked that the validations are passing and have addressed any issues that are present:
   - no

2023-11-16 11:56 UTC, v-rbajaj commented
Hi @ddamenova, thanks for raising this PR, we will review this PR by 20 Nov 2023.

2023-11-20 19:51 UTC, shainw requested changes
A few things to fix up, but looking good.

2023-11-20 19:51 UTC, shainw commented on Detections/SecurityAlert/Massdownload_USBFileCopy.yaml
>      fieldMappings:
FullName needs to be fixed here, should be broken into Name and UPNSuffix

2023-11-20 19:51 UTC, shainw commented on Detections/SecurityEvent/AccessibilityFeaturesModification.yaml
> -        name: Vasileios Paschalidis
Don't make this change, this is not a MSecR person and we don't want to remove credit for external contributors.

2023-11-20 19:51 UTC, shainw commented on Detections/SecurityEvent/AdminSDHolder_Modifications.yaml
> +        name: Microsoft Security Research
Same here, don't make this change.  Only do this for MSecR folks.

2023-11-20 19:51 UTC, shainw commented on Detections/SecurityEvent/GroupCreatedAddedToPrivlegeGroup_1h.yaml
> +  | extend HostNameDomain = iff(DomainIndex != -1, substring(GroupCreateComputer, DomainIndex + 1), GroupCreateComputer)
Need to extend GroupCreateSubjectAccount for Account: Name and UPNSuffix to replace FullName

2023-11-21 01:28 UTC, shainw approved these changes

2023-11-21 01:29 UTC, merged