Update "Explicit MFA Deny"
Azure/Azure-Sentinel pull request #9555
Opened 2023-12-07 09:26 UTC by tduarte14

Required items, please complete
   
   Change(s):
   - Remove redundant line declaring Type (it's already there)
   - Add Host and OS fields to the end of the query
   - Add extra entities: App and Host
   - Fix IP entity (was using inexistent field)
   - Removed URL entity (was using ClientAppUsed, which was giving no value)

   Reason for Change(s):
   - Some Entities had broken field mapping, another had no value and some were needed.

   Version Updated:
   - Yes

   Testing Completed:
   - Yes

   Checked that the validations are passing and have addressed any issues that are present:
   - Yes

2023-12-07 16:40 UTC, ashwin-patil commented on Solutions/Microsoft Entra ID/Analytic Rules/ExplicitMFADeny.yaml
> +  - entityType: CloudApplication
can you also add  identifier: AppId and Fieldmapping for CloudApplication entity.

2023-12-07 17:10 UTC, ashwin-patil requested changes
suggested couple of changes on entity mappings

2023-12-08 10:58 UTC, tduarte14 commented on Solutions/Microsoft Entra ID/Analytic Rules/ExplicitMFADeny.yaml
> +  | extend Host=tostring(DeviceDetail_dynamic.displayName), OS=tostring(DeviceDetail_dynamic.operatingSystem)
The thing is that the same Public IP can be related to different devices, so I'm not sure you can even have a correct match from that block of code there. The host I got was from the signin logs, which is what we actually see on the logs. DeviceInfo shows many times no publicIP nor logged user, so it's hard to have a match.

2023-12-08 10:58 UTC, tduarte14 reviewed
added comments

2023-12-09 10:11 UTC, tduarte14 commented on Solutions/Microsoft Entra ID/Analytic Rules/ExplicitMFADeny.yaml
> +  | extend Host=tostring(DeviceDetail_dynamic.displayName), OS=tostring(DeviceDetail_dynamic.operatingSystem)
If you please don't agree, please review again.

2023-12-09 10:12 UTC, tduarte14 reviewed
added comments as why I don't agree on the review. Please check

2023-12-16 22:14 UTC, tduarte14 commented
Hi any feedback here?

2023-12-18 12:23 UTC, v-prasadboke commented
Hello @tduarte14 Ashwin is on leave till 22. He will get back to you as he comes back.

2024-01-08 16:41 UTC, ashwin-patil commented
> Hi any news here?

Hey, i started the review but forgot to submit final comments. Apologies for delay, let me know your thoughts on follow-up comments. I will keep an eye on this PR this week to respond sooner.

2024-01-09 04:22 UTC, v-prasadboke commented
Hey Thank you for the updates @ashwin-patil.

2024-02-16 06:30 UTC, v-prasadboke commented
Hello @tduarte14, Ashwin has requested some changes please work on it

2024-02-20 05:28 UTC, v-prasadboke commented
Hello @tduarte14,
Ashwin has suggested some changes please take a look into it.

2024-02-22 05:28 UTC, v-prasadboke commented
Hello @tduarte14, 
Ashwin has requested some changes earlier, Please have a look on it.

2024-02-26 11:28 UTC, v-prasadboke commented
Hello @tduarte14, 
You might be busy with something, commenting on this PR to please acknowledge Ashwin's comments.

2024-02-26 12:06 UTC, tduarte14 commented
Got the latest version 1.0.5, removed URL entity and added just CloudApplication entity. Ignored the Host entity for now

2024-02-26 13:17 UTC, tduarte14 commented
Also changed runtime to every 1h instead of 1d to improve MTTD. Added missing appId field on CloudApplication entity as you requested, thought it was there already

2024-02-28 08:42 UTC, v-prasadboke commented
Thank you @tduarte14.

2024-03-12 02:53 UTC, ashwin-patil approved these changes

2024-03-12 02:55 UTC, ashwin-patil commented on Solutions/Microsoft Entra ID/Analytic Rules/ExplicitMFADeny.yaml
> +  | extend Host=tostring(DeviceDetail_dynamic.displayName), OS=tostring(DeviceDetail_dynamic.operatingSystem)
Sounds good @tduarte14 . We will revisit this sometime again later. 
Thanks for the feedback.

2024-03-12 06:08 UTC, v-prasadboke approved these changes

2024-03-12 06:30 UTC, v-atulyadav approved these changes

2024-03-12 06:30 UTC, merged